### ISSUE TITLE
How to use vue-grid-layout

### ISSUE THREAD

**Issue by Qlipoth** [jbaysolutions/vue-grid-layout#1]
Hello, i try to use this component. I included it to head tag in my jade template
`
script(type='text/javascript', src='Vues/vue-grid-layout.min.js')
`
I created file grid.js

`$(document).ready(function() {
    var testLayout = [
        {"x":0,"y":0,"w":2,"h":2,"i":"0"},
        {"x":2,"y":0,"w":2,"h":4,"i":"1"},
        {"x":4,"y":0,"w":2,"h":5,"i":"2"},
        {"x":6,"y":0,"w":2,"h":3,"i":"3"},
    ];

    var GridLayout = VueGridLayout.GridLayout;
    var GridItem = VueGridLayout.GridItem;
    window.vm = new Vue({
        el: '#app',
        components: {
            GridLayout,
            GridItem,
        },
        data: function() {
            return {
                layout: null,
            };
        },
        template: [
        '<div>',
            '<div id="content" v-if="layout">',
                '<grid-layout',
                        ':layout.sync="layout"',
                        ':col-num="12"',
                        ':row-height="30"',
                        ':is-draggable="true"',
                        ':is-resizable="true"',
                        ':vertical-compact="true"',
                        ':margin="[10, 10]"',
                        ':use-css-transforms="true">',
                    '<grid-item v-for="item in layout"',
                               ':x.sync="item.x"',
                               ':y.sync="item.y"',
                               ':w.sync="item.w"',
                               ':h.sync="item.h"',
                               ':i="item.i">',
                        '{{item.i}}',
                    '</grid-item>',
                '</grid-layout>',
            '</div>',
        '</div>'
        ].join(' '),
       
        computed: {
        },
        ready: function() {
            var vm = this;
            vm.layout = testLayout;
        },
        methods: {
    

        },
    });
});`
and  added to head tag after library.

When i reload page, i have that result http://joxi.ru/zANYYPPUlYd0b2
What did I do wrong?

**Comment by gmsa** [comment]
Just replace 

    data: function() {
        return {
            layout: null,
        };
    },

with 

    data: function() {
        return {
            layout: [],
        };
    },

**Comment by Qlipoth** [comment]
No, it is still not working. I cant resize and drag blocks =(. https://ibin.co/2xHYahlMqxJU.gif

**Comment by gmsa** [comment]
Sorry for the late reply. 
I just published version 1.0.0, which should fix your problem. Example here: https://jsfiddle.net/gmsa/hdb5p6dn/
