### ISSUE TITLE
Does the min/max for width and height work?

### ISSUE THREAD

**Issue by abezulski** [jbaysolutions/vue-grid-layout#101]
I have some individual widgets that I want to prevent from resizing. I noticed new properties for grid-item:

- minW, maxW,
- minH, maxH

Adding them, doesn't seem to work, unless I'm doing something wrong here:

                        <grid-item v-for="w in widgets" v-if="w.open"
                                   :i="w.i"
                                   :x="w.x"
                                   :y="w.y"
                                   :w="w.w"
                                   :h="w.h"
                                   :maxW="3"
                                   :maxH="3"
                                   :minW="3"
                                   :minH="3"
                                   v-on:resize="widgetResize"
                                   drag-allow-from=".widget"
                                   drag-ignore-from=".no-drag"
                                   v-bind:class="{'hpanel widget': true}">
                            <keep-alive>
                                <component :is="w.type" v-bind:widget="w">
                                </component>
                            </keep-alive>
                        </grid-item>

Any suggestions or is it a bug?

**Comment by gmsa** [comment]
Prop names need to be kebab-case: https://vuejs.org/v2/guide/components.html#camelCase-vs-kebab-case

```
<grid-item v-for="w in widgets" v-if="w.open"
		   :i="w.i"
		   :x="w.x"
		   :y="w.y"
		   :w="w.w"
		   :h="w.h"
		   :max-w="3"
		   :max-h="3"
		   :min-w="3"
		   :min-h="3"
		   v-on:resize="widgetResize"
		   drag-allow-from=".widget"
		   drag-ignore-from=".no-drag"
		   v-bind:class="{'hpanel widget': true}">
	<keep-alive>
		<component :is="w.type" v-bind:widget="w">
		</component>
	</keep-alive>
</grid-item>
```

**Comment by abezulski** [comment]
@gmsa Silly me...Thanks!
