### ISSUE TITLE
grid-items behaving strangely

### ISSUE THREAD

**Issue by AndreaRylander** [jbaysolutions/vue-grid-layout#102]
I have a problem with how the grid-items behave when being dragged. When the grid is first rendered everything is fine, they align just like I set them up to do in my "boxes" variable. But then when I draged them they cannot be near each other, they create gaps between them and push each other away if I try to put them next to each other.  What could be causing this behaviour?? 
Here is the code (Im sorry for the way it looks)

`<grid-layout :layout="boxes" :col-num="12" 
                :row-height="30"  :is-draggable="true" 
                :is-resizable="true"
                 :vertical-compact="true" 
                :margin="[10, 10]"
                :use-css-transforms="true">`

`<grid-item class="grid" v-for="box in boxes" :key="box.name" :x="box.x" :y="box.y" :w="box.w" :h="box.h" :i="box.i" 
                    :min-w="box.minw"
                    :min-h="box.minh"
                    @resize="resizeEvent">

                    <div v-if="box.name == 'Box1'" class="widget">
                        <agent-chart  @threshold="thresholdStatus = true" id="myCanvas" 
                               :members="selectedMembers" />
                    </div>
                    <div v-if="box.name == 'Box2'" class="widget">
                        <call-ratio :queues="queueInformation" :type="2" />
                    </div>
                    <div v-if="box.name == 'Box3'" class="widget">
                        <call-ratio :queues="queueInformation" :type="1" />
                    </div>
                    <div v-if="box.name == 'Box4'" class="widget">

                        <gauge class="agentsWrapper" :config="gaugeConfig1" :queues="queueInformation" />
                    </div>
                    <div v-if="box.name == 'Box5'"  class="widget">

                        <gauge class="agentsWrapper" :config="gaugeConfig2" :queues="queueInformation" />
                    </div>
                    <div v-if="box.name == 'Box6'" class="widget">

                        <agent-status class="agentsWrapper" :members="selectedMembers" />
                    </div>
                    <div v-if="box.name == 'Box7'" class="widget">

                        <sla-bar :info="queueInformation" />
                    </div>
                    <div v-if="box.name == 'Box8'" class="widget">

                        <queue-status :queues="queueInformation" />
                    </div>
                </grid-item>
                </grid-layout>`

boxes: 

` var boxes = [
                    { 'name': 'Box1', "x": 0, "y": 60, "w": 2.5, "h": 10.5,"minw": 2.5, "minh":10.5, "i":1 },
                    { 'name': 'Box2', "x": 2.5, "y": 60, "w": 2.5, "h": 4.5,"minw": 2.5, "minh":4.5,  "i":2 },
                    { 'name': 'Box3', "x": 5, "y": 60, "w": 2.5, "h": 4.5,"minw": 2.5, "minh":4.5,  "i":3 },
                    { 'name': 'Box4', "x": 6, "y": 122, "w": 3.5, "h": 6, "minw": 3.5, "minh":6,  "i": 4},
                    { 'name': 'Box5', "x": 2.5, "y": 120, "w": 3.5, "h": 6, "minw": 3.5, "minh":6,  "i":5},
                    { 'name': 'Box6', "x": 7.5, "y": 60, "w": 4.5, "h": 5,"minw": 4.5, "minh":5, "i":6 },
                    { 'name': 'Box7', "x": 0, "y": 128, "w": 12, "h": 3, "minw": 12, "minh":3, "i":7},
                    { 'name': 'Box8', "x": 0, "y": 125, "w": 12, "h": 3, "minw": 12, "minh":3,  "i":8},
                ]`

CSS:

`.grid {
    border: solid;
    display: block;
    border-color: grey;
}

.widget {
    width: 100%;
    height: 100%;
}

.widget>div {
    max-width: 100%;
    max-height: 100%;
    object-fit: contain;
}`

**Comment by gmsa** [comment]
Can't really tell without a sample to reproduce your problem, but I don't think using float values for height and width will work.
