### ISSUE TITLE
How to insert different html in each grid-item.

### ISSUE THREAD

**Issue by Masanix** [jbaysolutions/vue-grid-layout#103]
Hello,

I need some help.
I'd like to insert different html in each grid-item. 

The plugins works **flawlessly** when is used in this way 
```
<grid-item v-for="item in layout" :x="item.x" :y="item.y" :w="item.w" :h="item.h  :i="item.i">
   <b>{{item.i}}</b>: [{{item.x}}, {{item.y}}, {{item.w}}, {{item.h}}, {{item.minW}}]
</grid-item>
```

But instead I'd like to add my own HTML code like in this example
```
<grid-item :x="0" :y="0" :w="2" :h="2" :i="0">
   <div v-html="item.template" :href="Current_Project"></div>
</grid-item>
```
or
```
<grid-item :x="10" :y="5" :w="2" :h="2" :i="1">
   <h2><i class="material-icons">info_outline</i>   {{Current_Project}}</h2>
</grid-item>
```
Thanks in advance for your helpful support.

KR
Giovanni

**Comment by gmsa** [comment]
Hi,
Using v-html is an option and it works: https://stackoverflow.com/questions/42379819/how-to-pass-component-with-content-to-griditem-in-vue-grid-layout
