### ISSUE TITLE
Question: use different data model for grid

### ISSUE THREAD

**Issue by TomFranssen** [jbaysolutions/vue-grid-layout#104]
I would like to use product information in my grid. Is it possible to use these array values?
The row would be used for the y value and the column for the x value.

```javascript
    var products = [
        {
            name: 'Integer posuere erat a ante venenatis dapibus posuere velit aliquet.',
            row: 1,
            column: 1,
            width: 1,
            height: 1
        },
        {
            name: 'Integer oudawdawhuadhouwhoudw ahdowhodaw hoadwou',
            row: 1,
            column: 2,
            width: 1,
            height: 1
        }
    ];
```

If I try to use it like this I get an error.

```
        <grid-item v-for="item in layout"
                   :x="item.row"
                   :y="item.column"
                   :w="item.width"
                   :h="item.height"
                   :i="item.name">
            {{item.i}}
        </grid-item>
```

This is the error:
`[Vue warn]: Error in nextTick: "Error: VueGridLayout: Layout[0].x must be a number!"`

**Comment by fouratj** [comment]
I run into this problem yesterday. When you pass the array into the parent component, it requires that the values match up with it's children grid-item components. Since on the parent, there is no x, y props, it throws an error. Basically, you'll have to map over your array so that row, column are converted into x, y, and pass that into grid-layout.

**Comment by TomFranssen** [comment]
@fouratj yes that can be an option. Then I also need to unmap them again when saving the grid.

**Comment by fouratj** [comment]
Yep, that's what I do.

**Comment by TomFranssen** [comment]
@fouratj do you have an example? I support you use computed values for this?

**Comment by fouratj** [comment]
No, as I get the data from the server, I map over it converting (in my data set) pos_x -> x, pos_y -> y, then I save each item onto the data object of the component, which is then passed into both <grid-layout> and <grid-item>. Also, on the data object, I keep an object (by id) of all the original items as well in their unmodified state. 

On the fire events of grid-layout, I captured the id, access the original object, update the values there, then send the original object with updated values back to the server. The converted array of objects stays locally and never leaves. I hope that made sense.

**Comment by TomFranssen** [comment]
It makes sense. I will try to implement something similar. Thanks for the explanation.

**Comment by ChadTaljaardt** [comment]
Do you guys have an example of this?

**Comment by anilkumar-boyka** [comment]
here i an example 
i was getting data from server like this
layout = [{"name":1,config : {"x":0,"y":0,"i":2,"h":3,"w",3}}]

 And in my grid layout i was mapping data in this way
 <grid-item
        v-for="(item, i) in layout"
      
        :key="i"
       
        :x="item.config.x"
        :y="item.config.y"
        :w="item.config.w"
        :h="item.config.h"
        :i="item.config.i"
      >
{{item.config.i}}
</grid-item>
above code giving me this error - [Vue warn]: Error in nextTick: "Error: VueGridLayout: Layout[0].x must be a number!"

so i made my layout element like this = layout = [{"x":0,"y":0,"i":2,"h":3,"w",3}];
<grid-item
        v-for="(item, i) in layout"
      
        :key="i"
       
        :x="item.x"
        :y="item.y"
        :w="item.w"
        :h="item.h"
        :i="item.i"
      >
{{item.i}}
</grid-item>
here only one root/parent object is there 
it solved my problem
