### ISSUE TITLE
Not possible for touch?

### ISSUE THREAD

**Issue by SmiffyKMc** [jbaysolutions/vue-grid-layout#110]
Trying to build the library into an electron application. It will be running on a Surface which will need touch. Can't seem to drag and drop or resize using Googles Device tool.

Is there a way to enable it or is it not available?

Thanks

**Comment by gmsa** [comment]
Touch currently doesn't really work properly right now. I never really tried to look into it. Feel free to submit a PR if you manage to get it to work.

**Comment by rafaelmagalhaes** [comment]
Hi I managed to get to work for touch screens,
I used Jquery Ui (Touch https://github.com/joshgerdes/jquery.ui.touch)

I added the js file to my project and on my component i imported jquery ui
 
```
import VueGridLayout from 'vue-grid-layout'
import jqueryUi from './jquery.ui.touch'

export default {
    components: {
        GridLayout,
        GridItem,
    },
    mounted() {
        $('.vue-grid-layout').addTouch();
    },

}
```
