### ISSUE TITLE
Qustion:  how to change the pink color of drag placeholder? 

### ISSUE THREAD

**Issue by terrygogo** [jbaysolutions/vue-grid-layout#113]
I hope to change the color of the box that shows when drag. It can be done by set css entry? 

Thanks in advance.

Terry

**Comment by gmsa** [comment]
Yes, just set your custom styling for .vue-grid-item.vue-grid-placeholder

**Comment by feelslike1929** [comment]
I've tried the css entries (with and without !important):
.vue-grid-item.vue-grid-placeholder {background:blue;}
and also 
.vue-grid-item.vue-grid-placeholder {background-color:blue;}

However, it is not changing the background. Am I doing something wrong?

**Comment by feelslike1929** [comment]
Sorry, I figured out what was happening -- the style tag in the component can't be scoped. Is this a bug?

**Comment by xuanxiaoxiao** [comment]
> Sorry, I figured out what was happening -- the style tag in the component can't be scoped. Is this a bug?
You need to add '/deep/', if you use vue

**Comment by PhilLovesToCode** [comment]
I too had this question and could not find the answer in the docs or the examples.  It would be helpful to provide reference to all of the style tags in the docs, and show them in the examples.

**Comment by gmsa** [comment]
Started documenting how to customize the styling (here)[https://jbaysolutions.github.io/vue-grid-layout/guide/styling.html], will add more details next week
