### ISSUE TITLE
Keep aspect ratio on resize

### ISSUE THREAD

**Issue by jersobh** [jbaysolutions/vue-grid-layout#117]
Please, it would be great to keep an aspect ratio while resizing :)

**Comment by marverix** [comment]
The plugin uses Interact.js to handle drag&drop, resize, etc. This lib has an option to (squere resize)[http://interactjs.io/docs/#resize-square]. Would this be an solution? If yes then it's very easy to add wrapper for it.

**Comment by Sean-Der** [comment]
Hey @marverix that would work perfectly for me.

I have a bunch of video elements in the DOM, and trying to figure out the best way to resize them (while maintaining) aspect ratio. Currently just going to stretch the videos to fit the container (and then fixing to match the aspect ratio after the user is done) but that isn't the best experience.

**Comment by marverix** [comment]
Hey @Sean-Der,
I have just tried out this `squereResize` from Interact.js and it seems that... doesn't work. Not sure why and to be honest right now I don't have time to deeper investigation. But I have a feeling that it will be much more easier to implement own keep aspect ratio feature then forcing this library to do it. Maybe in some free time I will dig deeper.

**Comment by validide** [comment]
Hi,

This option would be nice and I believe it was supported at some point:

https://github.com/jbaysolutions/vue-grid-layout/blob/master/src/components/GridItem.vue#L793

I suspect this  `preserveAspectRatio: true` should have been changed when upgrading the `interactjs` library ([migration docs](https://interactjs.io/docs/migrating/#resize-aspectratio-modifier) see the `aspectRatio` section).

Not sure who is the project maintainer so would it be worth creating a merge request for this?

**Comment by gmsa** [comment]
@validide sure, submit a PR please. Thanks

**Comment by gmsa** [comment]
Fixed by adding preserveAspectRatio prop on GridItem. Available on release 2.3.12
