### ISSUE TITLE
scrollbar conflicts with resize handle

### ISSUE THREAD

**Issue by galipmedia** [jbaysolutions/vue-grid-layout#118]
Hello I would like to have a scrollbar on the contents of a single grid item but when you go to click on the scroll bar itself the horizontal resize handle is triggered. Could someone explain to me how to disable the horizontal resize handle so it only uses the bottom right one?

**Comment by marverix** [comment]
Could you bring an example source code?

**Comment by wojiaohanshuai** [comment]
@galipmedia  have you solved the problem? i meet the same problem, i want to drag the box only by click the bottom right icon, but when i click the right edge or bottom edge it also can be draged, how can i disable the drag event emited by click bottom edge or right edge @marverix ? thank you .

**Comment by elmat0** [comment]
Hopefully #144 gives us the ability to do this.
