### ISSUE TITLE
Strange behaviour with multiple grids

### ISSUE THREAD

**Issue by xernobyl** [jbaysolutions/vue-grid-layout#119]
When using multiple grids only the last one works correctly, the other ones think you're dragging items to the last one. I'm trying to find a workaround for this.

**Comment by jgn-epp** [comment]
Try using completely unique i-props

**Comment by xernobyl** [comment]
My items have sequential i's, should the grid-layout's also have i's?

**Comment by xernobyl** [comment]
It looks like as the grid-item you're dragging uses the wrong grid-layout (always the last one) when I drag with multiple layouts

**Comment by gmsa** [comment]
which version of vue and vue-grid-layout are you using? This was fixed by #22

**Comment by xernobyl** [comment]
Everything is in the most current version as of now. I'll have a look at that issue. Maybe I'm doing something wrong somehow.

**Comment by xernobyl** [comment]
Hello again =)
When the problem happens I've managed to realize the problem has to do with an l variable that is undefined, with a comment saying that that variable is sometimes null, however that varible is not null, it's undefined, so the next if (l === null) does nothing, as it should be if (!l) or if (l == undefined || l == null). I forgot the number of the lines, sorry, and I was using the release file with a few deobfuscators.

**Comment by gmsa** [comment]
Can you submit a PR with the fix?

**Comment by gmsa** [comment]
Fixed in 2.1.10
