### ISSUE TITLE
Buttons on grid-items are not working with tap (mobile)

### ISSUE THREAD

**Issue by pbabey** [jbaysolutions/vue-grid-layout#12]
Hi,

I have buttons on my grid-items. When i'm using it on desktop it's working well. When i'm using it with tap on mobile or tablet the Buttons are not working. The drag and drop is working well on mobile and tablet, but the buttons can't be triggered.

Any idea how it can be fixed? 

Many thanks for your great component.

Kind regards

Pascal

**Comment by gmsa** [comment]
Can you supply code or a fiddle to reproduce the problem?

**Comment by pbabey** [comment]
Hi gmsa, 
sorry for the late response. I will setup a fiddle, but I guess after looking into the code, that preventDefault or stoppropagation is added to all child elements, when it's used with touch (tap). Perhaps because of scrolling reason or so.

**Comment by pbabey** [comment]
I've setup a jsfiddle example. https://jsfiddle.net/pbabey/xyfbp8u8/10/ for mobile testing.

**Comment by gmsa** [comment]
I'm not sure which version of vue-grid-layout you're using on the fiddle, but if its 2.x you should be using vue 2. The fiddle is using vue 1.0.28.

**Comment by gmsa** [comment]
Might be an issue with interact.js. Link for future reference when I'm fixing this: https://github.com/taye/interact.js/issues/58

**Comment by pbabey** [comment]
Okay, thanks.

**Comment by pbabey** [comment]
It works. Perfect! Thank you.
