### ISSUE TITLE
Bind col-num to changing variable

### ISSUE THREAD

**Issue by TomFranssen** [jbaysolutions/vue-grid-layout#121]
I would like to dynamically change the width of the layout.
I have added a Vue data string to the col-num setting. If I change this setting the width of the layout doesn't change. Can this setting be made so that it responds to changes?

`v-bind:col-num="layoutWidth"`

**Comment by gmsa** [comment]
Can you submit a PR with that implementation?

**Comment by TomFranssen** [comment]
Thanks for adding this! 👍

**Comment by fenngineering** [comment]
can you gibe me an example of how this might work between 2 components?
