### ISSUE TITLE
How to prevent draggable event in content?

### ISSUE THREAD

**Issue by llwinner** [jbaysolutions/vue-grid-layout#122]
I want to prevent draggable event in the child of grid-item. For example:
```
<grid-item v-for="item in layout"
                    :x="item.x"
                    :y="item.y"
                    :w="item.w"
                    :h="item.h"
                    :i="item.i"
    <div style="height:50%; width:50%; background:black"></div>
</grid-item>
```
I want to prevent draggable event when I drag the div. In my div, there is a map component , it needs drag event alone, but I did not find the way to prevent it . can anyone help me?

**Comment by gmsa** [comment]
Did you check this example? https://jbaysolutions.github.io/vue-grid-layout/examples/04-allow-ignore.html

**Comment by llwinner** [comment]
I'm sorry, I have just read this example, and solved my problem. Thanks for your reply!
