### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by marverix** [jbaysolutions/vue-grid-layout#127]
Hi!
First of all big thanks and respect for this greate piece of work that you have done.

Is there any change to get any simple documentation? Or upgrade README.md so it will describe which param does what?

Or why I need to give item `x`, `y`, `w`, `h` and `i` if `layout` has already all of this? And why `i` must be a string?

Br,
Marek

**Comment by gmsa** [comment]
Thanks for the documentation update.
