### ISSUE TITLE
Dynamic Row Height

### ISSUE THREAD

**Issue by jasonlfunk** [jbaysolutions/vue-grid-layout#13]
Is there a way to have the row height be updated dynamically? I assumed that I just just pass the argument a data attribute, but it doesn't seem to be reactive to the data changing.

**Comment by jasonlfunk** [comment]
Ah, I see. The rowHeight in the GridItem is set once in the mounted() event by manually reading it from the parent. I see that the props were commented out. Is there a reason it was done this way?

**Comment by gmsa** [comment]
It was mostly a quick hack to get it working without having to supply extra props to the GridItems. It should be changed to be updated from the parent with events. I'll do it when I have some free time.
