### ISSUE TITLE
SSR support

### ISSUE THREAD

**Issue by SergeyKhval** [jbaysolutions/vue-grid-layout#132]
Are there any plans to add support for SSR?

**Comment by gmsa** [comment]
Not at the moment. I don't even know how that works

**Comment by Nisthar** [comment]
@gmsa would be nice to have ssr support.

Most of the similar packages doesn't have this feature.

**Comment by gmsa** [comment]
Sure, submit a PR

**Comment by SergeyKhval** [comment]
@Nisthar I made some research on how to implement SSR for grid-layouts and it turns out to be very nontrivial task. One of the biggest difficulties is to produce equal DOMs on server and on client. If you crucially need SSR for your grid look at native [CSS Grid layout](https://developer.mozilla.org/ru/docs/Web/CSS/CSS_Grid_Layout)
