### ISSUE TITLE
  create one Tabs components inside the grid-item， and Tabs  include  vue-grid-layout。 then outside vue-grid-layout  add new grid-item  has error

### ISSUE THREAD

**Issue by wuyinxing** [jbaysolutions/vue-grid-layout#133]
outside  component
![image](https://user-images.githubusercontent.com/17865784/34483924-6f40157e-effc-11e7-8d64-e0053164c2d0.png)
inside tabs   has  grid 
![image](https://user-images.githubusercontent.com/17865784/34483936-8151b11e-effc-11e7-8f9b-3f481be41693.png)
drag  outside  grid-item has error 
![image](https://user-images.githubusercontent.com/17865784/34484031-1d02b676-effd-11e7-87af-c4953653448e.png)
![image](https://user-images.githubusercontent.com/17865784/34483881-2c560ac0-effc-11e7-8486-37dfd3d641c9.png)

**Comment by gmsa** [comment]
try with vue-grid-layout latest version (2.1.11)

**Comment by wuyinxing** [comment]
thanks   ,the problem was solved  in latest version (2.1.11)  ！
