### ISSUE TITLE
how to own multiple grids in one vue application?

### ISSUE THREAD

**Issue by sunzongzheng** [jbaysolutions/vue-grid-layout#134]
[Please click here](https://jsfiddle.net/sunzongzheng/7huu5gw4/23/)

And then click the button `Add an item to the first grid` and `Add an item to the second grid` on the top. 

When drag the item of the first grid, the item of the second grid will move. 

How to resolve it? My application need two grid now, also I need to resize and move items.

![image](https://user-images.githubusercontent.com/12635613/34513525-9c0cc046-f0a3-11e7-8086-3fb78f96595c.png)

**Comment by gmsa** [comment]
With which version of vue and vue-grid-layout?

Have you checked this example? https://jbaysolutions.github.io/vue-grid-layout/examples/03-multiple-grids.html

**Comment by sunzongzheng** [comment]
thanks for your reply.
I used the lastest version. 
The vue-grid-layout's version of my jsfiddle's demo is from the repo's file. 
I have checked that example. That example was running on two vue application, But I need to run on only one vue application. 
Please look through that jsfiddle demo, thanks

**Comment by sunzongzheng** [comment]
[jsfiddle's demo](https://jsfiddle.net/sunzongzheng/7huu5gw4/10/)

**Comment by sunzongzheng** [comment]
It was caused by vue's provide and inject. [https://jsfiddle.net/sunzongzheng/6xe4mtc2/9/](https://jsfiddle.net/sunzongzheng/6xe4mtc2/9/)
I have posted an issue to vue's repo.
