### ISSUE TITLE
Min Width/Height not working and no examples

### ISSUE THREAD

**Issue by soccer99** [jbaysolutions/vue-grid-layout#14]
I would like to set min width on items but I have tried supplying minW (as searched and found in the js file) but cannot get it to work.

{"x":0,"y":0,"w":2,"h":2,"i":"0","minW":2} on an item seems to have no affect on resizing.

**Comment by soccer99** [comment]
Nevermind, finally after some digging found that it has to be written as min-w in the javascript or html templates.

**Comment by AndreaRylander** [comment]
I am trying to use min-w and min-h but it doesnt work
`{"x": 6.5, "y": 122, "w": 4, "h": 9, "min-w": 3.5, "min-h": 6.5},`

what am I doing wrong?

**Comment by gmsa** [comment]
Check #101 for an example
