### ISSUE TITLE
Enforce minW / minH

### ISSUE THREAD

**Issue by elmat0** [jbaysolutions/vue-grid-layout#148]
Is it possible to set hard size limits on a grid item to prevent them from resizing past the bounds set via minH / minW (or max) properties?

Eg to prevent [this.](https://gfycat.com/AllImaginaryDiplodocus) If not, can anyone recommend any workarounds to mitigate?

Unsure if related to https://github.com/jbaysolutions/vue-grid-layout/issues/114?

**Comment by gmsa** [comment]
This should be fixed in 2.2.0
