### ISSUE TITLE
Need help with installation 

### ISSUE THREAD

**Issue by Akshin** [jbaysolutions/vue-grid-layout#155]
Hi. Cant install. Dont understand why. (permission denied). With root user same problem.

Trying to npm install. 

![2018-02-06 22-29-38](https://user-images.githubusercontent.com/19845978/35879860-5ab7be16-0b8d-11e8-8422-91c3af17bcc1.png)

**Comment by gmsa** [comment]
Thats a problem with permissions on your machine
