### ISSUE TITLE
I can't install

### ISSUE THREAD

**Issue by adbarnett** [jbaysolutions/vue-grid-layout#156]
Can't install. 

![image](https://user-images.githubusercontent.com/11020287/36040428-53b2d47a-0dbd-11e8-90d1-de8c4626f296.png)

**Comment by adbarnett** [comment]
I have had this working before. Recently un-installed and re-installed node and all packages (don't ask) but for some reason this is the only package I cannot re-install

**Comment by gmsa** [comment]
If you look at the error message, it says you need to add git to $PATH
