### ISSUE TITLE
GridItem Drag Handle

### ISSUE THREAD

**Issue by soccer99** [jbaysolutions/vue-grid-layout#16]
In the React grid layout there is the option to create a drag handle in the item, such as a span within the griditem element.  Is there such a feature here?

**Comment by ThePlastic** [comment]
from what I could see this grid uses interact.js for both drag and resize, the functionality you refer is available using .allowFrom method ('. handle-class'), but unfortunately the possibility of having separate handle for each interaction is broken in interact.js current version, they should have fixed it in version 1.3.0 but is not yet available on npm (latest available version 1.2.8)

**Comment by gmsa** [comment]
There is no such feature here yet

**Comment by ThePlastic** [comment]
I will submit a PR as soon as the Interactjs release (1.3.0) that allows to have different handle for each interaction will be published on npm

**Comment by ThePlastic** [comment]
I did it ;)
https://github.com/jbaysolutions/vue-grid-layout/pull/53

**Comment by gmsa** [comment]
Supported in 2.1.7
