### ISSUE TITLE
Error after upgrading: [Vue warn]: Missing required prop: "layout"

### ISSUE THREAD

**Issue by TomFranssen** [jbaysolutions/vue-grid-layout#169]
I just upgraded from 2.1.11 to 2.1.12, now I got the following error:

![image](https://user-images.githubusercontent.com/1880964/38015050-e963c3ea-326a-11e8-8219-7f83396ff9c0.png)

This was working correct before I upgraded.
I am using Vue v2.5.16.

Anyone has any idea?

The layout array is in my Vue model:

    [
      {
        "product_id": 10,
        "type": "product",
        "rank": 0,
        "label": null,
        "y": 1,
        "x": 1,
        "i": "66745",
        "w": 1,
        "h": 1,
        "name": "Gestikte dweil",
        "sku": "000000000000000004_8710201866382_DS",
        "price": "€ 146,40",
        "qty": 0,
        "qty_increments": 1,
        "small_image_url": "/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/4/8710201969441/ST/8710201969441_4_400_0001.png",
        "empty": false,
        "dragable": true,
        "resizable": true
      }
    ]

And this is my HTML grid layout element:

    <grid-layout
        class="sections"
        v-bind:layout="sections"
        v-bind:col-num="colNumSet"
        v-bind:style="{'min-width': '<?php echo $this->getLayoutWidth('edit') * 180 ?>px'}"
        v-bind:row-height="320"
        v-bind:is-draggable="properties.use_default_sections === 0"
        v-bind:is-resizable="properties.use_default_sections === 0"
        v-bind:is-mirrored="renderMirrored"
        v-bind:vertical-compact="false"
        v-bind:margin="[10, 10]"
        v-bind:use-css-transforms="true"
        @layout-updated="layoutUpdatedEvent"
    >
        <grid-item
            class="section"
            v-for="(item, index) in sections"
            v-bind:key="item.id"
            v-bind:x="item.x"
            v-bind:y="item.y"
            v-bind:w="item.w"
            v-bind:h="item.h"
            v-bind:i="item.i"
            v-bind:title="item.sku"
            v-bind:class="item.type"
        >

**Comment by lrembacz** [comment]
Be sure that your `sections` data is an array and it is ready before component is reneder. 
If not just use `v-for="sections" `on grid-layout component.
