### ISSUE TITLE
npm run dist error

### ISSUE THREAD

**Issue by gitranxu** [jbaysolutions/vue-grid-layout#171]
I want to let the GridItem trigger a event in the amounted, so I modified the GridItem.vue,and run npm install, when I run npm run dist,i see the error info bellow:
ERROR in ./src/utils.js
Module parse failed: Unexpected token (2:7)
You may need an appropriate loader to handle this file type.
| // @flow
| export type LayoutItemRequired = {w: number, h: number, x: number, y: number, i: string};
| export type LayoutItem = LayoutItemRequired &
|                          {minW?: number, minH?: number, maxW?: number, maxH?: number,
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/GridItem.vue 5:13-31
 @ ./src/GridItem.vue
 @ ./src/index.js

ERROR in ./src/responsiveUtils.js
Module parse failed: Unexpected token (5:12)
You may need an appropriate loader to handle this file type.
| import {cloneLayout, compact, correctBounds} from './utils';
|
| import type {Layout} from './utils';
| export type ResponsiveLayout = {lg?: Layout, md?: Layout, sm?: Layout, xs?: Layout, xxs?: Layout};
| type Breakpoint = string;
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/ResponsiveGridLayout.vue 7:23-51
 @ ./src/ResponsiveGridLayout.vue
 @ ./src/index.js

I try to modify the bug, and I run npm install --save-dev flow-bin,but still can work.

**Comment by gmsa** [comment]
work fine here
