### ISSUE TITLE
layoutUpdatedEvent on page load / init

### ISSUE THREAD

**Issue by markuskoehler** [jbaysolutions/vue-grid-layout#182]
Hey,

I would need to trigger the layoutUpdatedEvent on page load or when the grid is initialized, so that I know the initial position of all elements, before anything is moved, is that possible?

Thanks!

**Comment by mech01nc01** [comment]
you are talking about the positions of the griditems within the document in px?

else please sepcify what you are thinking about

**Comment by markuskoehler** [comment]
yes thats what I wanted to say, thx. Any suggestions?

**Comment by portikM** [comment]
hey @markuskoehler!
did you find the solution?
