### ISSUE TITLE
When item isDraggable = false, it can still be moved

### ISSUE THREAD

**Issue by dasjestyr** [jbaysolutions/vue-grid-layout#185]
When an item is marked as `isDraggable=false` it cannot be dragged, but it can still be moved by dragging another item to its spot. There needs to be a way to lock items to their space on the grid.

**Comment by nkostadinov** [comment]
this has nothing to do with the draggable property but totally different functionality. May if we have some sort of callback in which we can decide whether the drag can start and/or element can be moved we can work this out

**Comment by dasjestyr** [comment]
Perhaps adding :static or something to that effect that would signify that the item has to stay where it is and nothing else can be moved into it's place. Would have to take care that if the item is spanning multiple cells, those cells must be off limits as well like anything else.

**Comment by gmsa** [comment]
Yes, static is another feature alltogether, that is not implemented. Care to submit a PR?
