### ISSUE TITLE
Elements don't replace each other in place when dragged

### ISSUE THREAD

**Issue by igor-sobolev** [jbaysolutions/vue-grid-layout#189]
When I try to use this library like in tutorial it doesn't work as in it.
`<GridLayout :layout="cards" :col-num="4" :is-draggable="true" :is-resizable="false" :row-height="280" :margin="[12.5, 12.5]"
        :use-css-transforms="true" :vertical-compact="true" ref="grid">
        <GridItem v-for="card in cards" :key="card.id" :x="card.x" :y="card.y" :w="card.w" :h="card.h" :i="card.id">
          <Card :data="card" :size="card.size"></Card>
        </GridItem>
      </GridLayout>`
It just shows placeholder but doesn't move other cards. When I add move event handler it works but a bit weird. It can't replace some of cards and a big card of 3/4 of width can't take away 3 other little 1/4 width cards.
`handleMove(id, newX, newY) {
      sample.forEach(function (v) {
        if (v.id === id) {
          v.x = newX;
          v.y = newY;
          console.log(v.x + ':' + v.y)
        }
      })
    }`
I am using **vue-grid-layout 2.1.13** and **vue 2.5.2**

**Comment by gmsa** [comment]
Sorry, please submit a way to reproduce the problem, like a jsfiddle
