### ISSUE TITLE
How do you change the main layout of App.vue from child components?

### ISSUE THREAD

**Issue by manjrekarom** [jbaysolutions/vue-grid-layout#192]
Hey,
I want to create a wrapper component called 'VueBoard' that contains 'GridLayout' and 'AddElement'.  
This VueBoard is placed inside App.vue and takes a layout array from the App as a prop which is used inside GridLayout.

I want this AddElement component to be also able to add a new layout item in the array and other information. 

How can I do this?

I am unable to understand how you can change App.vue's layout (data) from inside the child components like GridLayout or GridItem.

**Comment by mech01nc01** [comment]
hello,

this is not an issue related to vue-grid-layout

if you want to alter data in a parent component, then you have to emit an Event from the child that will be fetched in the parent and the parent will alter the data.

see [docs](https://vuejs.org/v2/guide/components.html#Sending-Messages-to-Parents-with-Events)
