### ISSUE TITLE
Having issue with window.onload

### ISSUE THREAD

**Issue by oeway** [jbaysolutions/vue-grid-layout#193]
Hi,
I am having problem with my window.onload function because it was overwritten by vue-grid-layout.
Currently, I can find two places with window.onload function in this repo: [here](https://github.com/jbaysolutions/vue-grid-layout/blob/33c5205b3a921e9ce1b59a616b039b3c928860c8/src/GridLayout.vue#L146) and [here](https://github.com/jbaysolutions/vue-grid-layout/blob/40da0e94918ec30861a3e37cf34941e520763067/src/ResponsiveGridLayout.vue#L109).
I think they can be improved to be less invasive version:
```
var origOnload = window.onload || function(){};
window.onload = function(){
     origOnload();
     // other code goes here
}
```
or use even listener:
window.addEventListener("load", handlerFunc, false)

Otherwise it may conflicting with other places where window.onload are used.

**Comment by gmsa** [comment]
Care to submit a PR with that improvement?
