### ISSUE TITLE
Has layout to be entered twice?

### ISSUE THREAD

**Issue by devleaks** [jbaysolutions/vue-grid-layout#204]
Hello,

I don't understand a little thing about the use of this layout engine.
All exemples in the code define a layout in a json object and then a loop generates almost empty grid-items. Grid items get their x,y,w,h and index from the loop. OK, got it.

I'd like to use the grid for UI, let's say a dashboard-like UI.
So what I basically have is a handcrafted vue component like this:
```
<template>
  <dashboard>
   <widget id=1 width=1 height=1></widget>
   <widget id=2 width=2 height=1></widget>
   ...
  </dashboard>
</template>
```

Now, how do I reder such a layout with grid-layout? Where do I need to place the "layout" parameters?
```
<template>
  <grid-layout layout="HAS TO BE HERE IN JSON?" col-num=12>
   <grid-item id=1 OR-HERE? x=0, y=0, w=1, h=1  ></grid-item>
   <grid-item id=2 width=2 height=1></grid-item>
  </grid-layout>
</template>
```

More questions:
 - Since user can later move and resize grid-items, why is there a need for an initial layout?
 - Is there a way to add / remove grid-items dynamically from grid-layout? Through direct DOM manipulation?

Many thanks for your help.

P.

**Comment by gmsa** [comment]
1. You need the use your layout json object both on the <grid-layout> element and on the <grid-item> objects inside it, using v-for. Your layout parameters need to be on the json object.
2. If there is no initial layout, what will the user move and resize?
3. Yes, just add or remove items from the layout json object. Vue's reactivity will take care of rendering the grid.

**Comment by devleaks** [comment]
There is no need for an initial layout (look at what masonry and other packages do). The wrapping element just need to accommodate its children, provided they have a size.
As I explained, I cannot "generate" child elements in a v-for loop. They are statically defined in a template. I found an alternate solution. Thank you.
