### ISSUE TITLE
Draggable area issues

### ISSUE THREAD

**Issue by msporyshev** [jbaysolutions/vue-grid-layout#209]
Is there any way to work with draggable elements inside grid-item if it is also draggable? For example, my grid item is a draggable form (inside grid-item) and I have a slider inside which I basically can't drag because of gridItem.

Is there any way to deal with it?

**Comment by gmsa** [comment]
You can use the GridItem dragIgnoreFrom prop to specify elements or classes where dragging should be ignored. You can also use dragAllowFrom to specify that your GridItem only is allowed to be dragged on specific elements. Check the main README for details
