### ISSUE TITLE
New events: 'moved' & 'resized' request

### ISSUE THREAD

**Issue by Cannonb4ll** [jbaysolutions/vue-grid-layout#21]
I noticed there are 2 events in this package, problem is they get triggered all the time.

Is there a way to detect when 'resizing' or 'moving' is done? I am doing an AJAX call on resize but its getting a bit of lot of calls this way.

**Comment by ThePlastic** [comment]
you should implement a debounce function, in my project i use something like: 
`function debounce(func, wait, immediate) {
    var timeout;
    return function() {
        var context = this, args = arguments;
            var later = function() {
            timeout = null;
            if (!immediate) func.apply(context, args);
    };
    var callNow = immediate && !timeout;
    clearTimeout(timeout);
    timeout = setTimeout(later, wait);
    if (callNow) func.apply(context, args);
    };
};`

And you can use inside your App.vue like:
`...
resize : debounce(function(item) {
	// here your Ajax call will be executed
        // only after 0.25s
}, 250);
...`
Optionally you can pass a third parameter ("immediate") as a Boolean to fire the event immediatly

**Comment by gmsa** [comment]
We're planning to implement two new events, 'moved' and 'resized', that will fire only when an item is finished moving or resizing. Those should be more useful than the current ones.

**Comment by Cannonb4ll** [comment]
Thanks! :)

@ThePlastic I had also thought of a solution like yours, and it works fine, but feels hacky and not good in any way. (I currently have setup it like this, but I will await the new update  :) )
