### ISSUE TITLE
Add an interface about the window.resize event

### ISSUE THREAD

**Issue by fuchunhui** [jbaysolutions/vue-grid-layout#216]
if you resize the window, the grid-layout already added a listener on it, it's ok.
but, when the display style of the another container(another grid-layout) is none, you resize the window, it's out of work, then the grid-layout will stay in left side(maybe it's in default status).
so if you can provide the interface, we can resolve it easily.
now. we just can use it like this.
this.$refs.gird-layout.onWindowResize()
you know, it's not always safe.

**Comment by gmsa** [comment]
Sorry, can't understand your problem

**Comment by fuchunhui** [comment]
ok, maybe a demo?
just, we need a way to resize the layout even though the window resize event is not triggered.

**Comment by gmsa** [comment]
Please submit a demo
