### ISSUE TITLE
Help for autoresize item.

### ISSUE THREAD

**Issue by thomashdk** [jbaysolutions/vue-grid-layout#221]
Should I call `this.$parent.autoSize();` from **//TWO** or in **//THREE.**
Can't get det resize to work. 
When en collapse min widget I want the grid to resize to fit the new size of the widget.

```
//ONE
<grid-layout
                :layout="gridLayout"
                :col-num="2"
                :row-height="30"
                :is-draggable="true"
                :is-resizable="false"
                :vertical-compact="true"
                :margin="[40, 12]"
                :use-css-transforms="true"
                :autoSize="true"
                @layout-updated="layoutUpdatedEvent"
            >
//TWO
                <grid-item 
                           :x="this.gridLayout[0].x" 
                           :y="this.gridLayout[0].y" 
                           :w="this.gridLayout[0].w" 
                           :h="this.gridLayout[0].h" 
                           :i="this.gridLayout[0].i" 
                           drag-allow-from=".vue-draggable-handle" 
                           drag-ignore-from=".no-drag">
                    // THREE*      
                    <widget-find-rights :data="json.data[0]" @resizeWidget="resizeElement = $event"></widget-find-rights>

                </grid-item>
```

**Comment by gmsa** [comment]
Check https://github.com/jbaysolutions/vue-grid-layout/blob/autoSize/src/App.vue#L59 and https://github.com/jbaysolutions/vue-grid-layout/blob/autoSize/src/TestElement.vue

**Comment by thomashdk** [comment]
> Check https://github.com/jbaysolutions/vue-grid-layout/blob/autoSize/src/App.vue#L59 and https://github.com/jbaysolutions/vue-grid-layout/blob/autoSize/src/TestElement.vue

Hey, thanks  :)
Can't see the  `this.$parent.autoSize();` been called anywhere?

**Comment by gmsa** [comment]
https://github.com/jbaysolutions/vue-grid-layout/blob/autoSize/src/TestElement.vue#L23

**Comment by thomashdk** [comment]
... wauw..

but strange. I just installed version 2.2.0, and there was only the console.log() line..

**Comment by gmsa** [comment]
Like I said before on the PR, this is on the autoSize branch...

**Comment by thomashdk** [comment]
arh sorry. Thought in was merge into master.
