### ISSUE TITLE
Grid doesn't work properly if grid item datastructure doesn't have an "i" element

### ISSUE THREAD

**Issue by GlennMatthys** [jbaysolutions/vue-grid-layout#226]
When using a different key as identifier for the grid-item datastructure, even though it's correctly assigned in <grid-item>, the grid doesn't work correctly anymore, for example:

```
layout: [{
        "x": 0,
        "y": 0,
        "w": 4,
        "h": 2,
        **"id": "0"** // instead of "i"
      }
```
```
<grid-item class="grid-cell" v-for="item in layout"
                   :x="item.x"
                   :y="item.y"
                   :w="item.w"
                   :h="item.h"
                   **:i="item.id"**>
```

[JSFiddle](https://jsfiddle.net/GlennMatthysECrane/f7avt465/3/).

When making changes to the grid, it reverts back to the original configuration. It appears having "i" in the item's datastructure is a hard requirement, even though you can define it manually where i is supposed to originate from.

**Comment by gmsa** [comment]
Yes, the "i" field is required, there's currently no way around it.
