### ISSUE TITLE
Questions: fixed (pinned) grid-item, collision event

### ISSUE THREAD

**Issue by gracefullight** [jbaysolutions/vue-grid-layout#229]
1: Is there a way to fix the x, y, w, h values ​​of grid-item?
I do not want to change the position of another grid-item by dragging it.

2: If a collision occurs during dragging, can I receive an event?
I want to invalidate the drag event when it crashes.

3. When adding a grid item, is there a way to check the layout range (cols, rows) is overflowed?

**Comment by gracefullight** [comment]
1: You can set the "static" option to "true" 
``` js
{ x: 1, y: 1, w: 2, h: 2, i: '2x2', static: true}
```

**Comment by gmsa** [comment]
2. No events are fired on collisions

3. No

**Comment by gracefullight** [comment]
Thanks @gmsa 
Could I ask if can support both cases?

**Comment by gmsa** [comment]
Not planning to implement either case, feel free to submit a PR
