### ISSUE TITLE
Library crash on startup in AMD project

### ISSUE THREAD

**Issue by micene09** [jbaysolutions/vue-grid-layout#236]
Hi, 
I have an AMD project (requirejs) with Vue.js 2.5...once that the umd file is loaded i see the foolowing error message:

```
vue-grid-layout.js?v=1.0.0.0:6756 Uncaught TypeError: Cannot read property 'component' of undefined
    at vue-grid-layout.js?v=1.0.0.0:6756
    at Array.forEach (<anonymous>)
    at Module.fb15 (vue-grid-layout.js?v=1.0.0.0:6755)
    at __webpack_require__ (vue-grid-layout.js?v=1.0.0.0:30)
    at vue-grid-layout.js?v=1.0.0.0:94
    at vue-grid-layout.js?v=1.0.0.0:97
    at Object.execCb (require.js:1696)
    at Module.check (require.js:883)
    at Module.enable (require.js:1176)
    at Module.init (require.js:788)
```

...seems that there is something wrong on load, requiring webpack anyway.

**Comment by gmsa** [comment]
Sorry, please provide a sample with that error.

**Comment by Micene09** [comment]
Simple and fast to reproduce, just install it via npm (or whatever) and write a sample HTML like this:
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <script src="vue-grid-layout.umd.min.js"></script>
</head>
<body></body>
</html>
```

You will see the error on dev tools.

**Comment by gmsa** [comment]
You need to include vue.js first.

**Comment by Micene09** [comment]
Really sorry for the bad example provided...but thank to your comment i got the idea that leaded me to the AMD (requirejs) problem's cause.

The `webpackUniversalModuleDefinition` function is missing the `vue` dependency inside the define.amd condition.

The (wrong) builded code:
```javascript
(function webpackUniversalModuleDefinition(root, factory) {
	if(typeof exports === 'object' && typeof module === 'object')
		module.exports = factory(require("vue"));
	else if(typeof define === 'function' && define.amd)
		define([], factory); // << HERE is the error...
	else if(typeof exports === 'object')
		exports["VueGridLayout"] = factory(require("vue"));
	else
		root["VueGridLayout"] = factory(root["Vue"]);
})
```

...and this is how it should be:
```javascript
//...
	else if(typeof define === 'function' && define.amd)
		define(["vue"], factory);
//...
```

I'm checking how to fix this, do you have any idea?

**Comment by gmsa** [comment]
Don't know what you're doing in your project, but that change broke the umd load. I'm reverting it.
In lib mode Vue is externalized anyway: https://cli.vuejs.org/guide/build-targets.html#library

**Comment by Micene09** [comment]
Reverting it you are fixing the global umd load (script tag) and breaking again the AMD load...but still, the issue is there.
At the module definition, the `define.amd` section is the only one with no dependency:
- `module.exports = factory(require("vue"));`  << require("vue") dependency ok
- `exports["VueGridLayout"] = factory(require("vue"));`<< dependency ok again
- `root["VueGridLayout"] = factory(root["Vue"]);` << dependency ok again...

...the only module definition, that is missing the (most important) depedency is `define.amd`.

Just to know it...but how is it breaking the umd load?

**Comment by Micene09** [comment]
I think i got it, setting the external dependency in that way (externals object), leaded to one of the deepest errors: _the module name is not the same, it will change with the module system_.

In your case, the module name for the root (global variable) is not `vue`, but `Vue`.
For this reason, setting the externals object in that way is wrong.

But, i found the real solution to this (and future problems like this), just following the [doc ->externals->object](https://webpack.js.org/configuration/externals/#object).
As you can read, we can set a module name for each module system, so the right way to do this should be:
```javascript
externals : {
    vue : {
      commonjs: 'vue', // the default commonjs module name
      amd: 'vue',  // required to make it work for AMD
      root: 'Vue' // the default global variable
    }
}
// maybe you can try to NOT override the commonjs and root values
// ...just because that are the default values:
externals : {
    vue : {
      amd: 'vue'
    }
}
```

Please, before revert and release, try this solution.

**Comment by reidcjk** [comment]
> I think i got it, setting the external dependency in that way (externals object), leaded to one of the deepest errors: _the module name is not the same, it will change with the module system_.
> 
> In your case, the module name for the root (global variable) is not `vue`, but `Vue`.
> For this reason, setting the externals object in that way is wrong.
> 
> But, i found the real solution to this (and future problems like this), just following the [doc ->externals->object](https://webpack.js.org/configuration/externals/#object).
> As you can read, we can set a module name for each module system, so the right way to do this should be:
> 
> ```js
> externals : {
>     vue : {
>       commonjs: 'vue', // the default commonjs module name
>       amd: 'vue',  // required to make it work for AMD
>       root: 'Vue' // the default global variable
>     }
> }
> // maybe you can try to NOT override the commonjs and root values
> // ...just because that are the default values:
> externals : {
>     vue : {
>       amd: 'vue'
>     }
> }
> ```
> 
> Please, before revert and release, try this solution.

Awesome!
Quite helpful!
