### ISSUE TITLE
Event bus not found

### ISSUE THREAD

**Issue by Matthijskl** [jbaysolutions/vue-grid-layout#247]
I'm using this application; https://github.com/SimulatedGREG/electron-vue.

When using this grid layout in a Vue Electron application, there comes an error about 'Injection "eventBus" not found'.

Can someone help me to fix this, or explain to me why this is happening.

` import { GridLayout, GridItem } from 'vue-grid-layout'

  export default {
    name: 'landing-page',
    components: { GridLayout, GridItem },
    data () {
      return {
        layout: [{
          'x': 0,
          'y': 0,
          'w': 4,
          'h': 2,
          'i': '0'
        }]
      }
    }
  }`

` <grid-layout
              :layout.sync="layout"
              :col-num="12"
              :row-height="30"
              :is-draggable="true"
              :is-resizable="true"
              :is-mirrored="false"
              :vertical-compact="true"
              :margin="[10, 10]"
              :use-css-transforms="true"
      >
        <grid-item style="background: black;" v-for="item in layout"
                   :x="item.x"
                   :y="item.y"
                   :w="item.w"
                   :h="item.h"
                   :i="item.i">
          {{item.i}}
        </grid-item>
      </grid-layout>`

**Comment by kazax-inc** [comment]
I have the same error with electron

> Injection "eventBus" not found

```vue
<template>
  <v-flex fill-height>
      <grid-layout
        :layout.sync="assetGrid"
        :col-num="5"
        :maxRows="4"
        :rowHeight="60"
        :is-draggable="true"
        :is-resizable="false"
        :is-mirrored="false"
        :vertical-compact="false"
        :margin="[0, 0]"
        :use-css-transforms="true"
      >

        <grid-item  v-for="item in assetGrid" :x="item.x" :y="item.y" :w="item.w" :h="item.h" :i="item.i">
          <AssetCard v-bind="asset[item.i]"></AssetCard>
        </grid-item>

      </grid-layout>
  </v-flex>
</template>

<script>
  import VueGridLayout from 'vue-grid-layout'
  import AssetCard from './card'
  export default {
    name: 'Watchlist',
    components: {
      GridLayout: VueGridLayout.GridLayout,
      GridItem: VueGridLayout.GridItem,
      AssetCard
    },
    props: [],
    data: () => {
      return {
        assetGrid: [
          {'x': 0, 'y': 0, 'w': 1, 'h': 1, 'i': '0'},
          {'x': 1, 'y': 0, 'w': 1, 'h': 1, 'i': '1'},
          {'x': 2, 'y': 0, 'w': 1, 'h': 1, 'i': '2'},
          {'x': 0, 'y': 1, 'w': 1, 'h': 1, 'i': '3'},
          {'x': 1, 'y': 1, 'w': 1, 'h': 1, 'i': '4'},
          {'x': 2, 'y': 1, 'w': 1, 'h': 1, 'i': '5'}
        ],
        asset: [10, 20, 30, 40, 50, 60]

      }
    },
    computed: {},
    methods: {},
    watch: {},
    mounted () {}
  }
</script>

<style scoped>
      
</style>

```

**Comment by kazax-inc** [comment]
Problem solved using the latest version of electron, vue and vuetify, the boilerplate is out of date, to have electron (latest) + vue (latest) + vuetify (latest) follow the instructions using vue CLI 3 instead of the boilerplate, to do this [(Electron + vue + vuetify)](https://github.com/vuetifyjs/vue-cli-plugin-vuetify)

**Comment by fgmehlin** [comment]
I am having this issue as well (using bare Vue, w/o Electron or vuetify). 

I'm using vue v2.6.10, vue-grid-layout v.2.3.4

```
 <grid-layout
               :layout.sync="layout",
               :col-num="2",
               :row-height="450",
               :is-draggable="true",
               :is-mirrored="false",
               :vertical-compact="true",
               :margin="[10, 10]",
               :use-css-transforms="true"
          >
            <grid-item v-for="comp in layout" :x="comp.x" :y="comp.y" :w="comp.w" :h="comp.h" :i="comp.i">
```

local data:

``` 
data: () => {
    return {
      layout: [
      {
        type: "WidgetComponent",
        title: "test1",
        x: 0,
        y: 0,
        h: 1,
        w: 2,
        i: "0",
      },
      {
        type: "WidgetComponent",
        title: "test2",
        x: 0,
        y: 2,
        h: 2,
        w: 1,
        i: "1",
      },
   ...
 ]
```

Error: 

```
Vue warn]: Injection "eventBus" not found

found in

---> <GridItem>

[Vue warn]: Error in created hook: "TypeError: Cannot read property '$on' of undefined"

found in

---> <GridItem>
```

Any idea how to fix this ?

**Comment by FFGF** [comment]
i meet the same problem when i use electron-vue , I finish the problem
```
npm install vue-grid-layout@2.1.13
```
i doubt your electron-vue was builded by cli2, but the newest vue-grid-layout is builded by cli3. they are not match. so you better install vue-grid-layout that was builded by cli2.
