### ISSUE TITLE
error js, Cannot read property 'component' of undefined

### ISSUE THREAD

**Issue by onchomngebul** [jbaysolutions/vue-grid-layout#268]
Uncaught TypeError: Cannot read property 'component' of undefined
    at index.js:16
    at Array.forEach (<anonymous>)
    at Module.fb15 (index.js:15)
    at n (bootstrap:19)
    at 00c2 (bootstrap:83)
    at bootstrap:83
    at universalModuleDefinition:9
    at universalModuleDefinition:1

**Comment by gmsa** [comment]
fixed on 2.3.3
