### ISSUE TITLE
Feature needed float layout like jquery gridstack.js

### ISSUE THREAD

**Issue by chen-ABC** [jbaysolutions/vue-grid-layout#281]
hi,
I have a requirement that I don't want elements to float up.
just as float layout of jquery gridstack.js
Do you have a plan?
thank you

**Comment by MLongz** [comment]
This Would be nice to have in the responsive part where the gridItems fill out the empty spaces..

**Comment by abulka** [comment]
@chen-ABC Why did you close this - has this feature been added? I need `float` too!

**Comment by chen-ABC** [comment]
@abulka https://jbaysolutions.github.io/vue-grid-layout/guide/properties.html#verticalcompact  You can try this

**Comment by abulka** [comment]
Thanks - works great!
