### ISSUE TITLE
How can i remove padding near border?

### ISSUE THREAD

**Issue by Artawower** [jbaysolutions/vue-grid-layout#288]
I want remove padding near border. If i user :margin="[6, 6]" that create little bit padding inside grid layout. What i can doing if i want use margin only between GridItem? (if i user :margin="[0, 0]" the indent is lost). For example:
![2019-01-22_19-08-05](https://user-images.githubusercontent.com/16963833/51548486-725bb680-1e79-11e9-8a50-6bb703adb851.png)
Is it possible to do this?

**Comment by atilkan** [comment]
you should add negative margin to container.

**Comment by kkroid** [comment]
If can have an official way, it will be better.

**Comment by gmsa** [comment]
There is no official way
