### ISSUE TITLE
When will the overlapping and rezise bug-fix be pushed to production?

### ISSUE THREAD

**Issue by MLongz** [jbaysolutions/vue-grid-layout#297]
When will the overlapping and rezise bug-fix be pushed to production? Would be nice to get this out soon. We are a big company that would like to test this in our next project, and we need the responsive feature. 😃

**Comment by atilkan** [comment]
Provide cols prop if you are setting colNum. It is not documented.

**Comment by MLongz** [comment]
> Provide cols prop if you are setting colNum. It is not documented.

I already did. Its still overlapping when resizing the grid-layout. Also the resize-bug for grid-item is still there.

**Comment by scarry1992** [comment]
@MLongz, Last version was not builded after last merge. https://github.com/jbaysolutions/vue-grid-layout/pull/299

**Comment by gmsa** [comment]
@MLongz if you are a big company, maybe you can sponsor the project so we can work on it faster 😉

**Comment by alc32** [comment]
When will the next version be released? @gmsa

**Comment by gmsa** [comment]
Probably tomorrow, waiting for changes in #301

**Comment by gmsa** [comment]
new version released
