### ISSUE TITLE
Responsive layout wrong griditem is being pushed down

### ISSUE THREAD

**Issue by MLongz** [jbaysolutions/vue-grid-layout#298]
When using the responsive layout the wrong griditem will be pushed down. Instead of the last item on the row, the item before the last item is being pushed instead.
![bug1](https://user-images.githubusercontent.com/14195692/52947340-b194fe80-3376-11e9-8640-1108c1c99804.PNG)
![bug2](https://user-images.githubusercontent.com/14195692/52947345-b48fef00-3376-11e9-819f-44ba8bacc0f0.PNG)

The fix would be to not sort the layout array when compact the array

**Comment by picululu** [comment]
I have the same problem

**Comment by tripflex** [comment]
There is also issue of difference in Firefox and Chrome, where they are not in the same order.  Firefox shows 0 at top, Chrome shows 5 at the top

https://jbaysolutions.github.io/vue-grid-layout/examples/06-responsive.html

Reported here:
https://github.com/jbaysolutions/vue-grid-layout/pull/228#issuecomment-442403390

**Comment by almeida245** [comment]
I have the same problem too

**Comment by kuldeep-argusoft** [comment]
Facing same issue. Fix would be really appreciated.
