### ISSUE TITLE
Vue grid layout does not work with latest stable Vue version

### ISSUE THREAD

**Issue by werdlv** [jbaysolutions/vue-grid-layout#3]
Grid layout works with Vue 1.0.24 (as in given example) but it does not work with latest Vue version 2.0.3

Console errors: `vue.js:2611 [Vue warn]: Invalid prop: type check failed for prop "layout". Expected , got Array. 
(found in component <GridLayout>)`

**Comment by gmsa** [comment]
Hi, Vue 2 is not supported yet
