### ISSUE TITLE
Horizontal version

### ISSUE THREAD

**Issue by gitsilvan** [jbaysolutions/vue-grid-layout#30]
I think a version that extends horizontally, instead of vertically, would be a useful feature. Are there any plans yet?

**Comment by gmsa** [comment]
Hi, sorry we have no plans for that. Do you any examples of how that would be useful?

**Comment by gitsilvan** [comment]
No worries! It would just be another layout option. If you have a dashboard or image gallery grid or whatever that is horizontally aligned. You can see it in action here: http://hootsuite.github.io/grid/
