### ISSUE TITLE
Resizing and overlaping issue if Responsive pop is true

### ISSUE THREAD

**Issue by Xstyler85** [jbaysolutions/vue-grid-layout#305]
If I download this project everything is working fine. I got problems when I created a new Vue project and install this package. If I use :responsive="true" resizing become buggy and sometimes element can overlap another element. I would really love to use this packed.

**Comment by Cirrusware** [comment]
Same issue.

Have you a demo in responsive mode ?

Thanks

**Comment by gmsa** [comment]
https://jbaysolutions.github.io/vue-grid-layout/examples/06-responsive.html

**Comment by gmsa** [comment]
Not enough information to reproduce the problem, closing issue.

**Comment by Cirrusware** [comment]
You have wright.

This code has fixed my issue.

    <grid-layout
      :layout.sync="widgets"
      ...
    >

Thanks for this library :-)
