### ISSUE TITLE
Grid Items overlapping

### ISSUE THREAD

**Issue by SanjayBanjade** [jbaysolutions/vue-grid-layout#306]
The content inside the grid item overlaps when the content is updated dynamically.

Here is the sandbox URL:
https://codesandbox.io/s/j29vq3qy1y

When I type in something in the input, the text gets overlapped with the input.

**Comment by gmsa** [comment]
That's something you have to handle, not the grid

**Comment by SanjayBanjade** [comment]
I don't know if you understand my query but I am posting the following picture:
![screenshot from 2019-03-08 18-10-24](https://user-images.githubusercontent.com/31353695/54028596-a42ca080-41cd-11e9-9a16-0d9a4cf74c83.png)

The button and the text are two different items. When the content is entered, shouldn't it adapt the height automatically as per the content size?

**Comment by gmsa** [comment]
No, it shouldn't adapt the height automatically. You have to handle it yourself. See #195.
