### ISSUE TITLE
ie11  will bounce when dragging

### ISSUE THREAD

**Issue by 1615450788** [jbaysolutions/vue-grid-layout#31]
ie11 will bounce when dragging

**Comment by gmsa** [comment]
What do you mean by bounce? Just tried here on IE11 and looks normal. Can you be more specific?

**Comment by 1615450788** [comment]
Yes, it looks normal. Please drag try. Very bad left and right jitter

**Comment by gmsa** [comment]
Sorry, I see no jitter...

![IE11](http://i.imgur.com/6FTL7Xo.gif)
