### ISSUE TITLE
Using prop for layout is causing height and width to be undefined

### ISSUE THREAD

**Issue by crotanite** [jbaysolutions/vue-grid-layout#310]
**Software version:**
 - Vue Version: 2.6.8
 - vue-grid-layout Version: 2.3.4

**Description:**
I'm trying to pass the layout for the GridLayout component as a prop and using that directly without setting it as data.
However, using the prop within the GridLayout component is causing the h and w properties to be set to undefined. If I do not use the prop here and instead use an empty array, the h and w properties are not being overwritten.
I have tested this with events and even in the beforeMount even, the layout is not showing the correct h and w values, only undefined.

`<view-user-tab-profile-edit v-if="editing" :widgets="widgets"></view-user-tab-profile-edit>`
```
<template>
	<div>
		<grid-layout
			:layout="widgets"
			:col-num="3"
			:row-height="250"
			:is-draggable="true"
			:is-resizable="true"
			:is-mirrored="false"
			:vertical-compact="true"
			:margin="[15, 15]"
			:use-css-transforms="true">
			<grid-item v-for="widget in widgets" :key="widget.id"
				:x="widget.x"
				:y="widget.y"
				:w="widget.w"
				:h="widget.h"
				:i="widget.id"
				:max-h="2"
				:max-w="3"
				drag-allow-from=".drag">
					<div class="widget" :key="widget.id">
						<!-- drag -->
						<div class="drag">
							<font-awesome-icon icon="grip-horizontal" fixed-width/>
						</div>
						<!-- box -->
						<div class="box"></div>
					</div>
			</grid-item>
		</grid-layout>
	</div>
</template>

<script>
	export default
	{
		props: ['widgets'],
	}
</script>
```

The errors: Invalid prop: type check failed for prop "w". Expected Number with value NaN, got Undefined and Invalid prop: type check failed for prop "h". Expected Number with value NaN, got Undefined

**Comment by kalle81** [comment]
I had the same problem if the unique identifier in layout is missing.
You use the id for the unique identifier **i** in widget, that's ok,
but in widgets the unique identifier **i** must also be present.

**Comment by harrisjose** [comment]
You might wanna try cloning the object before binding it in to the layout prop. I'm not sure why this works though :|

**Comment by crotanite** [comment]
@kalle81 You were right, switching from `id` to `i` fixed this error. Thank you for your assistance!
