### ISSUE TITLE
Width of blocks is 1px smaller than it should be

### ISSUE THREAD

**Issue by stijnvanackerbbright** [jbaysolutions/vue-grid-layout#314]
**Software version (please complete the following information):**
 - Browser chrome
 - Vue Version 2.6.9
 - vue-grid-layout Version: 2.3.4

The width of the blocks seem to be more or less 1px smaller than what they should be when I do the calculation myself.

With the following data:
- width: 720px
- col-num: 12
- margin: [10, 10]
- responsive: false

The width of the blocks on the grid should be 50 right? (720 / 12) - 10?
However I've noticed every block is 49px wide. If I resize it to 2 blocks it becomes 108 px wide (considering a 10px margin that means every block is again 49px wide). At 3 blocks it becomes 168px. (so every block is 49.333 px at that point)

This is causing me difficulties when trying to draw grid lines that match the blocks, can you explain how the width of every block is determined?

**Comment by luisalvarado** [comment]
Hi friend, are you also counting border width? Normally it is 1px.

**Comment by stijnvanackerbbright** [comment]
Hi, I figured it out in the end.
The calculation for block width is `(width - marginLeft) / col-num`
