### ISSUE TITLE
Capture @click event

### ISSUE THREAD

**Issue by Joebayld** [jbaysolutions/vue-grid-layout#318]
**Is your feature request related to a problem? Please describe.**
I want to use my grid items as buttons - but I can't get the mouseDown event. 

**Describe the solution you'd like**
I'd like to get some sort of event when the user clicks in the grid item. 

**Additional context**
In my instance, I have resizing and editing disabled. I'd like to know when the user clicks anywhere inside the grid item. Currently any @click events don't fire..

**Comment by gmsa** [comment]
Thats something you have to implement yourself. Create a button or a clickable div on each grid item and handle the click events.
