### ISSUE TITLE
Possible to have grid-layout inside grid-item inside another grid-layout?

### ISSUE THREAD

**Issue by nicokruger** [jbaysolutions/vue-grid-layout#32]
From my initial tests it doesn't seem to work correctly.

It's almost like the two grid layouts are sharing some state and working against one another.

Just want to know if it should be possible before I try and go deeper and figure out what I might be doing wrong.

Thanks

**Comment by gmsa** [comment]
I don't think thats possible right now, for the same reasons described in #22. We will need to fix the eventBus to be able to have multiple instances of grid-layout

**Comment by francescoagati** [comment]
with vue 2.2 with inject and provide now can be possible use also a local event bus

**Comment by gmsa** [comment]
@francescoagati sounds nice, is [this](https://vuejs.org/v2/api/#provide-inject) it?

**Comment by francescoagati** [comment]
yes this. is like the context of react but the context can be injected in any point of the tree and all the child can see the properties injected. this is nice for create data userland

**Comment by francescoagati** [comment]
you can see an example of local bus event here https://alligator.io/vuejs/custom-component-renderers/
