### ISSUE TITLE
Update interactjs to v1.4

### ISSUE THREAD

**Issue by fuzzzerd** [jbaysolutions/vue-grid-layout#320]
Interact is [now up to v1.4](https://github.com/taye/interact.js/releases/tag/v1.4.0) and includes several bug fixes which would be nice to have.

**Comment by gmsa** [comment]
Which bug fixes specifically, do you have any idea?

**Comment by fuzzzerd** [comment]
Personally, I'd benefit from the [improved feature detection for pointer events in MSIE Web Browser Control](https://github.com/taye/interact.js/commit/a9f474ded891d1e5517d72c088afcda445777c26). I said several knowing there are others fixes that may benefit others as well.

**Comment by fuzzzerd** [comment]
Any update on this? Would you be open to a PR?

**Comment by gmsa** [comment]
Sure! Submit a PR

**Comment by fuzzzerd** [comment]
> 
> 
> Sure! Submit a PR

I updated to the latest v1.5.3, and everything seems to work fine.
