### ISSUE TITLE
How to disable drag and resize on all grid-items

### ISSUE THREAD

**Issue by xkubr** [jbaysolutions/vue-grid-layout#322]
What is the correct way to disable drag & resize on all grid-items in the grid-layout?

**Comment by gmsa** [comment]
Check the readme

**Comment by xkubr** [comment]
I did. The readme mentions dragIgnoreFrom & resizeIgnoreFrom but these target the elements within the item. That is not really what I am looking for. To use these I would need to add all elements. I was hoping there was a global setting, at the grid-layout level. Or is there something else I missed in the readme?

**Comment by gmsa** [comment]
isDraggable and isResizable

**Comment by xkubr** [comment]
Aaaah, seem obvious now that you point it out, thank you. Not sure how I missed that, appreciate it. vue-grid-layout is a great product btw.
