### ISSUE TITLE
Resizable does not work

### ISSUE THREAD

**Issue by alataknet** [jbaysolutions/vue-grid-layout#323]
Hello,
 - Vue Version 2.6.10
 - vue-grid-layout Version:  2.3.3

I am using your basic example inside my code.
The draggable works fine, but the function resizable does not work.
And the render is in rtl mode
Do you have any clue why?

**Comment by gmsa** [comment]
See #211

**Comment by alataknet** [comment]
Thank you for your answer.
So there is no solution ?
Because it works fine on your demo.

**Comment by alataknet** [comment]
I don't want the RTL mode, but it is set as rtl

**Comment by alataknet** [comment]
Hello
If i set :is-mirrored=true then everything is fine, but i understood it should be false by default to have the LTR mode.
