### ISSUE TITLE
Programmatically set rowHeight property

### ISSUE THREAD

**Issue by JivanRoquet** [jbaysolutions/vue-grid-layout#326]
After the initial rendering has been done, how to programmatically modify a property of the grid layout?

E.g. if one wants to change `isDraggable` from false to true at any point in time, or `rowHeight` or any other property.

Follow-up question: is it then necessary to trigger a re-render? For instance, if we dynamically change `rowHeight`, do we need to re-render the grid or is taken care of automatically? If it is necessary, is there a dedicated method?

Use case is I'd like to listen to the browser window's resize events, and adjust `rowHeight` so that the grid "fills" the window's height. In theory that could be done by watching the window's height, and every time it changes, programmatically change the value of `rowHeight`. It looks like a somewhat dirty hack but so far I haven't found any other way to achieve that purpose.

**Comment by JivanRoquet** [comment]
One thing I've tried:

```html
<grid-layout
          ref="dashboardGridLayout"
          :layout.sync="layout"
          :row-height="50">
    <!-- ... -->
</grid-layout>
```

```js
export default {
  mounted() {
    this.$nextTick(() => {
      this.$refs.dashboardGridLayout.rowHeight = 100
    })
  }
}
```

The above triggers an error

> [Vue warn]: Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value. Prop being mutated: "rowHeight"

**Comment by gmsa** [comment]
If you're asking that question, maybe you need to learn a bit more about how Vue works. The demo also demonstrates how to do that: https://jbaysolutions.github.io/vue-grid-layout/examples/01-basic.html
