### ISSUE TITLE
how to resize on this screen of different sizes

### ISSUE THREAD

**Issue by yoyomule** [jbaysolutions/vue-grid-layout#345]
**Describe the solution you'd like**
Hello, the created grid cell, I hope to automatically resize on this screen of different sizes. Can this be done?

**Comment by lx812833** [comment]
I also hope

**Comment by JivanRoquet** [comment]
+1 to this one. Currently using a very dirty hack, dirty both in code and in render.

Would love to see a proper native support for automatic resizing which reacts to window resizes.

**Comment by gmsa** [comment]
If you're referring to being responsive, that's already possible:  https://jbaysolutions.github.io/vue-grid-layout/guide/08-responsive-predefined-layouts.html
Properties: http://localhost:8081/vue-grid-layout/guide/properties.html#responsivelayouts
