### ISSUE TITLE
Responsive not work when open in small view

### ISSUE THREAD

**Issue by bagaskarala** [jbaysolutions/vue-grid-layout#348]
**Software version (please complete the following information):**
 - Browser Chrome
 - Vue Version 2.6.10
 - vue-grid-layout Version: 2.3.4

**Describe the bug**
Responsive not work when i load this plugin from small device, but when i resize browser windows it will work normally

**To Reproduce**
https://recordit.co/CqYh8Ey6iG

**Expected behavior**
It should fill all the column, like it should be

**Screenshots**
https://recordit.co/CqYh8Ey6iG

**Additional context**
This is my grid-layout
`<grid-layout
        :layout.sync="layout"
        :col-num="12"
        :row-height="70"
        :is-draggable="editDashboard"
        :is-resizable="editDashboard"
        :touch-action="editDashboard ? 'none' : 'auto'"
        :margin="[10, 10]"
        :responsive="responsive"
        :breakpoints="{ lg: 700, xs: 0}"
      ></grid-layout>`

this is my grid-item
`<grid-item
          v-for="widget in widgets"
          :x="widget.layout.x"
          :y="widget.layout.y"
          :w="widget.layout.w"
          :h="widget.layout.h"
          :i="widget.layout.i"
          :key="widget.layout.i"
          :min-w="2"
          :min-h="2"
        ></grid-item>`

**Comment by gmsa** [comment]
You need more breakpoints, like :breakpoints="{ lg: 700, xs: 300, xxs: 0}"
