### ISSUE TITLE
Col width updated after release mouse button

### ISSUE THREAD

**Issue by jousepo** [jbaysolutions/vue-grid-layout#355]
**Software version (please complete the following information):**
 - Browser chrome 76.0.3809.132
 - Vue Version 2.6.10
 - vue-grid-layout Version: 2.3.5 (working fine in 2.3.4)

**Describe the bug**
In some cases cols will autoresize to 1 col bigger after resize.

**To Reproduce**
1. Instance a grid
2. Add an item and resize it to 6 columns
4. See error (after release mouse button will be resized to 7)

**Expected behavior**
While resize action the preview looks ok (6 columns) but when i release button it resizes to 7.

**Screenshots**
while resizing:
![image](https://user-images.githubusercontent.com/29270718/64533723-63484c80-d314-11e9-8853-ff58a05c30a4.png)

After release mouse button:
![image](https://user-images.githubusercontent.com/29270718/64533754-70fdd200-d314-11e9-871d-12f2e9227b9b.png)

**Additional context**
Screen resolution 1920*1200

Maybe the problem is for these piece of code where the col its changed to 7 instead of 6:

>  // Helper for generating column width
>     calcColWidth: function calcColWidth() {
>       var colWidth = (this.containerWidth - this.margin[0] * **(this.cols + 1))** / this.cols; 
>

**Comment by PennyYip** [comment]
Confirmed having the same issue, reverting to 2.3.4 solved the problem.

**Comment by gmsa** [comment]
Have a good idea what caused this, I'll revert it tomorrow and issue a new release

**Comment by jousepo** [comment]
Thx!!!!!
