### ISSUE TITLE
Dynamic Grid Item Height

### ISSUE THREAD

**Issue by Dave3of5** [jbaysolutions/vue-grid-layout#356]
Currently the height of an individual grid item has to be set when the grid is created along with the overall size of a row.

In responsive mode I want each individual grid item to shrink or grow depending on the content of the grid item. At the moment I have to do this by working out the width of the page and recalculating the grid items height.

Is there a way to not have to set the height of the grid item but only when the table moves into responsive mode?

**Comment by gmsa** [comment]
Might want to check #210

**Comment by Dave3of5** [comment]
@gmsa I actually changed it in css:

```
@media only screen and (max-width: 501px) {
  .vue-grid-item {
    height: fit-content!important;
    transform: none!important;
    position: relative!important;
    margin-bottom:10px;
  }
}

```

Not the greatest but it works. This also sorted out the misordering that the css transform do when in responsive mode.

**Comment by Dave3of5** [comment]
FYI I also included:

```
@media (hover:none), (hover:on-demand) {
  .vue-grid-item {
    height: fit-content!important;
    transform: none!important;
    position: relative!important;
    margin-bottom:10px;
  }
}
```

Which will make it change for all mobile devices regardless of their orientation and such. That's what i currently want, it may not be what others want but I thought I'd include it. I'll close this issue now as I'm happy with this solution.
