### ISSUE TITLE
Auto Layout (or does it already exist)?

### ISSUE THREAD

**Issue by ssuess** [jbaysolutions/vue-grid-layout#357]
It would be great if there was an auto layout mode or method that would take elements that are sized but not positioned, and lay them out in the best possible way (and then store those x,y positions). Something similar to [packery](https://packery.metafizzy.co/).

Is there already in the project something that does any kind of auto-layout and repositioning of elements? (If so I apologize I have not found it, could you point me in that direction).

Thanks for an awesome project btw.

**Comment by gmsa** [comment]
Only option related to that is verticalCompact https://github.com/jbaysolutions/vue-grid-layout/blob/master/README.md#properties
