### ISSUE TITLE
关于参数h定义是rowHeight定义数值的倍数,实际项目中并不是这样,数值越大误差就越大

### ISSUE THREAD

**Issue by singgl** [jbaysolutions/vue-grid-layout#359]
关于参数h定义是rowHeight定义数值的倍数,实际项目中并不是这样,数值越大误差就越大

**Comment by gmsa** [comment]
English only please

**Comment by sam019** [comment]
The issue meaning: the grid item's height not equal to: rowHeight * itemLayout.h, this is confusing...
