### ISSUE TITLE
Resize grid item in specific configs (width, height)

### ISSUE THREAD

**Issue by havietduc91** [jbaysolutions/vue-grid-layout#360]
Hi, Vue grid layout team,

Firstly, thank for the effort you're putting in this library, really excellent

And secondly, how we can config specific configs sizes to resize for grid item?
For example, there are three grid items with specific sizes as below:
```
Grid item 1 (width x height): 

 - 664 x 400 (minimum)

 - 1006 x 400 (default)

 - 1348 x 400 (maximum)

Grid item 2:

  - 322x400 (min, default)

  - 664x400

  - 1006x400

  - 1348x400

  - 1690x400 (max)

Grid item 3

  - 1006x400 (min)

  - 1348x400 (default)

  - 1690x400 (max)
```
We want the users just allowed to resize grid item in specific sizes.
So could you please let me know the solution to resolve it. 

Many thanks

**Comment by gmsa** [comment]
Thats not possible
