### ISSUE TITLE
Inserting a grid item at the location of an user's click

### ISSUE THREAD

**Issue by veeral-patel** [jbaysolutions/vue-grid-layout#364]
**Describe the solution you'd like**

I'd like to be able to right click an empty area of the grid and click "insert a dashboard" here. Thoughts on how I'd achieve this?

I know Vue Grid Layout uses its own row/column layout, so I would need to somehow translate (x, y) coordinates of the click (from the browser) into (row, col) coordinates. I'm not sure how to do this. 

**Describe alternatives you've considered**

I've succeeded at inserting a dashboard into a hard-coded place in the grid (row 0, column 0). However, users would need to move the dashboard to the desired location in the grid, once it's created

**Comment by Carson126** [comment]
1. can get the cursor-pointer position
   ``` javascript
   dx = cursor-pointer.pageX - container.offsetX
   dy = cursor-pointer.pageY - container.offsetY
   ```
2. compute co.pos
``` javascript
    co.pos.x = ~~(dx/container.width/colNum)
    co.pos.y = ~~(dy/rowHeight)
``` 
3. push new data to layout
``` javascript
   this.layout.push({x:co.pos.x, y:co.pos.y, w:w,h:h, i:(this.layout.length-1)})
```
4. emit position
``` javascript
   this.$refs.gridLayout.dragEvent(  'dragend',  String(this.layout.length.slice(-1).i), x:pos.x, y: co.pos.y, h:h,  w:w )
```
*maybe you want the placeholder
you can new dragEvent("dragstart") and dragEvent("dragend") and then call $ref.grid-item.handleDrag(dragEvent);*

good luck
