### ISSUE TITLE
Chart width is not render exactly

### ISSUE THREAD

**Issue by huymq85git** [jbaysolutions/vue-grid-layout#365]
**Software version (please complete the following information):**
 - Browser [e.g. chrome, safari]: chrome
 - Vue Version [e.g. 2.5.7]: 2.6
 - vue-grid-layout Version: [e.g. 2.3.3]: 2.3.6

**Describe the bug**
I want to display a v-chart in the grid, but the width of the chart is not render exactly.
The width is equal to 0.

**Screenshots**
- This is bug
![bug](https://user-images.githubusercontent.com/38619649/66624487-85d2cb80-ec1a-11e9-9aa6-9cab713d1164.png)
- This is the one I expect
![expected](https://user-images.githubusercontent.com/38619649/66624488-85d2cb80-ec1a-11e9-90f8-3635738ddd6a.png)

Thank you very much for your help

**Comment by gmsa** [comment]
Most likely a bug on you code
