### ISSUE TITLE
How to set fixed width and height

### ISSUE THREAD

**Issue by zuohailiang** [jbaysolutions/vue-grid-layout#367]
Set x, y, w, h as Numbers according to the grid, then how to set w and h as fixed pixel sizes, for example: w=300px; H =300px, x and y need to set the position in each layout. Is there any way to automatically calculate the position of each box, instead of specific setting the position of x and y? Please see this question and help to reply, thank you very much

**Comment by jcricaro** [comment]
@zuohailiang 

I believe you can do this by setting the row height

```
<grid-layout
   :row-height="100"
```
so basically h=3 is 3*100 (making it 300px)

width is pretty much the same thing, but you have to set a container size, set how many columns ```:col-num="12"```, maybe also consider the margins ```:margin="[10, 10]"```

**Comment by gmsa** [comment]
Not possible to do, alternative is what @jcricaro described
