### ISSUE TITLE
When I use this component under IE9, the component cannot load and display.

### ISSUE THREAD

**Issue by SnowyEvening** [jbaysolutions/vue-grid-layout#377]
**Software version (please complete the following information):**
 - Browser [IE9]
 - Vue Version [2.5.17]
 - vue-grid-layout Version: [2.3.7]

**Describe the bug**
When I use this component under IE9, there is an error. The component cannot load and display. The specific code in question is at the bottom.

```
// The code is in the /dist/Vue-grid-layout.common.js file
// Line number is 4404

var setPublicPath_i
  //console.log(window.document)                  // Ok
  //console.log(window.document.currentScript)    // got a number or string : 9
  // when execute next line code, got an error
  //console.log(window.document.currentScript.src.match(/(.+\/)[^/]+\.js(\?.*)?$/)[1])
  
  // The source code below will execute and got an error when the component runs.

  if ((setPublicPath_i = window.document.currentScript) && (setPublicPath_i = setPublicPath_i.src.match(/(.+\/)[^/]+\.js(\?.*)?$/))) {
    __webpack_require__.p = setPublicPath_i[1] // eslint-disable-line
}
```

The error is `Failed to resolve async component default: TypeError: Cannot get undefined or null referenced property 'match'`

**Expected behavior**
Expected it can display normally

**Comment by gmsa** [comment]
There are no plans to support end-of-life IE versions

**Comment by SnowyEvening** [comment]
> There are no plans to support end-of-life IE versions

Ok, thanks
