### ISSUE TITLE
when item is v-charts,item out grid

### ISSUE THREAD

**Issue by xuanxiaoxiao** [jbaysolutions/vue-grid-layout#381]
**Software version (please complete the following information):**
 - Browser Chrome
 - Vue Version 2.6.10
 - vue-grid-layout Version:2.3.7
 - v-charts Version 1.19.0

**Describe the bug**
In the official example, the v-charts plug-in was introduced as the content

**Example**:
`<ve-pie :data="chartData"></ve-pie>`

When I tried to solve this problem, 
I found that when I resized the window, it behaved normally, but the user could see the exception

**Comment by xuanxiaoxiao** [comment]
This problem is not found in version 2.3.6

**Comment by xuanxiaoxiao** [comment]
sorry, I have solved the problem of v-chart

**Comment by thedelk** [comment]
> sorry, I have solved the problem of v-chart

Would you mind sharing what you did to resolve your issue, in case other people have the same problem?
