### ISSUE TITLE
Weird dragging behaviour when programmatically adding elements to Grid

### ISSUE THREAD

**Issue by eduardhasanaj2** [jbaysolutions/vue-grid-layout#389]
Hello! First of all, thanks for the great plugin!

I have setup a grid layout with the following settings:
      :is-draggable="true"
      :is-resizable="false"
      :vertical-compact="true"
      :margin="[0, 0]"
      :use-css-transforms="true"

If I load a lot of items at start, everything works flawlessly. However, If I have an empty grid, and then add items (by click or something), the grid elements have weird dragging behaviour. They don't move when other items are being draged over them. Below is a gif that demonstrates this weird behaviour.
I checked, and the items have valid properties (x, y, w, h, i). What could be causing the problem?

Thanks in advance

![vue-grid-layout-error](https://user-images.githubusercontent.com/23219826/71360147-1f114d00-258f-11ea-84a5-e580e787c6cd.gif)

**Comment by gmsa** [comment]
Please use the issue template and provide a code sample as well.

**Comment by eduardhasanaj2** [comment]
I am closing this issue because I couldn't fix it, therefore used another plugin.
