### ISSUE TITLE
When I update the layout, I want an event to give the new recalculated layout data to me

### ISSUE THREAD

**Issue by ben-lau** [jbaysolutions/vue-grid-layout#393]
I use Vuex to control the layout in my project. When I want to insert one GridItem below a marked GridItem, I set the new GridItem's 'y' to the marked GridItem's 'y' plus its 'h', then It will appear below the marked one.But there's a problem, I watch the store in my view and when it's changed, I will set the new layout to the view's layout, however, it can't trigger the update event, and I can't got the layout data with recalculated.

![image](https://user-images.githubusercontent.com/16952163/71639674-d1df5a80-2cb5-11ea-9d58-ee17c12970d7.png)

I read your source code, the updated event only trigger by drag or resize, is it not resonable?

**Comment by Zamirk** [comment]
+1. Would be very useful.

**Comment by mrvnklm** [comment]
+1 having the same issue, do you know any solid workaround?

**Comment by ben-lau** [comment]
> +1 having the same issue, do you know any solid workaround?

I pull request to solve this problem.
#394

**Comment by bifacil** [comment]
+1 Same problem

**Comment by gmsa** [comment]
Fixed by https://jbaysolutions.github.io/vue-grid-layout/guide/events.html#layoutupdatedevent
