### ISSUE TITLE
TypeError: Cannot read property 'uninstall' of undefined

### ISSUE THREAD

**Issue by vitorhps** [jbaysolutions/vue-grid-layout#398]
When i use Grid Layout and Grid item, these errors appear:

[Vue warn]: Error in beforeDestroy hook: "TypeError: Cannot read property 'uninstall' of undefined"
[Vue warn]: Error in beforeDestroy hook: "TypeError: Cannot read property 'unset' of undefined"

![package json - agil-online-frontend-quasar - Visual Studio Code  Administrator](https://user-images.githubusercontent.com/40525572/73874137-524f2900-4829-11ea-9867-37684937f1d6.jpg)

I am using "vue-grid-layout": "^2.3.6"

**Comment by P8TRO** [comment]
I am also seeing this. It doesn't produce any noticable visual bugs since it is on unmount but the errors are definitely jarring.

**Comment by davidwashere** [comment]
I was receiving the same error and also came here looking for resolution

I got rid of the error by using a dynamic import for the component containing the `vue-grid-layout`

I'm using the standard project layout created by the Vue CLI and have a `Collection` component which contained the `vue-grid-layout`, changing this:

```javascript
...
import Collection from "../components/Collection.vue"

export default {
  components: {
    Collection
  }
}
...
```
to this:

```javascript
...
export default {
  components: {
    Collection: () => import("../components/Collection.vue")
  }
}
...
```
Got rid of the error for me.

Hope that helps!

**Comment by gmsa** [comment]
should be fixed in the next release
