### ISSUE TITLE
Vue v2 support

### ISSUE THREAD

**Issue by gmsa** [jbaysolutions/vue-grid-layout#4]

**Comment by RuCKk** [comment]
+1

**Comment by vesper8** [comment]
+1

**Comment by eljefedelrodeodeljefe** [comment]
@jbaysolutions @gmsa is this planned? I wanted to take a look at porting later and could PR if being successful.

**Comment by gmsa** [comment]
@eljefedelrodeodeljefe its planned, but we don't have that much free time right now. Feel free to PR!

**Comment by p06bx0m** [comment]
any updates so far?

**Comment by gmsa** [comment]
Nope, just don't have the free time to do it right now, sorry.

**Comment by gmsa** [comment]
Hi all, just released version 2.0.0 with Vue 2 support!
