### ISSUE TITLE
Shouldn't grid-item be a slot?

### ISSUE THREAD

**Issue by CheyenneForbes** [jbaysolutions/vue-grid-layout#402]
Whats the point of having both `v-for="item in layout"` for `grid-item` and `:layout="layout"` or `:layout.sync="layout"` for `grid-layout`?

**Comment by CheyenneForbes** [comment]
Anyone?

**Comment by gmsa** [comment]
You can try and modify the source to get it working with slots and submit a PR. I couldn't make it work.

**Comment by CheyenneForbes** [comment]
I'm unable to test my modifications

All works okay when I do `yarn add vue-grid-layout` but i get the following message in the browser when I do `yarn add file:/{PATH}/vue-grid-layout` after cloning it (even without adding my changes):

```
[Vue warn]: Unknown custom element: <grid-layout> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
```

Here are the steps I took before running the code:

```
cd vue-grid-layout
npm install
npm run build-lib

cd .../test-vgl
yarn add file:/{PATH}/vue-grid-layout
```

**Comment by CheyenneForbes** [comment]
any tips?

**Comment by CheyenneForbes** [comment]
👀

**Comment by CheyenneForbes** [comment]
Hey @gmsa can you give any information regarding my last query?

**Comment by milgner** [comment]
@CheyenneForbes did you register the component using 

```js
components: {
    GridLayout: VueGridLayout.GridLayout,
    GridItem: VueGridLayout.GridItem
},
```

The error message would be consistent with this part not being there.

I use Vue Class Components (Typescript) and there it looks like
```typescript
@Component({
  components: {
    GridLayout: VueGridLayout.GridLayout,
    GridItem: VueGridLayout.GridItem,
  },
})
export default class MainScreen extends Vue {
}
```

**Comment by CheyenneForbes** [comment]
oops, just remembered I stopped doing that because I'm using SSR, I'm using the hack to add it via plugins... I forgot to enable the plugin

**Comment by CheyenneForbes** [comment]
we need to make this support being imported when using SSR so we can at least import and wrap it with <no-ssr>
