### ISSUE TITLE
set 'row-height',  the actual rendered element height is not as expected. 

### ISSUE THREAD

**Issue by 654138926qq** [jbaysolutions/vue-grid-layout#406]
set 'row-height' and 'margin'  at the same time, the actual rendered element height is not as expected. 

For example:     <grid-layout v-if="layout && layout.length"
                 :layout.sync="layout"
                 :col-num="12"
                 :row-height="30"
                 :is-draggable="!isStatic"
                 :is-resizable="false"
                 :is-mirrored="false"
                 :vertical-compact="true"
                 :margin="[10, 10]"
                 :use-css-transforms="true"
                 @layout-updated="layoutUpdatedEvent">
-----------------------------------------------------------------------------------------------
'row-height' = 30  'h' = 12   the rendered element height is 360 as expected, bu it is 470 actually

Google Chrome 79.0.3945.130

**Comment by Liuxingguo** [comment]
because margin is set， 30*12+10*(12-1)=470
