### ISSUE TITLE
Remove borders on grid-item

### ISSUE THREAD

**Issue by tomwalsh96** [jbaysolutions/vue-grid-layout#408]
Is this possible? I have read through the documentation and cannot find any reference to it.

I have tried overriding the CSS to no success.

Can this be a feature request?

**Comment by gmsa** [comment]
What borders?

**Comment by tomwalsh96** [comment]
![border grid layout](https://user-images.githubusercontent.com/25707613/76015688-6772b280-5ed0-11ea-83f6-46133e1d8996.png)
the ones surrounding grid-item in the above image
