### ISSUE TITLE
[Question] html5 output from gridLayout with stored variables to fetch sql content

### ISSUE THREAD

**Issue by scyreDE** [jbaysolutions/vue-grid-layout#410]
Hi Pals,

i got a question over there. I am new to vue.js but the grid layout fits exactly my needs. I wan't to render html5 syntax via the "var gridLayout" to display sql stored content. How could i manage to do that?

I know that there is a way to display html5 code within a var in js and render it, but i am totaly lost when it comes to this constellation.

Would appreciate your help!
Best regards
Simon

**Comment by davidmunkacsi93** [comment]
Hi Simon,

I am doing something similar for REST APIs with the help of vue-grid-layout.

Check out and follow my repository: https://github.com/davidmunkacsi93/generic-customizable-web-ui <https://github.com/davidmunkacsi93/generic-customizable-web-ui>

Hope it helps you :)

Bests,
David
