### ISSUE TITLE
set x and y element to 0 then it is displayed below each other

### ISSUE THREAD

**Issue by DishantDesai** [jbaysolutions/vue-grid-layout#414]
Is it possible to add grid box dynamically without giving x and y position if we will give x and y position to all element then it is added below to next element but my request is if we provide x and y axes 0 in all elements then grid should be displayed side by side rather than below each other.

**Comment by DishantDesai** [comment]
Is it possible to add grid box dynamically without giving x and y position if we will give x and y position to all element then it is added below to next element but my request is if we provide x and y axes 0 in all elements then grid should be displayed side by side rather than below each other.

**Comment by davidmunkacsi93** [comment]
Have you thought about rendering the grid items in a loop? Then based on your index you can use the modulo operator to calculate your x position. E.g. assuming you have grid items with the width of 3, then x = (index % 3).

If your items have variable width then you can always use the bin packing algorithm to pack your items in the layout.

**Comment by DishantDesai** [comment]
> Have you thought about rendering the grid items in a loop? Then based on your index you can use the modulo operator to calculate your x position. E.g. assuming you have grid items with the width of 3, then x = (index % 3)*3, so your items will be render besides each other in 3 columns.
> 
> If your items have variable width then you can always use the bin packing algorithm to pack your items in the layout.

I don't know about bin packing algorithm can you please explain

**Comment by davidmunkacsi93** [comment]
> modulo

There are plenty of NPM modules that implement bin-packing algorithm, you have to look into it ;)

But the other solution by calculating the x position on the fly works as well.

I am not quite sure what you want to do tho, a bit more information/code sections would be cool.

**Comment by DishantDesai** [comment]
I would like to have add column dynamically and that column should be added besides the previous column.
For example,
If the width of the column is 3 then there should be 4 columns in the first row and when I add next column then should be added to next column.

**Comment by davidmunkacsi93** [comment]
In this case it is simple math, you can always calculate the x,y position based on the number of the items. Like I mentioned above x = (index % number_of_columns) * width should work. So when you dynamically add a new item to your layout, which is going to be at the 5th place for instance, then x = (5 % 4) * 3.

**Comment by DishantDesai** [comment]
@davidmunkacsi93 Thank you for help.
