### ISSUE TITLE
Gap between blocks when margin 0

### ISSUE THREAD

**Issue by Aterbonus** [jbaysolutions/vue-grid-layout#42]
vue-grid-layout version: 2.1.5
Vue version: 2.2.5

When we set margins to 0, in certains widths there is a gap between blocks. The gap appears to be always 1px wide.

[Reproduction in Codepen](http://codepen.io/Aterbonus/full/jBXVKM/)

![vue-grid-layout issue](https://cloud.githubusercontent.com/assets/15003767/24536926/7da5cc9e-15b4-11e7-9757-85f197ccc070.png)

The issue appears to be solved when in [calcColWidth](https://github.com/jbaysolutions/vue-grid-layout/blob/master/src/GridItem.vue#L605) we add ```Math.round```

```var colWidth = (this.containerWidth - (this.margin[0] * (this.cols + 1))) / this.cols;```

to 

```var colWidth = Math.round((this.containerWidth - (this.margin[0] * (this.cols + 1))) / this.cols);```

But this needs further tests to ensure this solution not affect other calcs.

**Comment by gmsa** [comment]
Will check this whenever I have some free time

**Comment by gmsa** [comment]
It seems to work fine without your fix. I think the main problem on your sample is this:

```css
* {
  margin: 0;
  padding: 0;
}
```
