### ISSUE TITLE
Unable to drag if load an iframe.

### ISSUE THREAD

**Issue by yurizhang** [jbaysolutions/vue-grid-layout#420]
**Software version (please complete the following information):**
 - Browser chrome
 - Vue Version 2.6.10
 - vue-grid-layout Version: lastest

**Describe the bug**

![image](https://user-images.githubusercontent.com/20555332/79968908-5b17d880-84c3-11ea-939f-ef0cd9e326aa.png)

below is screeshot.  left slide of image was load an iframe, unable to drag. Dont show mouse point.
right slide of image is can drag. I have been tried modify frame z-index , no effect.

**Comment by liuxingguo** [comment]
you may need a wapper set to the iframe, such as a div, for easy to drag.
demo: https://github.com/liuxingguo/vue-dragable-layout-demo
你可能需要在iframe外包一层div，方便拖动，因为鼠标在iframe里外边组件就管不到了。参考 https://github.com/liuxingguo/vue-dragable-layout-demo

**Comment by V-yw** [comment]
@liuxingguo @yurizhang  

I am also facing the same problem now   but https://github.com/liuxingguo/vue-dragable-layout-demo 404 ，can i see you demo ?
