### ISSUE TITLE
怎么添加一个正在移动的元素

### ISSUE THREAD

**Issue by fish-uncle** [jbaysolutions/vue-grid-layout#422]
我现在，移动某个元素框A，（类似的还有很多元素框B，C……）
移动到某个区域后，可进行vue-grid-layout中的，上下调整
那在移动到框中时，
可以添加一个正在被移动的元素，（并且隐藏掉之前拖动的元素框A）

目前好像只能添加一个静止的元素

或者可以理解为，两个面板，可以从一个面板，移动到另一个面板

**Comment by lishaobobo** [comment]
你实现动态添加item了吗 ，我动态添加item的时候报错   Injection "eventBus" not found

**Comment by lishaobobo** [comment]
> 我现在，移动某个元素框A，（类似的还有很多元素框B，C……）
> 移动到某个区域后，可进行vue-grid-layout中的，上下调整
> 那在移动到框中时，
> 可以添加一个正在被移动的元素，（并且隐藏掉之前拖动的元素框A）
> 
> 目前好像只能添加一个静止的元素


你实现动态添加item了吗 ，我动态添加item的时候报错 Injection "eventBus" not found

**Comment by fish-uncle** [comment]
> > 我现在，移动某个元素框A，（类似的还有很多元素框B，C……）
> > 移动到某个区域后，可进行vue-grid-layout中的，上下调整
> > 那在移动到框中时，
> > 可以添加一个正在被移动的元素，（并且隐藏掉之前拖动的元素框A）
> > 目前好像只能添加一个静止的元素
> 
> 你实现动态添加item了吗 ，我动态添加item的时候报错 Injection "eventBus" not found

list动态更新就行，保持i不一样就行

**Comment by lishaobobo** [comment]
> > > 我现在，移动某个元素框A，（类似的还有很多元素框B，C……）
> > > 移动到某个区域后，可进行vue-grid-layout中的，上下调整
> > > 那在移动到框中时，
> > > 可以添加一个正在被移动的元素，（并且隐藏掉之前拖动的元素框A）
> > > 目前好像只能添加一个静止的元素
> > 
> > 
> > 你实现动态添加item了吗 ，我动态添加item的时候报错 Injection "eventBus" not found
> 
> list动态更新就行，保持i不一样就行

方便加个微信吗 ？或者发个示例吗 我的微信18510598865

**Comment by liuxingguo** [comment]
@fish-uncle @lishaobobo https://github.com/liuxingguo/vue-dragable-layout-demo

**Comment by fish-uncle** [comment]
http://form.making.link/basic-version/#/zh-CN/
@liuxingguo 
像这样的，两个面板之前的拖动，你这还是一个面板

**Comment by liuxingguo** [comment]
> http://form.making.link/basic-version/#/zh-CN/
> @liuxingguo
> 像这样的，两个面板之前的拖动，你这还是一个面板

https://sortablejs.github.io/Vue.Draggable/#/custom-clone

**Comment by lishaobobo** [comment]
@liuxingguo 谢谢了 我看看这个
