### ISSUE TITLE
To keep the other item' position when an item was removed

### ISSUE THREAD

**Issue by Wirlo** [jbaysolutions/vue-grid-layout#423]
Can it support to  keep the other item' position when one of the items was removed?

**Comment by Wirlo** [comment]
But it is designed to set position of rest of items that were not be removed automatically

**Comment by liuxingguo** [comment]
You may need set `<grid-layout :vertical-compact='false' … >`

**Comment by Wirlo** [comment]
I fixed it as the author said, thanks a lot
