### ISSUE TITLE
"setCursor" method performance issue

### ISSUE THREAD

**Issue by whins** [jbaysolutions/vue-grid-layout#425]
**Software version (please complete the following information):**
 - Browser:  chrome
 - Vue Version: 2.6.11
 - vue-grid-layout Version: 2.3.7

**Describe the bug**
`setCursor` method  performance issue - time is  ~100ms.

I cannot provide example but `vue-grid-item` contains svg graphics with animations.
Issue was solved by commenting method  `setCursor`. 
And I cannot understand why css rule `hover` on `vue-grid-item`  is not used

**Expected behavior**
Improved performance of  `setCursor`  or using `hover`

![image](https://user-images.githubusercontent.com/2223328/81165203-48f56a00-8f9a-11ea-8a62-8ae3198a9fbd.png)

**Comment by gmsa** [comment]
setCursor is an interact.js method, which is an external dependency. Not much we can do there.
