### ISSUE TITLE
get Next Coords to addItem

### ISSUE THREAD

**Issue by lokomass** [jbaysolutions/vue-grid-layout#426]
Hi,
Amazing plugin !
I'v created a button to add an item.
I want to know where I can put it.
I want to put it at the last row, first col, I mean, at the first place available at the bottom.
I have different width/height so, the function has to keep this in mind, like this.
My grid contains between 1 and 4 columns and unlimited rows

`getLastPos: function(w, h) {
   ...
}`

I can get lastY, but lastX is so complex : 

`getLastY: function() {
	var max = 0;
	for (i=0;i<this.layout.length;i++) {
		var hauteur = this.layout[i].y + this.layout[i].h;
		max = (hauteur > max) ? hauteur : max;
	}
	return max;
},`

Here somes examples, in yellow, the block should be insert
Exemple 1 : https://i.imgur.com/tRMjQzB.jpg
If I insert a block (1,1) => https://i.imgur.com/UBuLDyO.jpg

Exemple 2 : https://i.imgur.com/yXGiFbJ.jpg
If I insert a block (1,1) => https://i.imgur.com/isKDx28.jpg
If I insert a block (3,2) => https://i.imgur.com/05VuUVK.jpg

Exemple 3 : https://i.imgur.com/wwICvq7.jpg
If I insert a block (1,1) => https://i.imgur.com/smnONcY.jpg

Thanks for help

**Comment by annlumia** [comment]
Maybe you can use:

```html
<grid-layout
  :margin="[4, 4]"
  :row-height="4"
  ...
  ref="grids"
>
  
....
</grid-layout>
```

```js

getNextY(){
      const containerHeight = parseInt(
        this.$refs.grids.containerHeight().replace('px', '')
      )

      const usedRow = (containerHeight - (containerHeight % 4)) / 4
      const nextY = usedRow + 1

     return nextY
}

```

**Comment by gmsa** [comment]
You can modify this example to your needs: https://jbaysolutions.github.io/vue-grid-layout/guide/09-dynamic-add-remove.html
Source here: https://github.com/jbaysolutions/vue-grid-layout/blob/master/website/docs/.vuepress/components/Example09DynamicAddRemove.vue

**Comment by zhoufanglu** [comment]
> You can modify this example to your needs: https://jbaysolutions.github.io/vue-grid-layout/guide/09-dynamic-add-remove.html
> Source here: https://github.com/jbaysolutions/vue-grid-layout/blob/master/website/docs/.vuepress/components/Example09DynamicAddRemove.vue
Can you tell me the calculation rules for xy?
```js
this.layout.push({
                x: (this.layout.length * 2) % (this.colNum || 12),
                y: this.layout.length + (this.colNum || 12), // puts it at the bottom
                w: 2,
                h: 2,
                i: this.index,
            });
```
