### ISSUE TITLE
The grids cann't be controlled correctly when using effects transform: scale(n)" css

### ISSUE THREAD

**Issue by codestepwell** [jbaysolutions/vue-grid-layout#430]
Thank you for your work, this is a great plugin. I have a problem in use, because of some needs, when I use the effect "transform: scale(1.5)" css on its parent DIV container, I can't control it properly, such as stretching or moving. Is there any way to solve this problem? Thank you very much for your attention.

感谢您的工作，这是一个如此棒的插件。 由于某些需求，我在使用中遇到问题，当我在其父DIV容器上使用效果“ transform：scale（1.5）” css时，无法正确控制它，例如拉伸或移动。 有什么办法解决这个问题请？ 非常感谢您的关注。

**Comment by lustan3216** [comment]
Same problem here

**Comment by adt-hgkim** [comment]
+1

**Comment by adt-hgkim** [comment]
`react-grid-layout` has prop `transformScale`
```
// If parent DOM node of ResponsiveReactGridLayout or ReactGridLayout has "transform: scale(n)" css property,
// we should set scale coefficient to avoid render artefacts while dragging.
transformScale: ?number = 1,
```

**Comment by gmsa** [comment]
@adt-hgkim can you submit a PR based on the react-grid-layout implementation?

**Comment by adt-hgkim** [comment]
@gmsa OK

**Comment by adt-hgkim** [comment]
#505 PR here :)

**Comment by gmsa** [comment]
merged and included on release 2.4.0

**Comment by songispm** [comment]
Can you merge the recent new featuress (like this) to vue3 and release a new vue3.0 beta? Thanks. @gmsa

**Comment by humorHan** [comment]
same problem in vue3，when support scale?
