### ISSUE TITLE
Item's size changes when hiding/displaying it again

### ISSUE THREAD

**Issue by jatanassian** [jbaysolutions/vue-grid-layout#431]
**Software version (please complete the following information):**
 - Browser: Chrome
 - Vue Version: 2.6.11
 - vue-grid-layout Version: 2.3.7

**Describe the bug**
I have checkboxes to hide/display each item of my grid layout. I am using VueX to store the layout and use a computed property to filter it.
Whenever I hide an item and display it again, it appears with a smaller size. It goes back to normal whenever I resize the screen.

Here's is the [CodeSandbox Example](https://codesandbox.io/s/festive-voice-3mv3h?file=/src/components/Dashboard.vue).

**To Reproduce**
1. Click on any checkbox to hide an item
2. Click again to display it again, it should be smaller
3. Resize the size of the page, the item goes back to normal

**Additional context**
I noticed that the layouts data in GridLayout becomes empty whenever I click on any checkbox.
So I think it may be due to the fact that every time I click on the checkbox it updates the computed property which resets the layout?

**Comment by rin4ik** [comment]
I am experiencing the same. could you please check that @gmsa  @ftylitak

**Comment by lustan3216** [comment]
me, 2

**Comment by jatanassian** [comment]
If it can help anyone experiencing this, the only solution I've found so far was to disable the responsiveness by setting the responsive property to false

**Comment by rin4ik** [comment]
I need responsive layout though

**Comment by gmsa** [comment]
merged, thanks
