### ISSUE TITLE
容器宽度计算的时机

### ISSUE THREAD

**Issue by sunzhilei** [jbaysolutions/vue-grid-layout#435]
**Software version (please complete the following information):**
 - Browser：chrome
 - Vue Version：2.6.11
 - vue-grid-layout Version: 2.3.3

**Describe the bug**
在GridItem中嵌入了echarts组件，发现echarts组件的宽度超出GridItem的宽度。

主页面代码：
```
<template>
    <GridLayout
        :layout.sync="layout"
        :col-num="4"
        :row-height="100"
        :is-draggable="true"
        :is-resizable="true"
        :is-mirrored="false"
        :vertical-compact="true"
        :margin="[10, 10]"
        :use-css-transforms="true"
    >

        <GridItem v-for="item in layout"
                :x="item.x"
                :y="item.y"
                :w="item.w"
                :h="item.h"
                :i="item.i"
                :key="item.i">
            <div v-if="item.i==0" class="block">
                <BarComponent></BarComponent>
            </div>
            <div v-else class="block">
            </div>
        </GridItem>
    </GridLayout>
</template>
```
```
<script>

import VueGridLayout from 'vue-grid-layout';

import BarComponent from './echarts/bar';

export default {
    components: {
        GridLayout: VueGridLayout.GridLayout,
        GridItem: VueGridLayout.GridItem,
        BarComponent,
    },
    data() {
        return {
            layout: [
                {"x":0,"y":0,"w":1,"h":1,"i":"0"},
                {"x":1,"y":0,"w":2,"h":2,"i":"1"},
                {"x":3,"y":0,"w":1,"h":1,"i":"2"},
                {"x":0,"y":1,"w":1,"h":1,"i":"3"},
                {"x":3,"y":1,"w":1,"h":1,"i":"4"},
                {"x":0,"y":3,"w":1,"h":1,"i":"5"},
                {"x":1,"y":3,"w":2,"h":1,"i":"6"},
                {"x":3,"y":3,"w":1,"h":1,"i":"7"}
            ],
        }
    }
}
</script>
```
```
<style lang="less">
.block{
    width: 100%;
    height: 100%;
    border-style: solid;
    border-color: black;
}
</style>
```

图表组件代码：

`  
<template><div id="bar" :style="{width: '100%', height: '100%'}"></div></template>
`

```
<script>
export default {
    mounted(){
        this.draw();
    },
    methods: {
        draw(){
            var bar = this.$echarts.init(document.getElementById('bar'));
            bar.setOption({
                xAxis: {
                    data: ["衬衫","羊毛衫","雪纺衫","裤子","高跟鞋","袜子"]
                },
                yAxis: {},
                series: [{
                    name: '销量',
                    type: 'bar',
                    data: [5, 20, 36, 10, 10, 20]
                }]
            });
        }
    }
}
</script>
```

得到的结果是：
Bar组件的宽度超出GridItem，通过chrome调试工具看到GridItem的宽度为300px，Bar的宽度为1200px（canvas的宽度）。

期待的结果是：
Bar组件的宽度等于GridItem的宽度。

**Comment by sunzhilei** [comment]
> **Software version (please complete the following information):**
> 
> * Browser：chrome
> * Vue Version：2.6.11
> * vue-grid-layout Version: 2.3.3
> 
> **Describe the bug**
> 在GridItem中嵌入了echarts组件，发现echarts组件的宽度超出GridItem的宽度。
> 
> 主页面代码：
> 
> ```
>     <GridItem v-for="item in layout"
>             :x="item.x"
>             :y="item.y"
>             :w="item.w"
>             :h="item.h"
>             :i="item.i"
>             :key="item.i">
>         <div v-if="item.i==0" class="block">
>             <BarComponent></BarComponent>
>         </div>
>         <div v-else class="block">
>         </div>
>     </GridItem>
> </GridLayout>
> ```
> 
> <script>
import VueGridLayout from 'vue-grid-layout'; 
import BarComponent from './echarts/bar';
> export default {
> components: {
> GridLayout: VueGridLayout.GridLayout,
> GridItem: VueGridLayout.GridItem,
> BarComponent,
> },
> data() {
> return {
> layout: [
> {"x":0,"y":0,"w":1,"h":1,"i":"0"},
> {"x":1,"y":0,"w":2,"h":2,"i":"1"},
> {"x":3,"y":0,"w":1,"h":1,"i":"2"},
> {"x":0,"y":1,"w":1,"h":1,"i":"3"},
> {"x":3,"y":1,"w":1,"h":1,"i":"4"},
> {"x":0,"y":3,"w":1,"h":1,"i":"5"},
> {"x":1,"y":3,"w":2,"h":1,"i":"6"},
> {"x":3,"y":3,"w":1,"h":1,"i":"7"}
> ],
> }
> }
> }
> </script>
> 
> <style lang="less"> 
.block{ width: 100%; height: 100%; border-style: solid; border-color: black; } 
</style>
> 图标组件代码：
> <script> 
export default { 
mounted(){ 
this.draw(); 
}, 
methods: { 
draw(){ 
var bar = this.$echarts.init(document.getElementById('bar')); 
bar.setOption({ 
xAxis: { 
data: ["衬衫","羊毛衫","雪纺衫","裤子","高跟鞋","袜子"] }, 
yAxis: {}, 
series: [{ 
name: '销量', 
type: 'bar', 
data: [5, 20, 36, 10, 10, 20] 
}] 
}); 
} 
} 
} 
</script>

> 得到的结果是：
> Bar组件的宽度超出GridItem，通过chrome调试工具看到GridItem的宽度为300px，Bar的宽度为1200px（canvas的宽度）

期望的结果是：
Bar组件的宽度等于GridItem的宽度。

**Comment by gmsa** [comment]
English only please
