### ISSUE TITLE
How to minimize a GridItem ? 

### ISSUE THREAD

**Issue by thibaut-loftorbital** [jbaysolutions/vue-grid-layout#438]
Hey !

I would like to be able to maximize and minimize a GridItem (as for standard window management with a dock at the bottom of the viewport).

Issue #333 works well to maximize a gridItem, but I don't know how to minimize a GridItem, and make the layout reorder naturally.

Any idea on that ? My initial idea of applying a class, based on #333 

```
.gridItem.minimized {
  transform: scale(0) !important;
  height: 0 !important;
  width: 0 !important;
}
``` 

leaves a blank space where the minimized item was previously.
(see https://codesandbox.io/s/vue-grid-layout-maximize-widget-q0gxv?file=/components/GridComponent.vue:2947-3051)

**Comment by gmsa** [comment]
Have a look at the autoSize function in the readme. 

Related discussion: https://github.com/jbaysolutions/vue-grid-layout/pull/210

**Comment by thibaut-lo** [comment]
While investigating what you suggest, I haven't found a solution yet @gmsa , I will let you know if I find it. I am currently stuck in #227 issue where I shared my latest sandbox https://codesandbox.io/s/vue-grid-layout-minimized-item-thisslotsdefault0elmgetboundingclientrect-is-not-a-function-v3q6w
