### ISSUE TITLE
can I use another key for the data list？

### ISSUE THREAD

**Issue by Lzhong8385** [jbaysolutions/vue-grid-layout#440]
can I use another key for the data list? I tried to change the "i" to the "key", but it didn't respond every time.
![image](https://user-images.githubusercontent.com/19373044/86765674-0de7e380-c07c-11ea-92ae-e140f8dac6e5.png)
![image](https://user-images.githubusercontent.com/19373044/86766012-83ec4a80-c07c-11ea-9e17-4b109775dee5.png)

**Comment by AOphagen** [comment]
This just happened to me as well. We wanted to use more verbose property names like width, height, xposition etc. How come the bound value-containing variables need to have the same name as the variables you are setting the values into?

**Comment by Lzhong8385** [comment]
I just want to see if I can use other keys, such as ID, key and so on

**Comment by gmsa** [comment]
No, you have to use those keys
