### ISSUE TITLE
不使用v-for来生成grid-item会有问题，组件出现重叠并且拖动无效

### ISSUE THREAD

**Issue by i542873057** [jbaysolutions/vue-grid-layout#441]
**Software version (please complete the following information):**
 - Browser chrome
 - Vue Version 2.5.7
 - vue-grid-layout Version: 2.3.7

**Describe the bug**
不使用v-for来生成grid-item会有问题，组件出现重叠并且拖动无效

**To Reproduce**

**Expected behavior**

**Screenshots**
![我的代码](https://user-images.githubusercontent.com/16971894/87034791-00b52b00-c21b-11ea-8373-89f2fc6173f4.png)

![image](https://user-images.githubusercontent.com/16971894/87034729-eb400100-c21a-11ea-968e-26b068592455.png)

**Additional context**

**Comment by gmsa** [comment]
Sorry, english only
