### ISSUE TITLE
Demo broken (latest dist files are empty)

### ISSUE THREAD

**Issue by thedelk** [jbaysolutions/vue-grid-layout#447]
**Software version (please complete the following information):**
 - Chrome (84.0.4147.105), Firefox Developer (80.0b6), Edge Chromium (84.0.522.52)
 - vue-grid-layout Version: [e.g. 2.3.8]

**Describe the bug**
No examples on the [demo site](https://jbaysolutions.github.io/vue-grid-layout/examples/01-basic.html) are usable.

Upon further investigation, it looks like it's because the project didn't get built after the latest update (0438d9a6846bf90aa15d948c6230fcea0585e962). All of the files in `dist` are empty.

**To Reproduce**
1. Go to [the demo page](https://jbaysolutions.github.io/vue-grid-layout/examples/01-basic.html).
2. Try to use demo.
3. Realize you can't because [vue-grid-layout.umd.min.js](https://jbaysolutions.github.io/vue-grid-layout/dist/vue-grid-layout.umd.min.js) is empty.

**Expected behavior**
The demo should be usable.

**Comment by gmsa** [comment]
fixed
