### ISSUE TITLE
Toolbox / Dynamic Add/Remove / Drag from Outside

### ISSUE THREAD

**Issue by protonbobby** [jbaysolutions/vue-grid-layout#448]
Are there any plans to add Toolbox, Dynamic Add/Remove, or Drag from Outside which React-Grid-Layout has? 

https://strml.github.io/react-grid-layout/examples/6-dynamic-add-remove.html
https://strml.github.io/react-grid-layout/examples/14-toolbox.html
https://strml.github.io/react-grid-layout/examples/15-drag-from-outside.html

**Comment by gmsa** [comment]
No plans right now. Maybe you could submit a PR with those?

**Comment by protonbobby** [comment]
Thanks. I submitted a PR for Dynamic Add/Remove. #449

**Comment by dhamet70** [comment]
I submitted a PR for Drag from Outside exactly like React-Grid-Layout.

**Comment by dhamet70** [comment]
I submitted a PR for Drag From Outside
