### ISSUE TITLE
Blur when zooming。And The Z of translate3d is not used

### ISSUE THREAD

**Issue by liyangyangi** [jbaysolutions/vue-grid-layout#452]
**Software version (please complete the following information):**
 - Vue Version [e.g. 2.5.7]
 - vue-grid-layout Version: [e.g. 2.3.3]

**Describe the bug**

Please use the [CodeSandbox Template](https://codesandbox.io/s/5wy3rz5z1x?module=%2Fsrc%2FShowcaseLayout.js) to demonstrate your bug. It is much easier for us to help you if you do.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by liyangyangi** [comment]
![P 6_GA {%4B3{LJ5K(_Y2L](https://user-images.githubusercontent.com/22519600/91013565-72560680-e61a-11ea-8c86-28d87c69d6d9.png)
![D4BC YQ8}8HHSKZ9ZMEB03M](https://user-images.githubusercontent.com/22519600/91013578-784be780-e61a-11ea-9006-520b0de83178.png)

**Comment by liyangyangi** [comment]
var translate = "translate3d(" + left + "px," + top + "px, 0)";

translate3d blur when zooming.
how about --> var translate = "translate(" + left + "px," + top + "px)";

**Comment by gmsa** [comment]
When zooming how? Please describe the problem properly
