### ISSUE TITLE
how to build

### ISSUE THREAD

**Issue by MrSmallLiu** [jbaysolutions/vue-grid-layout#454]
I want to build the project . now I exec `npm run build-lib` but the lib not work
error message :
![image](https://user-images.githubusercontent.com/26038018/91274518-62245f80-e7b1-11ea-97b8-18a0efcc81e0.png)
thanks for your help

**Comment by gmsa** [comment]
works fine here

**Comment by MrSmallLiu** [comment]
how to build?  I download this project 2.3.8 and exec 'npm install' then exec 'npm run build-lib'. Is this operation correct？

thanks for your help

**Comment by MrSmallLiu** [comment]
how to build? I download this project 2.3.8 and exec 'npm install' then exec 'npm run build-lib'. Is this operation correct？

thanks for your help



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jbaysolutions/vue-grid-layout"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月26日(星期三) 晚上7:15
收件人:&nbsp;"jbaysolutions/vue-grid-layout"<vue-grid-layout@noreply.github.com&gt;;
抄送:&nbsp;"栗子哥哥@"<1016817543@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [jbaysolutions/vue-grid-layout] how to build (#454)





 
works fine here

**Comment by gmsa** [comment]
yes

**Comment by MrSmallLiu** [comment]
I do the same thing. `npm i` then `npm run build-lib`. but my&nbsp; build's file was only 300K:

why is about?&nbsp;
I want to add cover prop. make the item&nbsp;can be overridden .&nbsp;I can submit it if necessary.&nbsp;thanks for your help.&nbsp;


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jbaysolutions/vue-grid-layout"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月26日(星期三) 晚上8:43
收件人:&nbsp;"jbaysolutions/vue-grid-layout"<vue-grid-layout@noreply.github.com&gt;;
抄送:&nbsp;"栗子哥哥@"<1016817543@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [jbaysolutions/vue-grid-layout] how to build (#454)





 
yes

**Comment by MrSmallLiu** [comment]
Thank you very much. I have found the problem. because of the interactjs version problem. work fine when i using interactjs@1.6.3, problem when using more than 1.6.3.&nbsp; you can reproduce this problem . first remove node_modules&nbsp; then npm install and npm run build-lib




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jbaysolutions/vue-grid-layout"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月26日(星期三) 晚上8:43
收件人:&nbsp;"jbaysolutions/vue-grid-layout"<vue-grid-layout@noreply.github.com&gt;;
抄送:&nbsp;"栗子哥哥@"<1016817543@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [jbaysolutions/vue-grid-layout] how to build (#454)





 
yes
