### ISSUE TITLE
Want to achieve overlapping effects

### ISSUE THREAD

**Issue by LOUSANPANG** [jbaysolutions/vue-grid-layout#457]
### Desired result
achieve overlap
![`HRNRN~ }U`FA)4V@CG%H{E](https://user-images.githubusercontent.com/36870764/91372862-67cc8480-e847-11ea-815b-90fc379c08ea.png)

### Additional information
1. I try to modify the source code to achieve overlapping effects
![image](https://user-images.githubusercontent.com/36870764/91374181-2ee1df00-e84a-11ea-89c1-ceb3103f7fad.png)

![image](https://user-images.githubusercontent.com/36870764/91374112-25f10d80-e84a-11ea-8528-f58c1eed890e.png)

2. Repackage after modification, and found that the packaged file has problems running
![errror-chrome](https://user-images.githubusercontent.com/36870764/91374262-69e41280-e84a-11ea-9597-68f1052243f4.png)

3. It was found that there was a problem with the packaged file. (Twice as small as the previous packaging file)

4. Maybe I didn’t read the document carefully, and I didn’t find the overlapping function attribute 🌹

5. Hope to help me solve this problem soon, thank you ❤⭐

### Environmental information
```
- Platform: Web Google Chrome 84.0.4147.135
- Vue: 2.9.6
- vue-grid-layout: 2.3.8
- OS: Windows 10
- Node: 12.17.0
- Yarn: 1.22.4
```

**Comment by gmsa** [comment]
You don't need vue-grid-layout for that
