### ISSUE TITLE
Using `GridItem` inside a wrapped Vue Component breaks the UI

### ISSUE THREAD

**Issue by vinayakkulkarni** [jbaysolutions/vue-grid-layout#463]
**Software version (please complete the following information):**
 - Browser: Microsoft Edge 85.0.564.51 (Official build) (64-bit)
 - Vue Version: 2.6.11
 - Nuxt: 2.14.5
 - vue-grid-layout Version: 2.3.8

**Describe the bug**
When I try to wrap the `<grid-item />` inside another component, the grid items aren't shown correctly in the `<grid-layout> </grid-layout>`

**To Reproduce**
```html
<grid-layout
  :layout.sync="testLayout"
  :col-num="12"
  :row-height="50"
  :is-draggable="true"
  :is-resizable="true"
  :is-mirrored="false"
  :vertical-compact="true"
  :margin="[10, 10]"
  :use-css-transforms="true"
>
  <widget
    v-for="item in testLayout"
    :key="item.i"
    :widget-title="item.i"
    :widget-id="item.i"
    class="bg-gray-600 border-red-400"
    :widget-position-x="item.x"
    :widget-position-y="item.y"
    :widget-width="item.w"
    :widget-height="item.h"
  >
    {{ item.i }}
  </widget>
</grid-layout>
```
```js
testLayout: [
  { x: 0, y: 0, w: 2, h: 2, i: '0' },
  { x: 2, y: 0, w: 2, h: 4, i: '1' },
  { x: 4, y: 0, w: 2, h: 5, i: '2' },
  { x: 6, y: 0, w: 2, h: 3, i: '3' },
  { x: 8, y: 0, w: 2, h: 3, i: '4' },
  { x: 10, y: 0, w: 2, h: 3, i: '5' },
]
```

My `Widget.vue` is:
```html
<grid-item
    :x="widgetPositionX"
    :y="widgetPositionY"
    :w="widgetWidth"
    :h="widgetHeight"
    :i="widgetId"
  >
  <slot />
</grid-item>
```

**Expected behavior**
It shouldn't break the whole UI

**Screenshots**
Wrong:
<img width="1920" alt="Screenshot 2020-09-14 at 8 11 39 PM" src="https://user-images.githubusercontent.com/19776877/93100184-83001680-f6c6-11ea-94e0-8aa2e3d01778.png">

Correct:
<img width="1920" alt="Screenshot 2020-09-14 at 8 12 13 PM" src="https://user-images.githubusercontent.com/19776877/93100259-97dcaa00-f6c6-11ea-934e-bbe5a72b4d41.png">

**Additional context**
NA

**Comment by gmsa** [comment]
You're not supposed to wrap GridItem inside another component, it won't work.
