### ISSUE TITLE
Added a Drag from Outside example page

### ISSUE THREAD

**Issue by dhamet70** [jbaysolutions/vue-grid-layout#467]
Just succeeded an implementation of Drag from Outside.
I hope you will enjoy it :)

Pull request : https://github.com/jbaysolutions/vue-grid-layout/pull/466/commits/63de0655684cc549e577cc0241549e8dc4c3eaca

**Comment by fenngineering** [comment]
This might be a silly question, but I have got this working using the examples provided, how do you append some html divs into the newly created widget? all that seems to be able to do is display the "id" of the element.

I'm using `this.layouot.push` to add the item, however I don't see any options to change the markup.

I need to add more content than the ID of the, how do I go about doing this?

Thanks
Andy

**Comment by dhamet70** [comment]
https://www.codeseek.co/preview/jZOBeV
Tell me if it solves your problem or not.

     Dominique HAMET

[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
05/10/20
à 18:22:42

Le lun. 5 oct. 2020 à 18:11, Andrew Fenna <notifications@github.com> a
écrit :
