### ISSUE TITLE
Property "dragevent" does not exists on type Vue element "vuejs"

### ISSUE THREAD

**Issue by fenngineering** [jbaysolutions/vue-grid-layout#474]
Hello,

I'm using your example to drag from outside but i am getting the below issue:-
`property "dragevent" does not exists on type Vue element `

I'm converting the example to TypeScript, ie classed-based components and it seems on lines 53 and 57 of [10-drag-from-outside.js](https://github.com/jbaysolutions/vue-grid-layout/blob/master/examples/10-drag-from-outside.js) does not compile.

`  this.$refs.gridLayout.dragEvent('dragstart', 'drop', new_pos.x,new_pos.y,1,1); `

Is there something I am missing?

`

**Comment by gmsa** [comment]
If the example works, and yours in TypeScript doesn't, the problem is on your code...
