### ISSUE TITLE
I use vue3 with vite， got this error message ： external_commonjs_vue_commonjs2_vue_root_Vue_default.a is not a constructor

### ISSUE THREAD

**Issue by jok311** [jbaysolutions/vue-grid-layout#475]
I use vue3 with vite， got this error message below：

vue-grid-layout.js:1630 Uncaught (in promise) TypeError: external_commonjs_vue_commonjs2_vue_root_Vue_default.a is not a constructor
    at Proxy.created (vue-grid-layout.js:1630)

**Comment by jasonandjay** [comment]
why close this problem?how to resolve it? @gmsa

**Comment by SergeyKhval** [comment]
@jasonandjay @jok311 take a look at vue3 branch https://github.com/jbaysolutions/vue-grid-layout/tree/vue3

**Comment by betterRunner** [comment]
The issue is still there, have tried https://github.com/jbaysolutions/vue-grid-layout/tree/vue3 but getting the same error, any updates?

**Comment by SergeyKhval** [comment]
Sorry, my bad. The code is actually in this PR #470. Haven't noticed that is hadn't been merged into vue3 branch

**Comment by SergeyKhval** [comment]
@gmsa may be we can merge this PR so it will be a starting point for Vue 3 related work?

**Comment by betterRunner** [comment]
@SergeyKhval  Hi, thanks for the fast reply. I actually also tested the code in #470 by replacing the dist code to my node_modules/vue-grid-layout but stilling getting the same error.  Then I clone the code and try to build it locally but getting `[!] (plugin commonjs) SyntaxError: Unexpected token (2:4) in E:\code\demo\vue-grid-layout\src\components\GridItem.vue?vue&type=template&id=15f3b9ae&lang.js
src\components\GridItem.vue?vue&type=template&id=15f3b9ae&lang.js (2:4)`

**Comment by SergeyKhval** [comment]
What version of Node do you have? I think you'll need v12+ to run it in dev mode or build.
Just tried to run it in dev and build locally but everything seems fine.

**Comment by gmsa** [comment]
Just merged the PR @SergeyKhval . Thank you for the work.

**Comment by rhlatky** [comment]
Hello,
I have the same problem, even with the vue3 branch.

Vue version: 3.0.4
Node version: 14.15.3

When I clone and run the repository with the selected vue3 branch it works as expected.

In a moment when I try to use it from node modules, I'm getting external_commonjs_vue_commonjs2_vue_root_Vue_default.a is not a constructor error.

Also tried it with a new project with the same result.

**Comment by Radik24** [comment]
Hello, any update? Thanks

**Comment by jvjvjv** [comment]
> Hello, any update? Thanks

I've seen this issue when I use the main release, but if I use the vue3 release, e.g.,

```bash
npm rm vue-grid-layout
npm add vue-grid-layout@next
```

I had no problem. Hopefully this helps for now. But be aware that this version for Vue3 is a little outdated, and I don't know what features or bugfixes are missing from the vue3 version.

**Comment by Radik24** [comment]
Hi, thanks, I installed vue3-grid-layout-next and it's working.

**Comment by Sandyzhao19** [comment]
> Hi, thanks, I installed vue3-grid-layout-next and it's working.

`npm install vue3-grid-layout-next` works for me, thanks!
