### ISSUE TITLE
Why I can't use custom names in external configuration object?

### ISSUE THREAD

**Issue by nikolay-atamanyuk** [jbaysolutions/vue-grid-layout#476]
On the example said:

```
var testLayout = [
	    {"x":0,"y":0,"w":2,"h":2,"i":"0"},
	...
	];
...
<grid-layout
            :layout.sync="layout"
            ...
>
<grid-item v-for="item in layout"
                   :x="item.x"
                   :y="item.y"
                   :w="item.w"
                   :h="item.h"
                   :i="item.i"
                   :key="item.i">
            {{item.i}}
</grid-item>
</grid-layout>
```

and described like this:

>  GridLayout
>     layout
>         type: Array
>         required: true
>     This is the initial layout of the grid.
>     The value must be an Array of Object items. Each item must have i, x, y, w and h properties.
>
> GridItem
>     i
>         type: String
>         required: true
>     This is the unique identifier of the item.
> 
>     x
>         type: Number
>         required: true
>     Says what is a initial horizontal position of the item (in which column it should be placed).
>     The value must be a whole number.
> 

As I understand, the property of the object grid-layout.layout bind to external configuration array objects, and each element of this array bind to some property of grid-item object. We have the next scheme:
grid-layout.layout bind.sync to the external array
    grid-item.x bind to some property of item of an external array.

And in this place, I have a question: why I couldn't use custom names for properties of an **external** array, like this?

```
var testLayout = [
	    {"x":0,"y":0,"width":2,"height":2,"id":"0"},
	...
	];
...
<grid-layout
            :layout.sync="layout"
            ...
>
<grid-item v-for="item in layout"
                   :x="item.x"
                   :y="item.y"
                   :w="item.width"    <-- ordinary bind
                   :h="item.height"   <-- ordinary bind 
                   :i="item.id"           <-- ordinary bind 
                   :key="item.id">    <-- ordinary bind 
            {{item.id}}
</grid-item>
</grid-layout>
```

It looks like ordinary bind but works only with predefined names.

**Comment by gmsa** [comment]
The properties need those names because they are used in the GridLayout component.

**Comment by nikolay-atamanyuk** [comment]
Can I bind external properties on GridLaoyt too?

**Comment by gmsa** [comment]
no

**Comment by gmsa** [comment]
Do you have any idea on how to do it? If so, submit a PR

**Comment by nikolay-atamanyuk** [comment]
Ok, I try to investigate this.
