### ISSUE TITLE
Grid items overlapping when using this.$parent.autoSize()

### ISSUE THREAD

**Issue by savandriy** [jbaysolutions/vue-grid-layout#478]
**Software version:**
 - Browser: Google Chrome Version 85.0.4183.121 (Official Build) (64-bit)
 - Vue Version: 2.6.12
 - vue-grid-layout Version: 2.3.9
 - vuetify: 1.5.24 

**Describe the bug**
I'm trying to create a page with multiple cards with inputs. Each card has a button to add more inputs inside it. When adding new inputs, the cards start to overlap. 

Also, I'm using vuetify, and a stored layout, which is received from an ajax request. Then, in each card, on mounted and updated, I call this.$parent.autoSize().

You can see the behavior here:
https://codesandbox.io/s/musing-grass-9ldxn?file=/src/main.js

**To Reproduce**
1. Open the codesandbox
2. Click a few times on the plus icon on the cards
3. See the items overlapping

**Expected behavior**
The items don't overlap.

A really cool library, but the overlapping ruins the experience. 

Any ideas on how to fix it? Maybe I'm doing smth wrong? Maybe there are some hacks or smth?

**Comment by savandriy** [comment]
I've went through the source code, and have found a workaround.

I have created a CustomGridItem.vue component:

```vue
<script>
import VueGridLayout from 'vue-grid-layout';

export default {
  name: "CustomGridItem",
  extends: VueGridLayout.GridItem,
  methods: {
    calcWH(height, width) {
      const colWidth = this.calcColWidth();

      // replaced Math.round with Math.ceil
      // now grid items don't (usually) overlap
      let w = Math.floor((width + this.margin[0]) / (colWidth + this.margin[0]));
      let h = Math.ceil((height + this.margin[1]) / (this.rowHeight + this.margin[1]));

      // Capping
      w = Math.max(Math.min(w, this.cols - this.innerX), 0);
      h = Math.max(Math.min(h, this.maxRows - this.innerY), 0);

      return {w, h};
    },
  }
}
</script>
```

Now, when we're calculating height of the grid item in rows, we always round up to the next largest integer.
Sure, a lot of the times the items will be slightly larger. But at least they won't overlap.

Also, in my project, I sometimes get odd margins between elements. However, I noticed that when I resize the window, the odd margins disappear. So, I've added the following workaround in my project:

```vue
<grid-layout
    ref="grid"
    @layout-updated="onLayoutUpdated"
    ...
>
```

```vue
...
methods: {
    onLayoutUpdated: function () {
      // this allows for removing odd margins between grid items
      this.$refs.grid.onWindowResize();
    },
...
}
```

You can see the workarounds in action here, and compare the behavior:
original behavior - https://codesandbox.io/s/musing-grass-9ldxn?file=/src/main.js
patched - https://codesandbox.io/s/vigilant-pare-sle2m?file=/src/App.vue

**Comment by Flourad** [comment]
> I've went through the source code, and have found a workaround.
> 
> I have created a CustomGridItem.vue component:
> 
> ```
> <script>
> import VueGridLayout from 'vue-grid-layout';
> 
> export default {
>   name: "CustomGridItem",
>   extends: VueGridLayout.GridItem,
>   methods: {
>     calcWH(height, width) {
>       const colWidth = this.calcColWidth();
> 
>       // replaced Math.round with Math.ceil
>       // now grid items don't (usually) overlap
>       let w = Math.floor((width + this.margin[0]) / (colWidth + this.margin[0]));
>       let h = Math.ceil((height + this.margin[1]) / (this.rowHeight + this.margin[1]));
> 
>       // Capping
>       w = Math.max(Math.min(w, this.cols - this.innerX), 0);
>       h = Math.max(Math.min(h, this.maxRows - this.innerY), 0);
> 
>       return {w, h};
>     },
>   }
> }
> </script>
> ```
> 
> Now, when we're calculating height of the grid item in rows, we always round up to the next largest integer.
> Sure, a lot of the times the items will be slightly larger. But at least they won't overlap.
> 
> Also, in my project, I sometimes get odd margins between elements. However, I noticed that when I resize the window, the odd margins disappear. So, I've added the following workaround in my project:
> 
> ```
> <grid-layout
>     ref="grid"
>     @layout-updated="onLayoutUpdated"
>     ...
> >
> ```
> 
> ```
> ...
> methods: {
>     onLayoutUpdated: function () {
>       // this allows for removing odd margins between grid items
>       this.$refs.grid.onWindowResize();
>     },
> ...
> }
> ```
> 
> You can see the workarounds in action here, and compare the behavior:
> original behavior - https://codesandbox.io/s/musing-grass-9ldxn?file=/src/main.js
> patched - https://codesandbox.io/s/vigilant-pare-sle2m?file=/src/App.vue

Have you fixed this problem? when i use autoSize method, only the grid-layout's height resize, the grid-item's height not change, i don't know how to solve it.

**Comment by ygj6** [comment]
I've tried. The way **savandriy** offers is useful.
@Flourad Coulud you please provide your code? That's how we can find the problem.
