### ISSUE TITLE
"TypeError: Super expression must either be null or a function" when built with webpack on version 2.3.9

### ISSUE THREAD

**Issue by savandriy** [jbaysolutions/vue-grid-layout#479]
**Software version:**
 - Browser: Google Chrome Version 85.0.4183.121 (Official Build) (64-bit)
 - Vue Version: 2.6.12
 - vue-grid-layout Version: 2.3.9

**Describe the bug**
When vue-grid-layout is updated from 2.3.8 to 2.3.9, my project starts to throw an error when trying to open a page where the vue-grid-layout is used:

```
vendor.e2d7ffc643d1eaf0ca78.js:22 TypeError: Super expression must either be null or a function
    at 0.7047a8ba9ffdfea99f38.js:8
    at 0.7047a8ba9ffdfea99f38.js:8
    at 0.7047a8ba9ffdfea99f38.js:8
    at Object.5014 (0.7047a8ba9ffdfea99f38.js:8)
    at n (0.7047a8ba9ffdfea99f38.js:8)
    at Object.bc21 (0.7047a8ba9ffdfea99f38.js:8)
    at n (0.7047a8ba9ffdfea99f38.js:8)
    at Object.<anonymous> (0.7047a8ba9ffdfea99f38.js:8)
    at Object.2af9 (0.7047a8ba9ffdfea99f38.js:8)
    at n (0.7047a8ba9ffdfea99f38.js:8)

l | @ | vendor.e2d7ffc….js:22
-- | -- | --
  | (anonymous) | @ | vendor.e2d7ffc….js:22
  | (anonymous) | @ | vendor.e2d7ffc….js:22
  | (anonymous) | @ | vendor.e2d7ffc….js:22
  | Promise.then (async) |   |  
  | (anonymous) | @ | vendor.e2d7ffc….js:22
  | (anonymous) | @ | vendor.e2d7ffc….js:22
  | (anonymous) | @ | vendor.e2d7ffc….js:22
  | Lt | @ | vendor.e2d7ffc….js:22
  | (anonymous) | @ | vendor.e2d7ffc….js:22
  | g | @ | vendor.e2d7ffc….js:22
  | i | @ | vendor.e2d7ffc….js:22
  | i | @ | vendor.e2d7ffc….js:22
  | i | @ | vendor.e2d7ffc….js:22
  | i | @ | vendor.e2d7ffc….js:22
  | (anonymous) | @ | vendor.e2d7ffc….js:22
  | (anonymous) | @ | vendor.e2d7ffc….js:22
  | (anonymous) | @ | app.60df97a….js:1
  | g | @ | vendor.e2d7ffc….js:22
  | i | @ | vendor.e2d7ffc….js:22
  | i | @ | vendor.e2d7ffc….js:22
  | _t | @ | vendor.e2d7ffc….js:22
  | Ft.confirmTransition | @ | vendor.e2d7ffc….js:22
  | Ft.transitionTo | @ | vendor.e2d7ffc….js:22
  | e.push | @ | vendor.e2d7ffc….js:22
  | Wt.push | @ | vendor.e2d7ffc….js:22
  | w | @ | vendor.e2d7ffc….js:22
  | Wt | @ | vendor.e2d7ffc….js:1416
  | n | @ | vendor.e2d7ffc….js:1416
  | s._wrapper | @ | vendor.e2d7ffc….js:1416
```

Everything works fine on 2.3.8. 

**To Reproduce**
1. Build a project with webpack v3
2. Try open a page where vue-grid-layout is used

**Expected behavior**
No error.

**Screenshots**
![vue-grid-layout-2 3 9](https://user-images.githubusercontent.com/11334140/95350211-97e85800-08c8-11eb-9403-ccffc95e7bf0.PNG)

**Comment by gmsa** [comment]
Please provide a sample where we can reproduce the error

**Comment by yanjingwen** [comment]
I had the same problem.
![image](https://user-images.githubusercontent.com/22724674/95548999-db61d400-0a38-11eb-8174-aa4fe07984ab.png)

**Comment by yanjingwen** [comment]
I had the same problem.
![image](https://user-images.githubusercontent.com/22724674/95549086-1d8b1580-0a39-11eb-871d-1bed11e93c2d.png)

**Comment by abuteler** [comment]
Same problem. `"vue-grid-layout": "^2.3.8",` I had to remove the caret in my package json to keep it to 2.3.8 and have it work again on deploy. In my local environment the library worked well either way, so I've no idea where the problem might be.

**Comment by gmsa** [comment]
Can anyone try with version 2.3.10? I think it might be a problem with the version of interact.js used in version 2.3.9.

**Comment by savandriy** [comment]
When trying to build with 2.3.10, I get the following error:
```
ERROR in ./node_modules/vue-grid-layout/dist/vue-grid-layout.common.js
Module parse failed: Unexpected token (10332:31)
You may need an appropriate loader to handle this file type.
|     subModification.prepareStates(modifiers);
|     state.subModification = subModification;
|     subModification.startAll({ ...arg
|     });
|   },
```

When downgrading back to 2.3.8, everything works fine.

**Comment by gmsa** [comment]
@savandriy I've been trying to reproduce that error, with no luck. Can you setup a quick sample for me to test?

**Comment by baboon-king** [comment]
> When trying to build with 2.3.10, I get the following error:
> 
> ```
> ERROR in ./node_modules/vue-grid-layout/dist/vue-grid-layout.common.js
> Module parse failed: Unexpected token (10332:31)
> You may need an appropriate loader to handle this file type.
> |     subModification.prepareStates(modifiers);
> |     state.subModification = subModification;
> |     subModification.startAll({ ...arg
> |     });
> |   },
> ```
> 
> When downgrading back to 2.3.8, everything works fine.

This is still the case at 2.3.7

**Comment by baboon-king** [comment]
> @savandriy I've been trying to reproduce that error, with no luck. Can you setup a quick sample for me to test?

You can try this , config & lib are from the project where I have problems

https://github.com/baboon-king/vue-grid-layout_build_error_demo

**Comment by gmsa** [comment]
Working sample: https://github.com/jbaysolutions/vue-grid-layout-sample-v2

**Comment by gmsa** [comment]
Version 2.3.12-legacy shouldn't have these issues
