### ISSUE TITLE
Is there any way to cancel dragging?

### ISSUE THREAD

**Issue by ChenJiaH** [jbaysolutions/vue-grid-layout#481]
## If you have a feature request, please try to implement it before requesting it. <br/>This is free software and the author is busy with other projects.

**Is your feature request related to a problem? Please describe.**

I want to determine whether the target position is a placeable position and then decide whether to cancel the move.

**Describe the solution you'd like**
Such as [react-grid-layout](https://github.com/STRML/react-grid-layout) draggableHandle/draggableCancel/onDragStop/onDrag

**Describe alternatives you've considered**
Add event listener.

**Additional context**
Are there any other alternatives?

**Comment by gmsa** [comment]
GridItem dragIgnoreFrom and moveEvent/movedEvent

**Comment by ChenJiaH** [comment]
> GridItem dragIgnoreFrom and moveEvent/movedEvent: https://github.com/jbaysolutions/vue-grid-layout#griditem

How can i set the two styles of placeholder?
For example, the default style can be set by `.vue-grid-placeholder { background: blue}`, when it is moved to a unavailable place, I want to set the `.vue-grid-placeholder {background: red}`. But for now, I can only get and modify the attrs of `grid-item`.
Thanks.

**Comment by gmsa** [comment]
I don't think that's possible

**Comment by Sunxinqiang** [comment]
我是这样做的，提供一个判断是否能放置的函数，在@move时做判断，不能放置的话 改外层加一个error的class，然后通过样式覆盖。.error .vue-grid-placeholder {background: red} @ChenJiaH

**Comment by Sunxinqiang** [comment]
About cancel dragging, when moving set a variable to store the moving item's placeable, when @layout-updated  if placeable===false, i will reset the layout data (i have a data copy)

**Comment by ChenJiaH** [comment]
> About cancel dragging, when moving set a variable to store the moving item's placeable, when @layout-updated if placeable===false, i will reset the layout data (i have a data copy)

3q~
