### ISSUE TITLE
2.3.11 build error

### ISSUE THREAD

**Issue by foxFallingSkies** [jbaysolutions/vue-grid-layout#488]
ERROR in ./node_modules/vue-grid-layout/dist/vue-grid-layout.common.js
Module parse failed: Unexpected token (10332:31)
You may need an appropriate loader to handle this file type.
|     subModification.prepareStates(modifiers);
|     state.subModification = subModification;
|     subModification.startAll({ ...arg
|     });
|   },

**Comment by 00laughing00** [comment]
What is the solution?

**Comment by foxFallingSkies** [comment]
> What is the solution?

because the version 2.3.11, used es6 and when i build i exculde node_modules module 
so,you can use babel-loder to solute this question,just like this
{
        test: /\.js$/,
        use: {
          loader: 'babel-loader?cacheDirectory'
        },
        include: [
          resolve('src'),
          resolve('test'),
          resolve('node_modules/vue-grid-layout')
        ]
      },

**Comment by zjc2684613** [comment]
I had the same problem，but the solution didn't work

**Comment by foxFallingSkies** [comment]
> he same problem，but the solution didn't work

show me your babel-loader code
and this problem has other solution,that is just set package.json vue-grid-layout:@2.3.7

**Comment by zjc2684613** [comment]
> > he same problem，but the solution didn't work
> 
> show me your babel-loader code
> and this problem has other solution,that is just set package.json vue-grid-layout:@2.3.7

module: {
    rules: [
      {
        test: /\.js$/,
        loader: 'babel-loader',
        include: [
          resolve('src'), resolve('test'),
          resolve('node_modules/vue-grid-layout'),
        ]
      },
   ]
}

**Comment by gmsa** [comment]
We have a webpack sample using vue-grid-layout 2.3.11 here: https://github.com/jbaysolutions/vue-grid-layout-sample-v2

**Comment by zjc2684613** [comment]
> We have a webpack sample using vue-grid-layout 2.3.11 here: https://github.com/jbaysolutions/vue-grid-layout-sample-v2

If you try require babel-polyfill , you will find the problem. Modification_Modification in vue-grid-layout.common.js  is not compiled.

**Comment by redrockhorse** [comment]
You may use the wrong version. After 2.1.13 ,they use vue-cli to build it,not web-package.So you can npm i vue-grid-layout@2.1.13 -S instead,if you use vue early version

**Comment by tauanbinato** [comment]
Having the same issue with 2.3.11;; 2.3.7 is working fine.. i'm using vuetify with vue-cli

**Comment by accexs** [comment]
I did what @redrockhorse recommended and it worked, anyone knows the changes between 2.1 and 2.3? 

All i did was to create a project with vue-cli legacy `vue init webpack demo-vue-grid-layout` and `npm install vue-grid-layout --save`  to install the package, so it should work right out the box or am i missing something?

**Comment by tobyCurtis** [comment]
For what it's worth -- I was also working fine with 2.3.7.just like @tauanbinato but 2.3.11 was causing this error for me, and the require() fix did not work for me (it was already in place to make 2.3.7 work for me). 

I was trying to upgrade because I was not getting the responsive breakpoint change function firing. I ended updating to 2.3.8, and that allowed the function to work for me.

**Comment by Massionter** [comment]
when I use 2.3.11, it has a error called "export 'default' (imported as 'VueGridLayout') was not found in 'vue-grid-layout'

**Comment by Massionter** [comment]
After i use babel-loder to solute this question, I has a new error called "export 'default' (imported as 'VueGridLayout') was not found in 'vue-grid-layout'

**Comment by Massionter** [comment]
> > What is the solution?
> 
> because the version 2.3.11, used es6 and when i build i exculde node_modules module
> so,you can use babel-loder to solute this question,just like this
> {
> test: /.js$/,
> use: {
> loader: 'babel-loader?cacheDirectory'
> },
> include: [
> resolve('src'),
> resolve('test'),
> resolve('node_modules/vue-grid-layout')
> ]
> },

warning  in ./src/pages/shareBoard/index.vue

241:16-26 "export 'GridLayout' was not found in 'vue-grid-layout'

 warning  in ./src/pages/shareBoard/index.vue

242:14-22 "export 'GridItem' was not found in 'vue-grid-layout'

 warning  in ./src/pages/designBoardArea/edit/index.vue

321:16-26 "export 'GridLayout' was not found in 'vue-grid-layout'

 warning  in ./src/pages/designBoardArea/edit/index.vue

322:14-22 "export 'GridItem' was not found in 'vue-grid-layout'

**Comment by gmsa** [comment]
Version 2.3.12-legacy shouldn't have these issues

**Comment by OnlyForYouYaner** [comment]
我2.3.12的，要报错，卸载了改为2.3.7的就可以了

**Comment by vvoweniubai** [comment]
The same problem and i change the version to 2.3.7, it works

**Comment by vvoweniubai** [comment]
> 我2.3.12的，要报错，卸载了改为2.3.7的就可以了

感谢，解决了

**Comment by OnlyForYouYaner** [comment]
> > 我2.3.12的，要报错，卸载了改为2.3.7的就可以了
> 
> 感谢，解决了



> The same problem and i change the version to 2.3.7, it works

You're welcome

**Comment by vvoweniubai** [comment]
2.3.7 leads other problems and i find that my company uses 2.3.4, all work

**Comment by 2066873348** [comment]
> Version 2.3.12-legacy shouldn't have these issues

Thank you. It's settled
