### ISSUE TITLE
Compaction Type

### ISSUE THREAD

**Issue by Enderguard3** [jbaysolutions/vue-grid-layout#489]
## Compaction Type

I wonder if you consider adding the compaction type feature which is on the react-grid-layout project you inspire from.
It should be very useful for my project and I'm sure others person need that too.

Anyway, thanks for your job.

**Comment by Enderguard3** [comment]
My bad it was already implemented I'm kind of bad sometimes :)
thx for not paying attention at this issue

**Comment by gmsa** [comment]
There is no horizontal compaction right now
