### ISSUE TITLE
Module parse failed: Unexpected token (10332:31) at build

### ISSUE THREAD

**Issue by baboon-king** [jbaysolutions/vue-grid-layout#491]
### error message
error  in ./node_modules/vue-grid-layout/dist/vue-grid-layout.common.js

Module parse failed: Unexpected token (10332:31)
You may need an appropriate loader to handle this file type.
|     subModification.prepareStates(modifiers);
|     state.subModification = subModification;
|     subModification.startAll({ ...arg

 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/views/report/reportPreview.vue 75:0-44
 @ ./src/views/report/reportPreview.vue
 @ ./src/router/modules/quote.js
 @ ./src/router/index.js
 @ ./src/router/permission.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8081 webpack/hot/dev-server babel-polyfill ./src/main.js

### my version
node: v12.19.0 & v14
npm: 6.14.8
vue: ^2.5.2
vue-grid-layout: ^2.3.7
babel-loader: ^7.1.1

### solution 
> I know it's temporary 
> [It comes from the Internet](https://github.com/jbaysolutions/vue-grid-layout/issues/488#issuecomment-708232437)

```JavaScript
module: {
  rules: [
    {
      test: /\.js$/,
      loader: 'babel-loader',
      include: [
        resolve('src'),
        resolve('test'),
        resolve('node_modules/webpack-dev-server/client'),
        resolve('node_modules/vue-grid-layout') // add
      ],
    },
  ]
}
```
I hope to get the best solution ! thinks
but, my colleague build it successfully. His "Node" version is 11

**Comment by baboon-king** [comment]
after  vue-grid-layout: ^2.3.7 changed to  vue-grid-layout: 2.3.7  build successful

**Comment by gmsa** [comment]
Version 2.3.12-legacy shouldn't have these issues

**Comment by scyyc1** [comment]
Hi, I come up with the same problem. May I wonder what does it mean by your solution "^2.3.7 changed to vue-grid-layout: 2.3.7 build successful". Thx very much!!!

**Comment by baboon-king** [comment]
> Hi, I come up with the same problem. May I wonder what does it mean by your solution "^2.3.7 changed to vue-grid-layout: 2.3.7 build successful". Thx very much!!!

This is equivalent to locking at "2.3.7".
Before changing to "2.3.7", the actual installed version may be higher than "2.3.7" like 2.3.8, 2.3.9 ....
