### ISSUE TITLE
Drag and drop wrong position

### ISSUE THREAD

**Issue by nhupv** [jbaysolutions/vue-grid-layout#492]
**Software version (please complete the following information):**
 - Browser: Google Chrome
 - Vue Version:  2.6.11
 - vue-grid-layout Version: 2.3.8

**Describe the bug**
I'm trying to drag and drop element to grid layout but i have an issue.

CodeSandbox: [Describe the bug here](https://codesandbox.io/s/mutable-bush-khqnt?file=/src/App.vue)

**To Reproduce**
Steps to reproduce the behavior: Open CodeSandbox
1. Drag and drop div element to grid layout
2. Resize width the grid item just added
3. Drag and drop new element again
4. I got a bug that I cannot drag and drop item to last columns of grid layout

If i don't resize any grid item, it work fine. It only happens when I resize width the dropped grid item

Any ideas on how to fix it? Maybe I'm doing something wrong?

**Comment by JetTsang** [comment]
I've got the same bug. Do you know how to fix it ?
