### ISSUE TITLE
When a component is added, can it be calculated automatically “x” and “y”

### ISSUE THREAD

**Issue by panyouqing** [jbaysolutions/vue-grid-layout#494]
Hello

I would like to push a new data,How do I calculate the new "X"  and "Y", then add the new data

Thanks

**Comment by SergeyKhval** [comment]
Depends on where you want to insert it

**Comment by panyouqing** [comment]
> 取决于您要插入的位置



> Depends on where you want to insert it

Can I add new data to the right place,

Is this method available

**Comment by gmsa** [comment]
Example here: https://jbaysolutions.github.io/vue-grid-layout/guide/09-dynamic-add-remove.html

**Comment by panyouqing** [comment]
> Example here: https://jbaysolutions.github.io/vue-grid-layout/guide/09-dynamic-add-remove.html

thank you
but when you change the existing width and height, and then add a new item, the new position is wrong

**Comment by gmsa** [comment]
It's up to to implement the add method that suits your needs
