### ISSUE TITLE
此插件不兼容IE11 出错语句为  var v = t=>!(!t || !t.Window) && t instanceof t.Window;

### ISSUE THREAD

**Issue by wwLovejy** [jbaysolutions/vue-grid-layout#495]
此插件不兼容IE11 出错语句为  var v = t=>!(!t || !t.Window) && t instanceof t.Window;

**Comment by gmsa** [comment]
English only please

**Comment by wwLovejy** [comment]
var v = t=>!(!t || !t.Window) && t instanceof t.Window  This sentence reported an error in ie11 browser

**Comment by wwLovejy** [comment]
The example you wrote runs on ie11 browser and also reports an error

**Comment by gmsa** [comment]
Sorry, IE11 is not supported.

**Comment by wwLovejy** [comment]
I hope you update the component to support ie11, please

**Comment by wwLovejy** [comment]
Sorry，My English is so poor

**Comment by shailee-m** [comment]
> var v = t=>!(!t || !t.Window) && t instanceof t.Window This sentence reported an error in ie11 browser

@gmsa 
I am also getting the same error in IE11. Is there any fix for this?

**Comment by gmsa** [comment]
Version 2.3.12-legacy supports IE
