### ISSUE TITLE
Can i drag grid-item to other grid-layout ? 

### ISSUE THREAD

**Issue by DerrySongSN** [jbaysolutions/vue-grid-layout#496]
I have two grid-layout , and i want to drag-drop the inside grid-item form each other.  how can i do?

**Comment by gmsa** [comment]
You have to implement that yourself

**Comment by chen-junqiao** [comment]
> I have two grid-layout , and i want to drag-drop the inside grid-item form each other. how can i do?

Have you solved the problem, please
