### ISSUE TITLE
vue-grid-layout no longer works with Microsoft Edge.

### ISSUE THREAD

**Issue by petergoulettebeast** [jbaysolutions/vue-grid-layout#498]
**Software version (please complete the following information):**
 - Browser Microsoft Edge 44.19041.423.0
 - Vue Version 2.6.11
 - vue-grid-layout Version: 2.6.10 and 2.6.11

**Describe the bug**
Vue-grid-layout will not load in Edge Browser. An error occurs:
SCRIPT1028: Expected identifier, string or number

The sample site pages also do not load on Microsoft Edge browser.

**To Reproduce**
1. Open Microsoft Edge browser 44.19041.423.0 or older
2. Go to https://jbaysolutions.github.io/vue-grid-layout/guide/01-basic.html
3. Notice that the vue component does not load for grid layout. Console log will display:
SCRIPT1028: SCRIPT1028: Expected identifier, string or number

**Expected behavior**
Vue-grid-layout should work in Microsoft Edge. versions 2.3.9 and previous do work.

**Screenshots**
![image](https://user-images.githubusercontent.com/74570077/99312899-554d6000-2824-11eb-80c7-dc8ec83f3fc8.png)

**Comment by gmsa** [comment]
Try version 2.3.12-legacy
