### ISSUE TITLE
Not working with webpack dynamic import

### ISSUE THREAD

**Issue by LG0012** [jbaysolutions/vue-grid-layout#501]
Maybe someone have any solution how can i dynamicaly import that vendor into my specific component which requires vue-grid-layout? That component it self is alreay splitted and have own chunk.js. Whole project is pretty clean, and there is no weird messages in console, and with that vendor, i get - [interact.js] The "@interactjs/*/index" packages are not quite stable yet. Use them with caution.

I know, it's from dependency, but then, why i have to import and compile that vendor into whole bundle.js if i use it on only 1 place? So yeah, again, i need any suggestions how to make it work with dynamic import?

**Comment by gmsa** [comment]
The interact.js dependency is already included in the vue-grid-layout package, you don't need to import it again. You can ignore that warning.

**Comment by LG0012** [comment]
Why u closed the issue? :D Problem still exist - impossible to dynamicaly import your component.

**Comment by gmsa** [comment]
please provide a sample then

**Comment by LG0012** [comment]
Hmm, strange. Tried in clean vue-cli project and it worked. But still not working in work-environment :/ Any ideas?

![image](https://user-images.githubusercontent.com/8395034/100157084-a90a1a00-2eb2-11eb-838a-ff5aa4bc102c.png)
