### ISSUE TITLE
引入时报错

### ISSUE THREAD

**Issue by kkueo123456** [jbaysolutions/vue-grid-layout#506]
在组件里 import VueGridLayout from 'vue-grid-layout';时报错
Module parse failed: Unexpected token (10332:31)
You may need an appropriate loader to handle this file type.
|     subModification.prepareStates(modifiers);
|     state.subModification = subModification;
|     subModification.startAll({ ...arg
|     });
|   },

 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/pages/index/index.vue 6:0-44
 @ ./src/pages/index/index.vue
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main.js

**Comment by yzkno1** [comment]
遇到了同样的问题

**Comment by gmsa** [comment]
English only please

**Comment by haughtys** [comment]
指定安装旧版本就可以了，把前面的“^”符号去掉
 "vue-grid-layout": "2.3.4"

**Comment by gmsa** [comment]
Version 2.3.12-legacy shouldn't have these issues
