### ISSUE TITLE
An error occurred when the component was introduced ：You may need an appropriate loader to handle this file type.

### ISSUE THREAD

**Issue by kkueo123456** [jbaysolutions/vue-grid-layout#507]
Module parse failed: Unexpected token (10332:31)
You may need an appropriate loader to handle this file type.
| subModification.prepareStates(modifiers);
| state.subModification = subModification;
| subModification.startAll({ ...arg
| });
| },

**Comment by yihuoren** [comment]
We have the same problem

**Comment by yihuoren** [comment]
2.3.11

**Comment by gmsa** [comment]
duplicate of #488

**Comment by gmsa** [comment]
Version 2.3.12-legacy shouldn't have these issues
