### ISSUE TITLE
vue-grid-layout still not support vuejs 2?

### ISSUE THREAD

**Issue by jhawas** [jbaysolutions/vue-grid-layout#51]
Erorr: [Vue warn]: Invalid prop: type check failed for prop "layout". Expected , got Array.

**Comment by gmsa** [comment]
How about reading the readme file? https://github.com/jbaysolutions/vue-grid-layout/blob/master/README.md

**Comment by jhawas** [comment]
I'm using the version 2.1.6 but still have warning issue but not affect the features.

[HMR] bundle has 1 warnings
client.js?7955:161 ./~/vue-loader/lib/template-compiler?{"id":"data-v-a91cded0"}!./~/vue-loader/lib/selector.js?type=template&index=0!./src/components/Dashboard.vue
(Emitted value instead of an instance of Error) <grid-item v-for="item in layout">: component lists rendered with v-for should have explicit keys. See https://vuejs.org/guide/list.html#key for more info.
 @ ./src/components/Dashboard.vue 9:2-182
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

**Comment by gmsa** [comment]
Dashboard.vue is not a component of vue-grid-layout

**Comment by jhawas** [comment]
Yeah i'm the one who mid the component. here's my code

`<template>
  <div class="dashboard">
    <md-toolbar>
      <h1 class="md-title">{{ title }}</h1>
    </md-toolbar>
    
    <div class="main-content">
        <grid-layout
            :layout="layout"
            :col-num="12"
            :row-height="30"
            :is-draggable="true"
            :is-resizable="true"
            :vertical-compact="true"
            :margin="[10, 10]"
            :use-css-transforms="true"
        >

          <grid-item v-for="item in layout"
                   :x="item.x"
                   :y="item.y"
                   :w="item.w"
                   :h="item.h"
                   :i="item.i">
            {{item.i}}
        </grid-item>
        </grid-layout>
    </div>

  </div>
</template>

<style scoped>
    .main-content{
      padding: 0 10px;
      margin-top: 20px;
    }

    .vue-grid-item{
      background-color: green;
    }
</style>



<script>

import VueGridLayout from 'vue-grid-layout'

export default {

  name: 'Dashboard',
  components: {
    GridLayout: VueGridLayout.GridLayout,
    GridItem: VueGridLayout.GridItem
  },
  data () {
    return {
      title: 'Dashboard',
      layout: [
        {
          'x': 0,
          'y': 0,
          'w': 2,
          'h': 2,
          'i': '0'
        },
        {
          'x': 2,
          'y': 0,
          'w': 2,
          'h': 2,
          'i': '1'
        }
      ]
    }
  }
}
</script>
`

**Comment by BeiKeJieDeLiuLangMao** [comment]
@jhawas hi,i think maybe i meet the same question with you 
`"Erorr: [Vue warn]: Invalid prop: type check failed for prop "layout". Expected , got Array."`
i install vue-grid-layout by `npm install vue-grid-layout` ,but i get version1.x
after changing the package.json `"vue-grid-layout": "^2.1.6",` 
every is fine

**Comment by gmsa** [comment]
Change package.json to `"vue-grid-layout": "2.1.6"`

**Comment by BeiKeJieDeLiuLangMao** [comment]
thank god
