### ISSUE TITLE
Default export not found in vue-grid-layout

### ISSUE THREAD

**Issue by ash-lewis** [jbaysolutions/vue-grid-layout#511]
**Software version**
 - Browser chrome
 - Vue Version 2.6.12
 - vue-grid-layout Version: 2.3.11

**Describe the bug**
The vue-grid-layout doesn't seem to be exporting anything, therefore vue fails run the project with error message:
`"export 'default' (imported as 'VueGridLayout') was not found in 'vue-grid-layout'`

**To Reproduce**
1. npm install vue-grid-layout --save
2. import VueGridLayout from "vue-grid-layout"; (from any vue component)

**Comment by ash-lewis** [comment]
Fixed this by starting a fresh Vue project...

**Comment by Massionter** [comment]
I can't start my project by restart my project, why?
