### ISSUE TITLE
static element is still moved when other elements drag over

### ISSUE THREAD

**Issue by Flourad** [jbaysolutions/vue-grid-layout#512]
**Software version (please complete the following information):**
 - Browser [chrome]
 - Vue Version [2.6.12]
 - vue-grid-layout Version: [2.3.11]

**Describe the bug**
static element is still moved when other elements drag over，the grid-layout's layouts data is not from data，is from vuex store and is dynamic.The layouts can be added and removed.

Please use the [CodeSandbox Template](https://codesandbox.io/s/5wy3rz5z1x?module=%2Fsrc%2FShowcaseLayout.js) to demonstrate your bug. It is much easier for us to help you if you do.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Comment by At867604340** [comment]
The parameter name must be static
