### ISSUE TITLE
"vue": "2.6.12" & "vue-grid-layout": "^2.3.11", system fault...

### ISSUE THREAD

**Issue by Gregory-Han** [jbaysolutions/vue-grid-layout#514]
**Software version (please complete the following information):**
 - Browse: chrome 87.0.4280.88
 - Vue Version : 2.6.12
 - vue-grid-layout Version: 2.3.11

**Describe the bug**
Browser stop and fault;
Also announce a interactive.js problem.

**To Reproduce**
Infinitively loop.

**Expected behavior**

**Screenshots**
Infinitively loop.

**Additional context**

**Comment by gmsa** [comment]
Sorry, but "Infinitively loop." is not a proper description of the problem.
