### ISSUE TITLE
how to disable resize vertical

### ISSUE THREAD

**Issue by iamwelk** [jbaysolutions/vue-grid-layout#52]
I'm doing a project which only permit resize the element horizontally, but there is no option to fit. So how to disable the resize function of vertical direction？Thx~

**Comment by gmsa** [comment]
There's no support for that right now

**Comment by lhilton** [comment]
If I understand your question correctly, this might be solved using the **rowHeight** parameter. I have a similar requirement, and this is my configuration:

```
        <grid-layout
                :layout="layout"
                :colNum="12"
                :maxRows="1"
                :rowHeight="280"
                :isDraggable="true"
                :isResizable="true"
                :verticalCompact="true"
                :margin="[10, 10]"
        >
```

**Comment by lhilton** [comment]
In case the maxRows approach isn't workable for you, I played with a different solution using CSS to restrict this. You could also do something like this, where the height values align with your **rowHeight** value from the component parameter.

```
.vue-grid-item {
    min-height: 280px !important;
    max-height: 280px !important;
}

.vue-grid-item.vue-grid-placeholder {
    min-height: 280px !important;
    max-height: 280px !important;
}
```

Combine that with a vue watcher on the object you are storing the layout in to force the h value of each layout element to stay at 1 (or whatever size you want). This will keep your UI and your data consistent, and improved my own project a bit. I would still prefer a true solution in-built, but this was workable.

**Comment by iamwelk** [comment]
The `maxRows` parameter really works！Thank you~

**Comment by iamwelk** [comment]
@lhilton but there is another question，when I drag the item，it will auto position to the first row of layout area...

**Comment by iamwelk** [comment]
Finally, the css works right!

**Comment by lhilton** [comment]
If you still have issues with this:

> @lhilton but there is another question，when I drag the item，it will auto position to the first row of layout area...

You might be able to get the functionality you want by changing the grid-layout parameter:

`:verticalCompact="true"`

to this:

`:verticalCompact="false"`

**Comment by iamwelk** [comment]
I have already tried, it's not what I want~

**Comment by SergeyKhval** [comment]
If I get it right this line is responsible for vertical resizing:
https://github.com/jbaysolutions/vue-grid-layout/blob/master/src/GridItem.vue#L447

I monkey-patched that method by simply removing that line and vertical resizing got disabled

May be we can add another prop to `GridLayout` component and wrap that line in if statement. If that suits, I can send a PR

**Comment by gmsa** [comment]
Sure, you can submit a PR. But that new prop shouldn't have any effect if the isResizable prop is set to false
