### ISSUE TITLE
Prevent draging outside of the parent element

### ISSUE THREAD

**Issue by rin4ik** [jbaysolutions/vue-grid-layout#523]
Is it somehow possible to
prevent grid items to go outside of container div?

**Comment by rin4ik** [comment]
It is possible in react grid layout
https://strml.github.io/react-grid-layout/examples/16-bounded.html

**Comment by gmsa** [comment]
Can you submit a PR with that feature for vue-grid-layout?

**Comment by rin4ik** [comment]
@gmsa ready

**Comment by jan-br** [comment]
Some updates on this one?
