### ISSUE TITLE
Grid responsive does not work in vue3.

### ISSUE THREAD

**Issue by ygj6** [jbaysolutions/vue-grid-layout#529]
**Software version (please complete the following information):**
 - Vue Version [e.g. 3.0.0]
 - vue-grid-layout Version: [vue3](https://github.com/jbaysolutions/vue-grid-layout/tree/vue3)

**Describe the bug**
Add the parameter responsive="true" to App.vue, and the problem in the video below will appear:
https://youtu.be/9O8B5W1gWOg

**To Reproduce**
* Add the parameter responsive="true" to App.vue
```
    <GridLayout
            :responsive="true"
    >
```

**Comment by gmsa** [comment]
fix merged to vue3 branch
