### ISSUE TITLE
IE11 drag / resize not working

### ISSUE THREAD

**Issue by sharq1** [jbaysolutions/vue-grid-layout#545]
**Software version:**
 - Browser IE11
 - Vue Version 2.5.4
 - vue-grid-layout Version: 2.3.12-legacy

**Describe the bug**
Unable to drag / resize in IE11.
Getting this warning in console:
```
[interact.js] There are no listeners set for this action drag [object Object]
```
Works well in Chrome though.

**To Reproduce**
1. Set up demo example code from https://jbaysolutions.github.io/vue-grid-layout/guide/usage.html
2. Try dragging / resizing on IE11 - it will not work - see warning in console
3. The same works on Chrome

**Expected behavior**
I'm able to drag / resize on IE11

**Screenshots**
### console output
![image](https://user-images.githubusercontent.com/1241239/105182393-42f5e800-5b2d-11eb-89e1-f02ebfa73fea.png)

### IE11 version
![image](https://user-images.githubusercontent.com/1241239/105195611-15b03680-5b3b-11eb-97c5-30b6ebb0175f.png)

## Thanks
Thank you very much for deciding to support IE11! I hope the above is easy to fix.

**Comment by gmsa** [comment]
Can you provide a codesandbox/codepen sample, please?

**Comment by sharq1** [comment]
@gmsa sorry, but not sure how I could do that to test it with IE11 at the same time - I found no sandbox that supports IE11.

The example would be this: https://jsfiddle.net/fdye95tg/

But it would have to require these dependencies instead:
https://cdnjs.cloudflare.com/ajax/libs/vue/2.5.4/vue.min.js
https://raw.githubusercontent.com/jbaysolutions/vue-grid-layout/legacy/dist/vue-grid-layout.umd.min.js

**Comment by sharq1** [comment]
@gmsa I updated the fiddle above and it's using the right dependencies now, but still that can't be launched in IE11.

**Comment by sharq1** [comment]
Solved - it was [Cloudinary widget](//widget.cloudinary.com/v2.0/global/all.js) that was somehow conflicting.
It was enough to ensure that vue-grid-layout loads first and it works now!
Sorry for the hassle and thanks again for the great job!
