### ISSUE TITLE
[Question] Slower animation than react version?

### ISSUE THREAD

**Issue by MarcMagnin** [jbaysolutions/vue-grid-layout#55]
Hi,
I was looking at the react version and it seems to be more responsive when dragging items:
https://strml.github.io/react-grid-layout/examples/0-showcase.html
Is it related to the animation that as more delay or something like that?

Regards,
Marc

**Comment by gmsa** [comment]
Sorry, can't really see any visible difference looking at the showcases. 
The code that calculates positions and collisions is basically the same, so there shouldnt be much difference.
