### ISSUE TITLE
Cannot pass components through v-html

### ISSUE THREAD

**Issue by sejr** [jbaysolutions/vue-grid-layout#56]
As the [Vue.js documentation](https://vuejs.org/v2/api/#v-html) states, v-html cannot be used to pass components. That said, I am having difficulty using VueGridLayout because, in my layout, I'd like to allow users to add, remove, and interact with a wide variety of components. 

Any thoughts on how I should approach this?

**Comment by gmsa** [comment]
Have a look at https://github.com/jbaysolutions/vue-grid-layout-sample-v1/blob/master/index.html 

There is no issue in using a component inside a grid item:

````html
    <grid-layout
            :layout="layout"
            :col-num="12"
            :row-height="30"
            :is-draggable="true"
            :is-resizable="true"
            :vertical-compact="true"
            :margin="[10, 10]"
            :use-css-transforms="true"
    >
        <grid-item v-for="item in layout"
                   :x="item.x"
                   :y="item.y"
                   :w="item.w"
                   :h="item.h"
                   :i="item.i">
            <test-element :text="item.i"></test-element>
        </grid-item>
    </grid-layout>
````

**Comment by sejr** [comment]
I know that; the issue here is that it is impossible to use different components; if I do the approach you have suggested, I am limited to only using `test-element` in my grid layout. I have considered doing a rather clunky workaround, creating an encapsulating component that just uses `v-if` to determine which component to display. I feel like this would perform very poorly.

**Comment by gmsa** [comment]
You can use any component you declare. The business logic that defines which component should be used in each item is up to you. Thats not something this lib is trying to do.

We have used different components in draxed with `v-if` with no problem at all. If you don't like it that way, maybe take a look at dynamic components: https://vuejs.org/v2/guide/components.html#Dynamic-Components

**Comment by sejr** [comment]
I ended up using `v-if` in an encapsulating component and it seems to be working fine.

**Comment by abulka** [comment]
@sejr Presumably the encapsulating component e.g. `test-element` worked something like:

```html
<template>
  <div>
    <h1>{{ msg }}</h1>
    <button v-if="msg == 1">Click me</button>
    <input v-if="msg == 19">
    <textarea v-if="msg == 22"></textarea>
  </div>
</template>
```

In my case, I want to be able to drag out different kinds of form fields into the grid and the above approach works OK. 

I'll have to pass information into the encapsulating component to configure each kind of form field, which may not scale too well - will see how I go.
