### ISSUE TITLE
interact.js

### ISSUE THREAD

**Issue by MironenkoDeveloper** [jbaysolutions/vue-grid-layout#572]
Hi, how do I fix this error ?
![Screenshot 2021-03-03 at 18 25 48](https://user-images.githubusercontent.com/35580366/109828764-fcc49600-7c4d-11eb-926d-4c0381bbdd22.png)

**Comment by MironenkoDeveloper** [comment]
![Uploading Screenshot 2021-03-03 at 20.12.51.png…]()

**Comment by MironenkoDeveloper** [comment]
I can't set the environment in the project 
<img width="788" alt="Screenshot 2021-03-03 at 20 12 51" src="https://user-images.githubusercontent.com/35580366/109844209-f7bb1300-7c5c-11eb-9486-a1ec2a30e1b9.png">

**Comment by MironenkoDeveloper** [comment]
Hi @gmsa I need your help

**Comment by gmsa** [comment]
duplicate of #573
