### ISSUE TITLE
It was specified as a dependency of '@interactjs/interactjs'

### ISSUE THREAD

**Issue by moisesvni** [jbaysolutions/vue-grid-layout#573]
npm install or update @interactjs/clone@1.10.5 version do not exist, in package.json version is lasted in @interactjs

![image](https://user-images.githubusercontent.com/1066127/109839654-181bab00-7c26-11eb-8f38-58b1d3146313.png)

![image](https://user-images.githubusercontent.com/1066127/109840907-4ea5f580-7c27-11eb-81c9-904f5d69b9b0.png)

**Comment by gmsa** [comment]
https://github.com/taye/interact.js/issues/889

**Comment by moisesvni** [comment]
@gmsa thanks is OK now  
force installation is not legal, but installed  
npm i @interactjs/interactjs@1.10.3
