### ISSUE TITLE
Compiled in Dev Mode

### ISSUE THREAD

**Issue by Teddy-Schmitz** [jbaysolutions/vue-grid-layout#59]
Hello,
I am getting the "You are running Vue in development mode" message even when I compile my project with NODE_ENV=production.  From searching through my project the only thing I can find that is importing vue.common.js is vue-grid-layout, which looks like it was compiled without replacing process.env.NODE_ENV because I can still see it in the minified code.

Would it be possible to release a version with vue compiled in production mode.

**Comment by gmsa** [comment]
which version of vue-grid-layout and vue are you using?

**Comment by Teddy-Schmitz** [comment]
Vue 2.2.0 and vue-grid 2.1.6

**Comment by goalie7** [comment]
Hello! 

I have the same problem here with vue 2.3.3 and vue-grid 2.1.6.

One of the main problems of this is that even I disable vue-devtools for production mode, as it detects your component in development it shows the state of my application.

Despite of that, I would like to congratulate you all for that amazing component!

**Comment by goalie7** [comment]
I have solved it requiring the component this way:

```
const VueGridLayout = require('vue-grid-layout/dist/vue-grid-layout.min.js')
```
