### ISSUE TITLE
Is it possible to disable the drag cursor?

### ISSUE THREAD

**Issue by Jacks349** [jbaysolutions/vue-grid-layout#599]
This library is awesome, so thank you for your work! It's incredibly fun and easy to use. 

I created a grid with two items on each row, and inside of each items i have some forms and a chart. I was wondering if it's possible to disable dragging only in some parts of the item or, if it isn't possible, if i can disable the drag cursor and use the normal one instead.

The problem is that sometimes, while i use the form,  the item is moved, and i would like to avoid that, if possible.

**Comment by gmsa** [comment]
https://jbaysolutions.github.io/vue-grid-layout/guide/properties.html#dragignorefrom
https://jbaysolutions.github.io/vue-grid-layout/guide/04-allow-ignore.html
