### ISSUE TITLE
Incorrect "main" in package.json

### ISSUE THREAD

**Issue by marvinroger** [jbaysolutions/vue-grid-layout#6]
Hi,

When installing from npm, you want the `main` field of the `package.json` to point to the dist code.
So I guess [this](https://github.com/jbaysolutions/vue-grid-layout/blob/master/package.json#L15) should be `dist/vue-grid-layout.js` instead.

**Comment by gmsa** [comment]
[done](https://github.com/jbaysolutions/vue-grid-layout/releases/tag/2.0.1), thanks!
