### ISSUE TITLE
How to disable 'Drag' on child element

### ISSUE THREAD

**Issue by samyfox** [jbaysolutions/vue-grid-layout#60]
I would like to use the drag option but not on all the .vue-grid-item element.
How to disable inside a child element ?

With an iframe or a button inside a .vue-grid-item element, it's not dragable, this is the behavior that I want with a textarea.

**Comment by hkhandare** [comment]
You can use the 'dragIgnoreFrom' prop on Grid Item to achieve this.
Specify the child element names to disable drag from in the comma-separated string for the prop.
Defaults to:  `"a, button"`

`
<grid-item v-for="item in layout"
                           :x="item.x"
                           :y="item.y"
                           :w="item.w"
                           :h="item.h"
                           dragIgnoreFrom="a, button, textarea"
                           :i="item.i">
                    {{item.i}}
        </grid-item>
`

**Comment by samyfox** [comment]
Thanks, it works.
I can also specify a class or an id in the dragIgnoreFrom prop, nice !
