### ISSUE TITLE
How can i force re-size of an item?

### ISSUE THREAD

**Issue by Jacks349** [jbaysolutions/vue-grid-layout#602]
In my grid i need to edit an item's width and height from the code. The problem is that once the height or the width of an item is edited, the item will override other items, whereas if i resize manually this won't happen. I read on other issues that i need to call `resizeEvent` but i don't know how to do that. I also tried to call manually `this.layoutUpdatedEvent(this.layout)` but this didn't work.

**Comment by gmsa** [comment]
https://github.com/jbaysolutions/vue-grid-layout/pull/210
