### ISSUE TITLE
Mozilla Firefox bouncing while dragging

### ISSUE THREAD

**Issue by blaluc** [jbaysolutions/vue-grid-layout#61]
As already pointed out in other issues related to IE11 (e.g. #37 ), attached is the same strange behavior with the latest Firefox  (53.0.3 64 bit on Win10) (no issues with the react version)

![vuegrid_firefox](https://cloud.githubusercontent.com/assets/4599417/26395729/43d312a0-4071-11e7-871f-6a49a9fa8004.gif)

**Comment by ThePlastic** [comment]
I had that issue too, I solved this problem by simply deleting comments from line 26 of the GridItem.vue file as follows:
`.vue-grid-item.vue-draggable-dragging {
        transition:none;
        z-index: 3;
    }`

**Comment by llwinner** [comment]
How I import the GridItem.vue in my project? I got an error when i import GridItem.vue.I must import vue-grid-layout.js.
I changed GridItem.vue:
`.vue-grid-item.vue-draggable-dragging { transition:none; z-index: 3; }`
But my import like this:
`import VueGridLayout from './../../node_modules/vue-grid-layout/dist/vue-grid-layout'`
How to change vue-grid-layout.js or import GridItem.vue?
