### ISSUE TITLE
Why do I have an error when I just import component?Version is 2.3.11

### ISSUE THREAD

**Issue by Crys1om** [jbaysolutions/vue-grid-layout#616]
Module parse failed: Unexpected token (10106:31)
You may need an appropriate loader to handle this file type.
|     subModification.prepareStates(modifiers);
|     state.subModification = subModification;
|     subModification.startAll({ ...arg
|     });
|   },

**Comment by zhaoyinpeng** [comment]
https://github.com/jbaysolutions/vue-grid-layout/issues/488
