### ISSUE TITLE
Lacks documentation

### ISSUE THREAD

**Issue by insign** [jbaysolutions/vue-grid-layout#63]
I think I understood every props of this plugin but, some questions persists....

If an initial documentation be inserted in the README or in wiki section, I would help to continue...

**Comment by gmsa** [comment]
You mean like this? https://github.com/jbaysolutions/vue-grid-layout/blob/master/README.md
Or this? https://github.com/jbaysolutions/vue-grid-layout/tree/master/examples
Or this? https://github.com/jbaysolutions/vue-grid-layout-sample-v1
