### ISSUE TITLE
Vue3+vite   How to introduce and use

### ISSUE THREAD

**Issue by Muxin-007** [jbaysolutions/vue-grid-layout#637]

**Comment by marcelo-rebello** [comment]
For Vue 3 you can try
`npm i vue-grid-layout@3.0.0-beta1`
then in `main.ts` 
```
import { createApp } from 'vue'
import VueGridLayout from 'vue-grid-layout'
import App from './App.vue'
import router from './router'

const app = createApp(App)
app.use(router).use(VueGridLayout).mount('#app')
```

**Comment by lmssieh** [comment]
@marcelo-rebello thank you, it works.

this should be added to the docs.

**Comment by passioncsu** [comment]
> @marcelo-rebello thank you, it works.
> 
> this should be added to the docs.

Luckily I came here to see if there is a solution

**Comment by llzzii** [comment]
https://github.com/llzzii/merlin-vue3-template/tree/main/src/components/GridLayout

**Comment by annlumia** [comment]
> For Vue 3 you can try `npm i vue-grid-layout@3.0.0-beta1` then in `main.ts`
> 
> ```
> import { createApp } from 'vue'
> import VueGridLayout from 'vue-grid-layout'
> import App from './App.vue'
> import router from './router'
> 
> const app = createApp(App)
> app.use(router).use(VueGridLayout).mount('#app')
> ```

This is work for me.

### Quasar
For use in quasar, i added a boot file.

```ts
// src/boot/vue-grid-layout.ts
import { boot } from 'quasar/wrappers';

import VueGridLayout from 'vue-grid-layout';

export default boot(async ({ app }) => {
  app.use(VueGridLayout);
});


```

Modify quasar.config.js
```js
// quasar.config.js
  ...
    boot: ['routes-interceptor', 'axios', 'vue-grid-layout'],
  ...
```

Add declaration file
```ts
// src/vue-grid-layout.d.ts
declare module 'vue-grid-layout';
```

**Comment by bartimos** [comment]
something was wrong
"
A plugin must either be a function or an object with an "install" function.
"
