### ISSUE TITLE
layout validation

### ISSUE THREAD

**Issue by scottperreault** [jbaysolutions/vue-grid-layout#64]
Layout validation seems to only occur on the layout object which therefore doesn't allow customizing where the x,y,h,w properties come from through the html template.

I can't imagine that this is intended because if you add those properties to your objects, even if they are negative numbers, solely to pass the validation, it properly uses the html template configured properties to do the actual layout.

Look at the example to understand what I'm saying if anything is unclear.

[example.txt](https://github.com/jbaysolutions/vue-grid-layout/files/1045724/example.txt)

**Comment by gmsa** [comment]
Sorry, but I don't really understand what you're trying to show with your example.

**Comment by scottperreault** [comment]
Take a close look at the example.
Look at the testLayout var.
Notice what the html template references is x1, y1, h1, w1.
Notice how I have to include the x, y, h, and w properties to make the js console not throw errors.

You can see this by opening the above example as an html file and then open the below example as an html file... they are exactly the same except I've removed the x, y, h, and w properties which were set to -1 just to pass the layout validation.

[example.txt](https://github.com/jbaysolutions/vue-grid-layout/files/1046329/example.txt)

**Comment by gmsa** [comment]
Yes, I noticed that, I just don't understand why would you declare variables as x1, y1, w1 and h1 when you're not supposed to.

**Comment by scottperreault** [comment]
Not supposed to? You allow the configuration of these through the html template... It really seems like that is SUPPOSED to be configurable.

This is just an example. I wouldn't ACTUALLY use x1, y1, h1, and w1. I have a panel object that has a configuration object that stores the top, left, height, width, and displayOrder. I would like to be able to use the html template to point to the properties that I store on my objects, like your html template seems to imply that it supports.

I get around this currently by looping over all of my objects and adding the x, y, h, and w properties and assigning -1 to them... because they are not used.. at all.. except for validation of the layout object. That validation is wrong, it should be checking the properties that the view is configured to use. OR the view should not be configurable.

**Comment by gmsa** [comment]
x, y, h and w values are managed by the vue-grid-layout. If you want to the use the grid, you MUST store objects with those properties. That works for us and apparently everyone else who uses this component. 

If you think something isn't working the way it should, feel free to submit a PR with your improvements.

If that doesn't fit your needs, I'm sorry but probably this component isn't for you.

**Comment by scottperreault** [comment]
Well, created the pull request. I hope my change clears up any misunderstandings if there were any.
