### ISSUE TITLE
doesn't support low chrome version (chrome version <= 56) ?

### ISSUE THREAD

**Issue by kbd518** [jbaysolutions/vue-grid-layout#649]
**Software version (please complete the following information):**
 - Browser [<= chrome 56]
 - Vue Version [vue2.0]
 - vue-grid-layout Version: [2.3.12]

**Describe the bug**
doesn't support low version chrome  (chrome version <= 56) 

when loading page, it shows some required module are not supported, and report many errors on browser.

I want to know what is the lowest chrome version that vue-grid-layout-2.3.12 support? and what can I do if vue-grid-layout-2.3.12 doesn't support low version? can I use 2.3.12-legacy to resolve this problem?

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by gmsa** [comment]
try 2.3.12-legacy
