### ISSUE TITLE
响应式布局

### ISSUE THREAD

**Issue by lsqGitHub716** [jbaysolutions/vue-grid-layout#652]
3.0版本的响应是布局有问题，组件块会叠加到一起
![image](https://user-images.githubusercontent.com/65587928/155531914-fd2f564f-78bf-4f26-a49b-1fdc1a71ba31.png)

**Comment by geekFeier** [comment]
同问

**Comment by YananDong** [comment]
我也遇到这个问题了，挠头一天，最后是加了个v-if，因为布局参数是请求后请求到的，可能布局先行了，所以请求到参数之后，再让grid-layout渲染，就没有折叠了，不知道你的是不是同一种情况。

**Comment by gmsa** [comment]
English only please
