### ISSUE TITLE
How to register local component with vue-grid-layout@3.0.0-beta1?

### ISSUE THREAD

**Issue by shalom-lab** [jbaysolutions/vue-grid-layout#661]
Vue-grid-layout@3.0.0-beta1 has support registered grid-layout globally by `app.use()`. Howerer I want to build my vue component as a lib. So I want to register grid-layout locally ,what should I do to make it ?

**Comment by namespace-github** [comment]
Here is the example:
```javascript
import initGridLayout from 'vue-grid-layout';

[...]

// create vue app
const app = createApp(App);

[...]

initGridLayout(app);
```

Now you have access to

```html
<grid-layout />
<grid-item />
```

**Comment by shalom-lab** [comment]
Thank, let me have a try

**Comment by shalom-lab** [comment]
This is still a global component.

**Comment by shalom-lab** [comment]
> I found no way to register the grid-layout in an other way, so i use:
> 
> ```js
> import initGridLayout from 'vue-grid-layout';
> 
> [...]
> 
> // create vue app
> const app = createApp(App);
> 
> [...]
> 
> initGridLayout(app);
> ```
> 
> To have access to
> 
> ```
> <grid-layout />
> <grid-item />
> ```
> 
> I join the wish and the question to import the component as in version 2.

Thanks for your tips. I find a alternative solution by this.
![image](https://user-images.githubusercontent.com/49271035/160108312-04ea877f-d066-4a32-beb6-666abcda0426.png)
