### ISSUE TITLE
低版本chrome无法显示官网示例

### ISSUE THREAD

**Issue by the8th** [jbaysolutions/vue-grid-layout#662]
使用360浏览器的极速模式无法显示官网示例

控制台报错：uncaught SyntaxError: Unexpected token ...
判断是展开运算符没编译，低版本chrome内核不支持

360版本  ：360se9.1.0.424。
userAgent信息："Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36"

**Comment by gmsa** [comment]
English only please

**Comment by Ec2-slj** [comment]
> 使用360浏览器的极速模式无法显示官网示例
> 
> 控制台报错：uncaught SyntaxError: Unexpected token ... 判断是展开运算符没编译，低版本chrome内核不支持
> 
> 360版本 ：360se9.1.0.424。 userAgent信息："Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36"

部分脚手架默认不对node_moudles中的代码进行编译，使用vue-cli的可以直接配置transpileDependencies: [/[\\/]node_modules[\\/]_?vue-grid-layout[\\/]dist(.*)/]选项，把该插件代码包含进去，使用自定义webpack的配置的可以看下babel的设置是否包含node_moudles中的代码
