### ISSUE TITLE
help ! Vue3 : Invalid vnode type when creating vnode: undefined. 

### ISSUE THREAD

**Issue by zhangshilun** [jbaysolutions/vue-grid-layout#664]
Main.ts
`import VueGridLayout from 'vue-grid-layout';`

`const app = createApp(App);`
`app.use(VueGridLayout);`

index.vue
![image](https://user-images.githubusercontent.com/38464851/162424413-41786aa5-8b2e-45f8-a931-fe9c17e3d8f3.png)

preview page is blank
![image](https://user-images.githubusercontent.com/38464851/162424659-935d38ac-37e0-4630-a3e9-d40f66bffb11.png)

help me

**Comment by richthegxd** [comment]
Hi, how did you fix it?

**Comment by Nercus** [comment]
@richthegxd 
add 
`import VueGridLayout from 'vue-grid-layout'`
`app.use(VueGridLayout)`

to your main.ts file and remove the following line:
`import { GridLayout, GridItem } from 'vue-grid-layout'` (line# 27 in the picture above)
