### ISSUE TITLE
layout属性不能传入computed属性或者不是声明在data区域里的属性

### ISSUE THREAD

**Issue by zjlhope** [jbaysolutions/vue-grid-layout#667]
如下两种情况都有问题：
1)其中layout在computed声明时（为了执行逻辑得出layout):
  <grid-layout v-bind="getLayoutProps1()" :layout="layout">
     <grid-item v-for="item in layout"  :key=“item.i” v-bind="getGridItemProps1(item)">
      <span class="text">{{ item.i }}</span>
    </grid-item>
 </grid-layout>

  computed: {
    layout() {
      return [
        { x: 0, y: 0, w: 2, h: 2, i: '1' },
        { x: 2, y: 0, w: 2, h: 2, i: '2' },
        { x: 4, y: 0, w: 2, h: 2, i: '3' },
        { x: 6, y: 0, w: 2, h: 2, i: '4' },
        { x: 8, y: 0, w: 2, h: 2, i: '5' },
      ]
    },
  },
2) 执行方法返回props:
  getLayoutProps1() {
      return {
        layout: [
        { x: 0, y: 0, w: 2, h: 2, i: '1' },
        { x: 2, y: 0, w: 2, h: 2, i: '2' },
        { x: 4, y: 0, w: 2, h: 2, i: '3' },
        { x: 6, y: 0, w: 2, h: 2, i: '4' },
        { x: 8, y: 0, w: 2, h: 2, i: '5' },
      ],
        colNum: 12,
        rowHeight: 30,
        verticalCompact: false,
      }
    },
此时grid-layout绑定如下：
 <grid-layout v-bind="getLayoutProps1()">
     <grid-item v-for="item in layout"  :key=“item.i” v-bind="getGridItemProps1(item)">
      <span class="text">{{ item.i }}</span>
    </grid-item>
 </grid-layout>

**Comment by gmsa** [comment]
English only please
