### ISSUE TITLE
Is there a way to make grid-item overlap

### ISSUE THREAD

**Issue by bigbiglv** [jbaysolutions/vue-grid-layout#671]
## If you have a feature request, please try to implement it before requesting it. <br/>This is free software and the author is busy with other projects.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by bigbiglv** [comment]
Manually modify 'resizeEvent' and 'compactItem'

**Comment by oo10** [comment]
How did you achieve it
