### ISSUE TITLE
Lag behaviour while dragging quickly

### ISSUE THREAD

**Issue by piyushchauhan2011** [jbaysolutions/vue-grid-layout#68]
I just pondered around with `vue-grid-layout` and `react-grid-layout` library and it feels like there is a lag when try and drag the grid box quickly as compared to react version where the box always stays in sync with the pointer and feels more quick.

Is it because of performance or because of some animation lag we are using in `vue-grid-layout` ?

Here is the react version: https://strml.github.io/react-grid-layout/examples/0-showcase.html

**Comment by gmsa** [comment]
probably related to #37 and #61

**Comment by joshmn** [comment]
Easy fix:

`  .vue-resizable.resizing { pointer-events: none; }`

**Comment by joshmn** [comment]
I have found that the following styles greatly increase performance:

```
  .vue-grid-item.cssTransforms { transition-property: inherit !important; }
  .vue-resizable.resizing { pointer-events: none; }
  .vue-draggable-dragging { pointer-events: none; }
```

**Comment by piyushchauhan2011** [comment]
@joshmn It's great. Also I think this one is good too from @ThePlastic  as it preserves some transition `.vue-grid-item.vue-draggable-dragging { transition:none; z-index: 3; }` . Cheers 💯
