### ISSUE TITLE
Stopped working with Vue 2.7

### ISSUE THREAD

**Issue by lazer-hybiz** [jbaysolutions/vue-grid-layout#687]
**Software version (please complete the following information):**
 - Browser: chrome
 - Vue Version: 2.7
 - vue-grid-layout Version: 2.3.12

**Describe the bug**
Stopped working with Vue 2.7

**Comment by Yiddishe-Kop** [comment]
Changing these 4 props from `NaN` to `null` fixes it 😇 :

https://github.com/jbaysolutions/vue-grid-layout/blob/103b3c108b3bd971f047204aea5b10b7a933984e/src/components/GridItem.vue#L223-L226

I'll open a PR later.

**Comment by kingyue737** [comment]
Maybe  related to this issue? https://github.com/vuejs/vue/issues/12595

**Comment by kingyue737** [comment]
Fixed in Vue v2.7.1
