### ISSUE TITLE
how to show the grid line in "Gridlayout"

### ISSUE THREAD

**Issue by HasGenvts** [jbaysolutions/vue-grid-layout#689]
how can i do this ?

**Comment by joel-wenzel** [comment]
This can be done in pure css:
```
.grid::before {
    content: '';
    background-size: calc(calc(100% - 12px) / 12) 110px;
    background-image: linear-gradient(
        to right,
        lightgrey 1px,
        transparent 1px
      ),
      linear-gradient(to bottom, lightgrey 1px, transparent 1px);
    height: 100%;
    width: 100%;
    position: absolute;
    background-repeat: repeat;
    margin: 4px 6px;
}
```

My relevant GridLayout config

```
 <GridLayout
    class="grid flex-grow-1"
    :col-num="12"
    :margin="[12, 10]"
    :row-height="100"
    :use-css-transforms="true"
```

**Comment by HasGenvts** [comment]
我已经收到邮件了，我将会在稍后进行回复。I have received the email, I will reply later.

**Comment by gmsa** [comment]
@joel-wenzel thanks for the sample, I added it to the docs, but the lines seem to end a little outside of the container. Can you check what I have wrong? https://jbaysolutions.github.io/vue-grid-layout/guide/styling.html#grid-lines

**Comment by joel-wenzel** [comment]
@gmsa No problem. Slight adjustment to the css:
```
.grid::before {
    content: '';
    background-size: calc(calc(100% - 6px) / 12) 112px;
    background-image: linear-gradient(
        to right,
        lightgrey 1px,
        transparent 1px
      ),
      linear-gradient(to bottom, lightgrey 1px, transparent 1px);
    height: calc(100% - 6px);
    width: calc(100% - 6px);
    position: absolute;
    background-repeat: repeat;
    margin: 6px;
}
```
Still assuming a margin of 12 and rowHeight of 100

background size = calc(calc(100% - (margin/2)) / 12) rowHeight + margin;
height: calc(100% - (margin/2))
width: calc(100% - (margin/2))
margin: margin / 2

![image](https://user-images.githubusercontent.com/50124194/182737057-dc0cc991-8d99-4827-9e5b-6fe32cc9a91f.png)

**Comment by HasGenvts** [comment]
thanks.
I have already solved the problem.

**Comment by gmsa** [comment]
thanks @joel-wenzel !
