### ISSUE TITLE
Document is not defined

### ISSUE THREAD

**Issue by OguzcanKarakoc** [jbaysolutions/vue-grid-layout#702]
**Software version (please complete the following information):**
 - Browser Chrome
 - Vue Version 3 (I am using Nuxt3 , which is build in Vue3)     `"nuxt": "3.0.0-rc.6",`
 - vue-grid-layout Version: 2.4.0

**Describe the bug**

If I import `import { GridLayout, GridItem } from 'vue-grid-layout'` it gives me an error saying `document is not defined`.

**To Reproduce**
Simply importing in a nuxt3 project. 

**Expected behavior**
package to work

**Screenshots**
![image](https://user-images.githubusercontent.com/31690356/186241738-f00b5daa-5e00-4598-bc74-e774f00e7815.png)

**Additional context**

**Comment by gmsa** [comment]
vue-grid-layout v2 doesn't work on vue 3. Try the vue3 branch and check https://github.com/jbaysolutions/vue-grid-layout/issues/686 https://github.com/jbaysolutions/vue-grid-layout/issues/617 and https://github.com/jbaysolutions/vue-grid-layout/issues/439
