### ISSUE TITLE
关于元素对换的功能,不知是否有计划做?

### ISSUE THREAD

**Issue by chouchou723** [jbaysolutions/vue-grid-layout#709]
在使用的时候,发现比如我想让一个元素和另外一个元素的对换是没办法做到的,即使两个元素的尺寸是相同的,或者源元素是宽高是小于目标元素的,
所以想问下是否会有计划考虑做这样的一个功能?或者有没有其他可以实现的方法?
目前也没有看到其他gridlayout的插件有做出这样的一个功能..

**Comment by gmsa** [comment]
English only please
