### ISSUE TITLE
How to display the el-dialog component defined in the grid-item on the full screen.

### ISSUE THREAD

**Issue by Losery1021** [jbaysolutions/vue-grid-layout#717]
**Software version (please complete the following information):**
 - Browser [chrome]

 - Vue Version [3.2.6]
 - vue-grid-layout Version: [3.0.0beta]

**Describe the bug**
How to display the el-dialog component defined in the grid-item on the full screen.

**Screenshots**
![image](https://user-images.githubusercontent.com/76801182/198184687-25891230-9c91-4461-9222-605a65c544f3.png)

**Comment by webliuye** [comment]
@Losery1021 你好，请问一下这个怎么解决的？

**Comment by Losery1021** [comment]
> @Losery1021 你好，请问一下这个怎么解决的？

把弹窗组件写在最外层父组件里 然后子组件事件传递到父组件打开弹窗就可以了
![image](https://user-images.githubusercontent.com/76801182/202651183-de92c8cb-6b14-4fdd-92d9-37633ae1286a.png)

![image](https://user-images.githubusercontent.com/76801182/202651131-b28a9e0c-f552-4fee-ae89-14d21c046f2d.png)

**Comment by webliuye** [comment]
@Losery1021 我刚才解决了， 不过我是把那个 use-css-transforms 改成 false就行了。 它是 transform导致 fixed 失效了

**Comment by Losery1021** [comment]
> @Losery1021 我刚才解决了， 不过我是把那个 use-css-transforms 改成 false就行了。 它是 transform导致 fixed 失效了

ok 学到了
