### ISSUE TITLE
Possible to have grid in grid?

### ISSUE THREAD

**Issue by nickycdk** [jbaysolutions/vue-grid-layout#72]
At first test this does not seem to be supported - I have a grid layout, and each grid item then contains a custom component, which has X components that should act as tiles - Inside this component i would like to have a new grid layout, so it's possible to drag these component in the "parent" tile, all in the same application... It seems like something is going a bit wrong when doing this - See screenshot:

![screenshot](https://user-images.githubusercontent.com/7260291/27509505-ceef7446-58fe-11e7-94df-677d970ce895.PNG)

As you can see, seems the styling etc gets mixed up :(
So the question is: Is it possible to have grid in grid OR multiple grid layouts in same application ? Which is not the same case as in #32 

In my home component I have:
![home](https://user-images.githubusercontent.com/7260291/27509518-44c27aec-58ff-11e7-9815-27a82bf9db56.PNG)

then in component im inserting into the grid item contains:
![component](https://user-images.githubusercontent.com/7260291/27509519-49227eac-58ff-11e7-832e-f68255259c8d.PNG)

**Comment by gmsa** [comment]
I never tested it, but I don't think that will work
