### ISSUE TITLE
Resize and Drag is not working on Chrome, which was working earlier, but same thing works in Firefox

### ISSUE THREAD

**Issue by rohaanthakare** [jbaysolutions/vue-grid-layout#720]
We have implemented a component which uses vue-grid-layout, it was working about 1 month back, but now its not working in chrome, even examples give on https://jbaysolutions.github.io/vue-grid-layout/ are not working on chrome. Chrome version I am using is Version 107.0.5304.87 (Official Build) (64-bit)

**Comment by gmsa** [comment]
Working fine here with Chrome 107.0.5304.88 (Official Build) (64-bit)
