### ISSUE TITLE
Cursor changes into `not-allowed` while dragging from outside

### ISSUE THREAD

**Issue by mosuzi** [jbaysolutions/vue-grid-layout#723]
**Software version**
 - Browser Chrome 107.0.5304.88
 - Vue Version 2.7.10
 - vue-grid-layout Version 2.4.0

**Describe the bug**
Cursor changes into `not-allowed` while dragging from outside.
It is available just right in [this page:10-drag-from-outside](https://jbaysolutions.github.io/vue-grid-layout/guide/10-drag-from-outside.html)

**To Reproduce**
1. Drag item from outside
2. You find the cursor changes into `not-allowed`
3. Is there a way to prevent cursor from changing into `not-allowed`?

**Expected behavior**
Cursor changes into `grab`

**Comment by mosuzi** [comment]
I have solved this issue.

**Comment by AbdulKadirKhann** [comment]
@mosuzi I can still see this. How to change this to grabbing?

**Comment by mosuzi** [comment]
@AbdulKadirKhann Add @drop event listener to the element where you want dragging element to drop into.
