### ISSUE TITLE
安卓系统 Computed style 计算有错误，在操作了多行文本输入框之后

### ISSUE THREAD

**Issue by Chanzd** [jbaysolutions/vue-grid-layout#730]
[1](https://i.postimg.cc/YqdW3TDp/1.png)
[2](https://i.postimg.cc/134NYMbD/2.png)

如图1，利用VueGrid 布局了三个VueGridItem，在操作了安卓端手机的多行文本输入框之后，返回这个页面，就变成了如图2 的样子。
原来的VueGridItem的style 为 left 变成了 right，而且特别大 跑到了屏幕最左边。

**Comment by gmsa** [comment]
English only please, and follow the guidelines for posting an issue
