### ISSUE TITLE
How to drag&drop the "item" from another container into this grid?

### ISSUE THREAD

**Issue by Robin2009** [jbaysolutions/vue-grid-layout#74]
saying that I have another draggable list laying to the left of this grid-layout. I wander how to implement a feature like drag any item from the list then drop into my grid-layout and meanwhile I can still see a shadow under this "item" effects the current layout? Just like I was dragging an item inside this grid?  Any idea will be appreciated so much~

**Comment by gmsa** [comment]
Thats not supported as far as I know

**Comment by Robin2009** [comment]
Sad news...but anyway thanks for your reply.
