### ISSUE TITLE
version 3.0.0 breakpoint-changed event

### ISSUE THREAD

**Issue by jieun94** [jbaysolutions/vue-grid-layout#750]
**Software version (please complete the following information):**
 - Browser [chrome]
 - Vue Version [3.2.45]
 - vue-grid-layout Version: [3.0.0-beta1]

**Describe the bug**
When using the 3.0.0 version breakpoint-changed event, if the width decreases, the items overlap.

Please use the [CodeSandbox Template]
https://codesandbox.io/s/vue-grid-layout-sft1pr?file=/src/App.vue

**To Reproduce**
Reduce the browser's width.

**Expected behavior**
Items in the first column overlap with the added items without being pushed down.

**Screenshots**
![image](https://user-images.githubusercontent.com/65692593/219521845-f05e9d9b-751e-4315-983e-4da042b55143.png)
![image](https://user-images.githubusercontent.com/65692593/219521953-fa65144b-debc-41c4-aec9-ce1e409ec2c6.png)

**Additional context**
It works fine in 2.x versions.

**Comment by daklay** [comment]
yes same here

**Comment by Godzilla-Henry** [comment]
v-model:layout = "your layout" in Vue3
layout.sync = "your layout" in Vue2

**Comment by Kim-Sun-Kyo** [comment]
Has the issue been resolved? i still have problem. Should i wait for the release version, or is there another solution?
