### ISSUE TITLE
存在位置够确无法拉到对应位置的情况

### ISSUE THREAD

**Issue by minzhenyu** [jbaysolutions/vue-grid-layout#774]
**Software version (please complete the following information):**
本项目案例10

**Describe the bug**
在位置足够的情况下，拉取外部新的item 无法放到item末尾

**To Reproduce**
步骤
https://jbaysolutions.github.io/vue-grid-layout/zh/guide/10-drag-from-outside.html
1在这个页面中拉取新的item到第一个位置
2拉长item宽度
3然后重新拉取外部item 就无法放到第一个item后面，此时末尾位置是可以放下的

![image](https://github.com/jbaysolutions/vue-grid-layout/assets/12856051/bf94fa27-2e25-471e-bf35-c1b6623b8dd9)

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by minzhenyu** [comment]
<img width="816" alt="image" src="https://github.com/jbaysolutions/vue-grid-layout/assets/12856051/1e32713f-4e72-4263-92d5-d0dbfd89cf10">

**Comment by minzhenyu** [comment]
修改方案：
![image](https://github.com/jbaysolutions/vue-grid-layout/assets/12856051/7215bdfc-3232-4d61-8a18-fdae58a2248a)

使用时添加元素宽高
![image](https://github.com/jbaysolutions/vue-grid-layout/assets/12856051/f5bc6159-e37d-4f74-b63e-bf09c7cfb69e)

**Comment by latou19921203** [comment]
I also had the same issue, hope the author can fix it soon, thanks

**Comment by minzhenyu** [comment]
@gmsa
