### ISSUE TITLE
How to import the GridItem.vue

### ISSUE THREAD

**Issue by llwinner** [jbaysolutions/vue-grid-layout#78]
How to import the GridItem.vue in my project? I got an error when i import GridItem.vue.I must import vue-grid-layout.js.
I changed GridItem.vue:
.vue-grid-item.vue-draggable-dragging { transition:none; z-index: 3; }
But my import like this:
import VueGridLayout from './../../node_modules/vue-grid-layout/dist/vue-grid-layout'
How to change vue-grid-layout.js or import GridItem.vue?

**Comment by mohanzeal** [comment]
if you have installed vue-grid-layout from npm (npm install --save vue-grid-layout) then...
in any component you can use below statements


    import VueGridLayout from 'vue-grid-layout';
    var GridLayout = VueGridLayout.GridLayout;
    var GridItem = VueGridLayout.GridItem;

    export default {
         components: {
            GridLayout,
            GridItem,
        },
        data(){
            return {
            }
        }
    }

**Comment by llwinner** [comment]
Thanks for your reply! 
I mean that  i change the content of source code(GridItem.vue), but it doesn't reflected in the pages......
How can make changes to vue-grid-layout.js?
