### ISSUE TITLE
[Maintainance] Update branch vue3

### ISSUE THREAD

**Issue by ultravires** [jbaysolutions/vue-grid-layout#785]
Update branch vue3.

**Comment by gwinnem** [comment]
@ultravires 
Looks like this repo is dead.
[Try this one instead](https://github.com/gwinnem/vue-responsive-grid-layout)

**Comment by ultravires** [comment]
Looks like this repo is dead.

**Comment by tpoxa** [comment]
> @ultravires Looks like this repo is dead. [Try this one instead](https://github.com/gwinnem/vue-responsive-grid-layout)

unfortunately, that repo is dead too

**Comment by gwinnem** [comment]
> > @ultravires Looks like this repo is dead. [Try this one instead](https://github.com/gwinnem/vue-responsive-grid-layout)
> 
> unfortunately, that repo is dead too

Not dead. I just have had a busy time lately

**Comment by gmsa** [comment]
> > > @ultravires Looks like this repo is dead. [Try this one instead](https://github.com/gwinnem/vue-responsive-grid-layout)
> > 
> > 
> > unfortunately, that repo is dead too
> 
> Not dead. I just have had a busy time lately

Welcome to the club 😆

**Comment by gwinnem** [comment]
Feel free to give me a hand if you have some free time 😀
