### ISSUE TITLE
Question: Can We have nested grid items inside a gridlayout?

### ISSUE THREAD

**Issue by mohanzeal** [jbaysolutions/vue-grid-layout#79]
I want to create a Grid layout with nested Grid items. eg:
```
<grid-layout>
    <grid-item>
          <grid-item>
          </grid-item>
   </grid-item>
</grid-layout>
```

Can Items be nested inside one another! If so, how to design the layout object?

**Comment by gmsa** [comment]
You can't nest grid items.
