### ISSUE TITLE
how to disable animation when remove element from array

### ISSUE THREAD

**Issue by xralphack** [jbaysolutions/vue-grid-layout#80]
I used this.splice(this.layout, index, 1) to remove element from array
however related elements will re-render with animation
any suggestion?

**Comment by xralphack** [comment]
my work around is 
this.layout[this.selectedIndex] = {"x":0,"y":0,"w":0,"h":0,"i":this.selectedIndex};

**Comment by gmsa** [comment]
Sorry, don't really understand what you're trying to do....remove an element from the array without the other items changing position?

**Comment by xralphack** [comment]
yes, once remove an element from the array, other elemnts after that will reposition with animation.

**Comment by gmsa** [comment]
change vertical-compact to false

**Comment by xralphack** [comment]
already used, not work
