### ISSUE TITLE
Could not install ... node_modules/vue-grid-layout/libs/interact.js-1.3.0-alpha.4

### ISSUE THREAD

**Issue by semonje** [jbaysolutions/vue-grid-layout#88]
![image](https://user-images.githubusercontent.com/17279882/29414564-607975b6-8360-11e7-9872-bdf3f81c8bf0.png)

Seems like there is a problem with interact.js. Npm says that it doesn't have a package.json, so it's refusing me to install vue-grid-layout.

**Comment by gmsa** [comment]
Can you try with 2.1.8?

**Comment by semonje** [comment]
2.1.8 didn't, but 2.1.6 seems to be working

**Comment by gmsa** [comment]
should be fixed on 2.1.9
