### ISSUE TITLE
Error Problem When  Json response as String Params (x,y,h,w).

### ISSUE THREAD

**Issue by ixpingxi** [jbaysolutions/vue-grid-layout#90]
My project is getting the data from json api.
My JSON from API is
`{
  "data": {
    "items": [
      {
        "x": "0",
        "y": "0",
        "h": "2",
        "w": "2",
        "template": "button",
        "id": "0",
        "moved": "false"
      },
      {
        "x": "0",
        "y": "2",
        "w": "2",
        "h": "5",
        "i": "New",
        "template": "button",
        "id": "0",
        "moved": "false"
      }
    ]
  }
}`

**Comment by ixpingxi** [comment]
I try to put "parseInt()". but still not working

`        <input type="checkbox" v-model="draggable"/> Draggable
        <input type="checkbox" v-model="resizable"/> Resizable
        <br/>
        <grid-layout :layout="layout"
                     :col-num="12"
                     :row-height="30"
                     :is-draggable="draggable"
                     :is-resizable="resizable"
                     :vertical-compact="true"
                     :use-css-transforms="true"
        >
            <grid-item v-for="item in layout"
                       :x="parseInt(item.x)"
                       :y="parseInt(item.y)"
                       :w="parseInt(item.w)"
                       :h="parseInt(item.h)"
                       :i="parseInt(item.i)"
            >
            <span class="text">

                {{item.i}}
                <template-x  :row="item"></template-x>
            </span>
            </grid-item>
        </grid-layout>`

**Comment by gmsa** [comment]
All your json elements need the "i" property
