### ISSUE TITLE
Moved event not triggered for affected grid items

### ISSUE THREAD

**Issue by tho068** [jbaysolutions/vue-grid-layout#92]
Hello

Lets say I move a grid-item to some new location, and by doing this, some other items are moved away to make room for the newly moved item. This happens automatically with the items that are in the way when you move around a item.

But the problem (or maybe it is not supposed to work like that?), is that events are not triggered for the items that are moved to a new location as a result of moving an item to a new location.

**Comment by gmsa** [comment]
Hi,
Its supposed to only trigger the moved event on the dragged item.

**Comment by tho068** [comment]
Okey.

Maybe it should also trigger event for the others? I dont see any other easy way to update the server about the new locations. A solution would be to just store two copies of the layout, and compare them upon change, but that feels like a "hack".

**Comment by gmsa** [comment]
Why don't you just save the whole layout when an item is moved?

**Comment by tho068** [comment]
I could, just not that efficient to save something that is not a 100% changed.

But that is probably the cleanest solution I guess.

Sendt fra min iPhone

Den 24. aug. 2017 kl. 17.56 skrev Gustavo Santos <notifications@github.com<mailto:notifications@github.com>>:


Why don't you just save the whole layout when an item is moved?

-
