### ISSUE TITLE
Drag between grids

### ISSUE THREAD

**Issue by sebastianmacias** [jbaysolutions/vue-grid-layout#95]
I'm looking at the [multiple grids example](https://jbaysolutions.github.io/vue-grid-layout/examples/03-multiple-grids.html)  and wanted to know if it's possible to drag blocks between grids.

**Comment by sebastianmacias** [comment]
Similar to this: http://troolee.github.io/gridstack.js/demo/two.html

**Comment by pxljoy** [comment]
This isn't possible right now, at least vanilla-wise.
What is it exactly you're trying to accomplish? I'm sure you could "transfer" the grid item by changing the two layout arrays (by splicing one, pushing/slicing the other), however visually it wouldn't look as nice.

This functionality would be useful, though! 😄

**Comment by gmsa** [comment]
It's not possible do drag between grids
